Repository endoflife-date/endoflife.date, pull requests merged in 2021-08, with the labels that each got.

#331 [eks] EKS EoL dates are more specific now
  tools/eks.md
Labels: release-updates

#339 Latest Django Releases
  tools/django.md
Labels: release-updates

#340 Adds Ansible
  tools/ansible.md
Labels: new-product

#350 [openapi] Fix navbar URL
  _layouts/schema.html
Labels: bug

#354 [angular] Adds Angular Framework
  products/angular.md
Labels: new-product

#355 [java] Minor updates for Java
  products/java.md
Labels: release-updates

#361 [linux] Add Linux Kernel
  products/linuxkernel.md
Labels: new-product

#363 [freebsd] Add older freebsd releases
  .gitignore
  products/freebsd.md
Labels: release-updates

#357 [Godot] add changelogTemplate and update versions
  _layouts/post.html
  products/godot.md
Labels: enhancement

#358 [coldfusion] Adds Adobe ColdFusion
  products/coldfusion.md
Labels: new-product
