Repository endoflife-date/endoflife.date, pull requests merged in 2021-11, with the labels that each got.

#523 [Linux] Added kernel 5.15
  products/linuxkernel.md
Labels: release-updates

#521 [Debian] Update 9.x , modify lts/nonlts version structure
  products/debian.md
Labels: enhancement, release-updates

#519 Added CFEngine
  products/cfengine.md
Labels: new-product

#482 Created docker.md
  products/docker-engine.md
Labels: new-product

#487 Add Rocky Linux
  products/rockylinux.md
Labels: new-product

#528 [GitLab] Update 14.4.1, 14.3.4, 14.2.6
  products/gitlab.md
Labels: release-updates

#527 [Fedora Linux] Add 35
  products/fedora.md
Labels: release-updates

#526 Add a template for New Product Suggestions via Issues
  .github/ISSUE_TEMPLATE/new_product_suggestion.md
Labels: enhancement

#533 Update ansible.md
  products/ansible.md
Labels: release-updates

#536 [Python] 3.9.8 is out
  products/python.md
Labels: release-updates

#541 [GitLab] Update 14.4.2
  products/gitlab.md
Labels: release-updates

#542 [Visual Studio] Add 2022 version 17.0
  products/visualstudio.md
Labels: release-updates

#545 [Node.js] Update 17.1.0
  products/nodejs.md
Labels: release-updates

#543 [PowerShell] Add 7.2, Update 7.1 End-of-support
  products/powershell.md
Labels: release-updates

#544 [.NET] Add 6.0, Update 5.0.12 [.NET Core] Update 3.1.21 [.NET Framework] Add 3.5 SP1
  products/dotnet.md
  products/dotnetcore.md
  products/dotnetfx.md
Labels: release-updates

#551 [RabbitMQ] Update 3.9.9, 3.8.24
  products/rabbitmq.md
Labels: release-updates

#552 [Spring Framework] Update 5.3.13
  products/spring-framework.md
Labels: release-updates

#553 [.NET][.NET Core] Combine .NET and .NET Core
  products/dotnet.md
  products/dotnetcore.md
Labels: enhancement

#555 [RabbitMQ] Update 3.8.25
  products/rabbitmq.md
Labels: release-updates

#556 Update consul.md
  products/consul.md
Labels: release-updates

#557 [amazon-linux] Amazon Linux 2.0.20211103.0
  products/amazon-linux.md
Labels: release-updates

#558 [RockyLinux] update to 8.5
  products/rockylinux.md
Labels: release-updates

#559 [Redhat Linux] Update to 8.5
  products/redhat.md
Labels: release-updates

#561 [Linux] update its latest version info
  products/linuxkernel.md
Labels: release-updates

#565 [Laravel] Update supported and end of life
  products/laravel.md
Labels: product-fixes

#566 Update nomad.md
  products/nomad.md
Labels: release-updates

#567 [Laravel] add upcoming 9.x as a template and update older version
  products/laravel.md
Labels: release-updates

#568 [Python] 3.9.9 is out
  products/python.md
Labels: release-updates

#563 [Unity3d] add 2021.2 and update version infos
  products/unity.md
Labels: release-updates

#570 [GoLang] Update versions
  products/go.md
Labels: release-updates

#571 Show the latest version info even if its support ended
  _layouts/post.html
Labels: enhancement

#575 [GitLab] Add 14.5
  products/gitlab.md
Labels: release-updates

#573 [Kubernetes] Update 1.20.13, 1.21.7, 1.22.4
  products/kubernetes.md
Labels: release-updates

#574 [RabbitMQ] Update 3.8.26, 3.9.10
  products/rabbitmq.md
Labels: release-updates

#577 [Linux] 5.14 became EOL with its latest update, update version info
  products/linuxkernel.md
Labels: release-updates

#569 [Windows] Add 10 21H2
  products/windows.md
Labels: release-updates, product-fixes

#580 [mssqlserver] Update 2019 CU14
  products/mssqlserver.md
Labels: release-updates

#581 [alpine] Alpine Linux 3.15 release
  products/alpinelinux.md
Labels: release-updates

#586 [Blender] Start to use changelog template system
  products/blender.md
Labels: enhancement

#587 [alpine] Fix links
  products/alpinelinux.md
Labels: product-fixes

#582 [Wagtail] Update Version info
  products/wagtail.md
Labels: release-updates

#590 [php] Fix template of changelog , Add 8.1.x, Fix ordering for releases
  products/php.md
Labels: release-updates

#592 [Linux] Update version info
  products/linuxkernel.md
Labels: release-updates

#593 [Symfony] Update Versions, Add Upcoming versions as template
  products/symfony.md
Labels: release-updates

#597 [Ruby] Update Version info , add 3.1.x as template
  products/ruby.md
Labels: release-updates

#576 Update nomad.md
  products/nomad.md
Labels: release-updates

#591 [GitLab] Update 14.2.7, 14.3.5
  products/gitlab.md
Labels: release-updates

#595 [Docker Engine] Update to Latest Version, Cleanup Comments , Fix chan…
  products/docker-engine.md
Labels: release-updates

#599 [ubuntu] update version info
  products/ubuntu.md
Labels: release-updates

#602 [Firefox] version update
  products/firefox.md
Labels: release-updates
