Repository endoflife-date/endoflife.date, pull requests merged in 2021-09, with the labels that each got.

#369 [alpine] New releases, link fixes
  products/alpinelinux.md
Labels: release-updates

#366 Add NVIDIA driver
  products/linuxkernel.md
  products/nvidiadriver.md
Labels: new-product

#383 [layout] Add support for discontinued: true
  _layouts/post.html
Labels: enhancement

#393 [Drupal] Update new releases
  products/drupal.md
Labels: release-updates

#403 [iphone] Note about iOS 14 still being supported
  products/iphone.md
Labels: release-updates
