Repository endoflife-date/endoflife.date, pull requests merged in 2021-07, with the labels that each got.

#290 Update CentOS information
  tools/centos.md
Labels: release-updates

#299 Update php version info
  tools/php.md
Labels: release-updates

#307 Amazon EKS
  tools/eks.md
Labels: new-product

#315 [SEO] Configurable description for every page.
  _config.yml
  _includes/head_custom.html
Labels: enhancement

#314 Google Kubernetes Engine
  .gitignore
  .ruby-version
  Gemfile
  Gemfile.lock
  HACKING.md
  Rakefile
  _auto/gke.rb
  _config.yml
  _data/gke.yml
  _layouts/post.html
  _plugins/liquify.rb
  netlify.toml
  tools/gke.md
Labels: new-product

#320 [Symfony] Update Version Info
  tools/symfony.md
Labels: release-updates
