Repository endoflife-date/endoflife.date, pull requests merged in 2021-12, with the labels that each got.

#614 [nodejs] Update 17.2.0, 14.18.2
  products/nodejs.md
Labels: release-updates

#619 [gitlab] Update 14.5.1, 14.4.3
  products/gitlab.md
Labels: release-updates

#588 [mediawiki] 1.37 is out
  products/mediawiki.md
Labels: release-updates

#617 [angular] Update 13.0.3, 12.2.14
  products/angular.md
Labels: release-updates

#618 [nodejs] Update 16.13.1
  products/nodejs.md
Labels: release-updates

#622 [rabbitmq] Update 3.9.11
  products/rabbitmq.md
Labels: release-updates

#624 [Blender] Add 3.0
  products/blender.md
Labels: release-updates

#625 [amazon-linux] Add information about Amazon Linux 2022
  products/amazon-linux.md
Labels: release-updates, product-fixes

#627 [gitlab] Update 14.5.2, 14.4.4, 14.3.6
  products/gitlab.md
Labels: release-updates

#633 [angular] Update 13.1.0
  products/angular.md
Labels: release-updates

#546 Added VMware ESXi
  products/esxi.md
Labels: new-product

#641 [ESXi] Some minor and Cosmatics changes
  products/vmware-esxi.md
Labels: product-fixes

#643 [powershell] Update 7.2.1
  products/powershell.md
Labels: release-updates

#631 [kubernetes] Add 1.23
  products/kubernetes.md
Labels: release-updates

#642 [dotnet] Update 6.0.1, 5.0.13, 3.1.22
  products/dotnet.md
Labels: release-updates

#644 [Laravel] Updates
  products/laravel.md
Labels: release-updates

#645 [Update] Symfony 6.0.1 and 5.4.1
  products/symfony.md
Labels: release-updates

#638 Add new product : Looker
  products/looker.md
Labels: new-product

#647 [rails] Release updates
  products/ruby-on-rails.md
Labels: release-updates

#646 [iphone] iOS 14 is no longer supported
  products/iphone.md
Labels: product-fixes

#649 [angular] Update 13.1.1, 12.2.15
  products/angular.md
Labels: release-updates

#650 [kubernetes] Update 1.21.8, 1.20.14
  products/kubernetes.md
Labels: release-updates

#623 Add Citrix Virtual Apps and Desktops & VMware Horizon
  products/citrix-apps-desktops.md
  products/vmware-horizon.md
Labels: new-product

#547 Recommendations for maintainers
  index.md
  products/ruby.md
  recommendations.md
Labels: enhancement

#648 [Android] 8.1.x Reached EOL
  products/android.md
Labels: release-updates

#654 [log4j] Adds Log4j
  products/log4j.md
Labels: new-product

#657 [nodejs] Update 12.22.8
  products/nodejs.md
Labels: release-updates

#656 [kubernetes] Update 1.23.1,1.22.5
  products/kubernetes.md
Labels: release-updates

#655 [spring] Update 5.3.14, 5.2.19.RELEASE
  products/spring-framework.md
Labels: release-updates

#665 [nodejs] Update 17.3.0
  products/nodejs.md
Labels: release-updates

#667 [Unity3d] Update Version info
  products/unity.md
Labels: release-updates

#666 [Yocto] Update version info
  products/yocto.md
Labels: release-updates

#668 [gitlab] Add 14.6
  products/gitlab.md
Labels: release-updates

#677 [django] Fix link for 4.0 release
  products/django.md
Labels: product-fixes

#681 [Linux] Update version info
  products/linuxkernel.md
Labels: release-updates

#680 [blender] add 2.93.7
  products/blender.md
Labels: release-updates

#682 [dotnetframework] fix eol and release dates for 3.5sp1
  products/dotnetfx.md
Labels: product-fixes

#683 Remove locale from upstream URLs
  products/citrix-apps-desktops.md
  products/consul.md
  products/dotnetfx.md
  products/firefox.md
  products/iphone.md
  products/looker.md
  products/msexchange.md
  products/mssqlserver.md
  products/nomad.md
  products/nvidiadriver.md
  products/nvidiaproducts.md
  products/office.md
  products/visualstudio.md
  products/windows.md
  products/windowsEmbedded.md
  products/windowsServer.md
  recommendations.md
Labels: product-fixes

#685 Change Visual Studio servicing docs link to a generic one
  products/visualstudio.md
Labels: product-fixes

#688 Adds Electron
  CONTRIBUTING.md
  products/electron.md
  products/log4j.md
Labels: new-product
