Repository endoflife-date/endoflife.date, pull requests merged in 2022-10, with the labels that each got.

#1620 Improve contrast to meet WCAG
  _sass/custom/custom.scss
Labels: hacktoberfest-accepted

#1630 [mssqlserver] Update 2019 CU18, 2017 CU31
  products/mssqlserver.md
Labels: release-updates

#1614 [Qt] Add 6.4 release
  products/qt.md
Labels: release-updates

#1638 [debian] Add back minor versions
  products/debian.md
Labels: bug

#1634 VMWare: Switch EOL and Active Support
  products/vmware-esxi.md
  products/vmware-horizon.md
Labels: product-fixes

#1639 [wordpress] Collapse and reorder entries supported PHP versions
  products/wordpress.md
Labels: enhancement

#1642 [linux] Add 6.0
  products/linuxkernel.md
Labels: release-updates

#1631 [java] Add 19, Update 18.0.2.1, 17.0.4.1, 11.0.16.1
  products/java.md
Labels: release-updates

#1589 [API Platform] Add versions 3.0.0 and 2.7.0
  products/api-platform.md
Labels: release-updates

#1652 [pypi] PyPi Automation
  products/apache-airflow.md
Labels: enhancement

#1654 [apple] Add iOS,iPadOS,watchOS
  products/ios.md
  products/ipados.md
  products/iphone.md
  products/watchos.md
Labels: new-product

#1656 [openssl] Automate releases using git
  products/openssl.md
Labels: enhancement, product-fixes

#1659 [typo3] Add Automation
  products/typo3.md
Labels: product-fixes

#1672 [NewProduct] CakePHP
  products/cakephp.md
Labels: new-product

#1677 [CakePHP] fix a small duplicate key "latest" with value "3.10.4"
  products/cakephp.md
Labels: bug

#1047 [ansible] Split ansible into "ansible" and "ansible-core"
  products/ansible-core.md
  products/ansible.md
Labels: enhancement, new-product

#1678 [MongoDB] Add 6.1 (Rapid Release)
  products/mongodb.md
Labels: release-updates

#1679 [typo3] v12 released
  products/typo3.md
Labels: release-updates

#1690 Fix latest .NET 3.1 version
  products/dotnet.md
Labels: bug

#1667 [NewProduct] VMware vCenter
  products/vmware-vcenter.md
Labels: new-product

#1662 [pci] Adds PCI DSS Page
  products/pci-dss.md
Labels: new-product

#1675 [mssharepoint] Add SE & Oct updates
  products/mssharepoint.md
Labels: release-updates

#1698 [pci-dss] Fix category
  products/numpy.md
  products/pci-dss.md
Labels: product-fixes

#1699 [cassandra] Fix newline
  products/apache-cassandra.md
Labels: product-fixes

#1669 [NewProduct] VMware SRM
  products/vmware-srm.md
Labels: new-product

#1700 Fix #1685
  .github/config.yml
Labels: community

#1701 [citrix-app-desktops] Add 2203 CU1
  products/citrix-apps-desktops.md
Labels: release-updates, product-fixes

#1706 [Kindle] Add Kindle 11 and update to latest version infos
  products/kindle.md
Labels: release-updates

#1710 Update ansible-core.md
  products/ansible-core.md
Labels: bug

#1720 Add github icon
  _layouts/product.html
Labels: enhancement

#1705 [NewProduct] Mattermost
  products/mattermost.md
Labels: new-product

#1727 [vmware] October updates
  products/vmware-esxi.md
  products/vmware-horizon.md
  products/vmware-srm.md
  products/vmware-vcenter.md
Labels: release-updates

#1728 [nodejs] Add 19
  products/nodejs.md
Labels: release-updates

#1737 Add Python 3.11 release; 3.11.0 was released today
  products/python.md
Labels: release-updates

#1714 [Unity] Update latest version
  products/unity.md
Labels: release-updates

#1744 [NewProduct] Filebeat
  filebeat.md
Labels: new-product

#1753 [ipados] Add version 16, and update 15's latest version
  products/ipados.md
Labels: release-updates

#1757 [linux] Add missing eol date for 5.18
  products/linuxkernel.md
Labels: release-updates

#1754 [sles] Update latest release to SLES 15 SP4
  products/sles.md
Labels: release-updates

#1747 [New Product] Added Slackware GNU/Linux
  products/slackware.md
Labels: new-product

#1749 [New Product] Added Devuan GNU+Linux
  products/devuan.md
Labels: new-product

#1750 [New Product] Added MX Linux
  products/mxlinux.md
Labels: new-product

#1758 [New Product] Added NetBSD
  products/netbsd.md
Labels: new-product

#1764 [mxlinux] fix YAML
  products/mxlinux.md
Labels: product-fixes

#1763 [unity] Fix links
  products/unity.md
Labels: product-fixes

#1748 [New Product] Added antiX Linux
  products/antixlinux.md
Labels: new-product

#1767 [rocky] Fix image
  products/rockylinux.md
Labels: product-fixes

#1770 [dotnetfx] Add changelogTemplate and fix missing links
  products/dotnetfx.md
Labels: product-fixes

#1772 [vmware] Update release date
  products/vmware-esxi.md
Labels: release-updates
