Repository endoflife-date/endoflife.date, pull requests merged in 2022-06, with the labels that each got.

#1278 [nixos] Add 22.05, Use codename
  products/nixos.md
Labels: release-updates

#1275 [nodejs] Add cycles 13, 8
  products/nodejs.md
Labels: release-updates

#1284 [fix] Fix LTS date diff being considered as EOL diff
  _includes/ltslabel.html
Labels: bug

#1285 Update macos.md
  products/macos.md
Labels: product-fixes

#1287 [go] Update go URLs
  products/go.md
Labels: product-fixes

#1291 [nodejs] Add 11, 9, 1-7
  products/nodejs.md
Labels: release-updates

#1294 [mediawiki] Add 1.38, markdown cleanup
  products/mediawiki.md
Labels: release-updates

#1288 [es] Switch page to use major versions
  products/elasticsearch.md
Labels: product-fixes

#1295 [LinuxKernel] Update releases and change changelogTemplate
  products/linuxkernel.md
Labels: product-fixes

#1298 [python] update 3.10.5
  products/python.md
Labels: release-updates

#1296 [eks] New releases
  products/eks.md
Labels: release-updates

#1303 [k8s] Ignore old releases
  products/kubernetes.md
Labels: product-fixes

#1307 [blender] Fix changelogTemplate
  products/blender.md
Labels: bug

#1309 [kotlin] Add 1.7
  products/kotlin.md
Labels: release-updates

#1310 Fix broken VersionCommand info part
  _layouts/product.html
Labels: bug, product-fixes

#1311 [nodejs] v16 EOL date moved forward
  products/nodejs.md
Labels: product-fixes

#1312 Add Alpine 3.16.0
  products/alpinelinux.md
Labels: release-updates

#1325 [dotnet] Update git url
  products/dotnet.md
Labels: enhancement

#1323 [Python] Add 2.6 to chart
  products/python.md
Labels: release-updates

#1320 [Drupal] Fix Drupal 9.2 EOL date
  products/drupal.md
Labels: release-updates, product-fixes

#1318 [Qt] Update versions
  products/qt.md
Labels: release-updates

#1322 [drupal] Update 7.x version to 7.90
  products/drupal.md
Labels: release-updates

#1324 [mssqlserver] Update 2019, 2017, 2016, 2014
  products/mssqlserver.md
Labels: release-updates

#1326 [Drupal] Add 9.4 release
  products/drupal.md
Labels: release-updates

#1333 [kernel] 5.17 became EOL
  products/linuxkernel.md
Labels: release-updates, product-fixes

#1327 Add Oracle Linux
  products/oraclelinux.md
Labels: new-product

#1335 [visualstudio] Add 17.2 LTSC, Update 17.0 LTSC
  products/visualstudio.md
Labels: release-updates

#1338 [KDE Plasma] Add 5.25
  products/kdeplasma.md
Labels: release-updates

#1336 [kindle] Update to latest versions
  products/kindle.md
Labels: release-updates

#1340 [mssqlserver] Use releaseLabel
  products/mssqlserver.md
Labels: product-fixes

#1343 Add nginx 1.23, set eol for 1.21 and 1.20
  products/nginx.md
Labels: release-updates, product-fixes

#1345 [nix]: mark older releases as EOL
  products/nix.md
Labels: product-fixes

#1339 [mssqlserver] Reduce GDR details
  products/mssqlserver.md
Labels: product-fixes

#1344 [perl] Add 5.36, update support for 5.32 and 5.30
  products/perl.md
Labels: release-updates

#1347 [gitlab] Add 15.1
  products/gitlab.md
Labels: release-updates

#1316 Add Internet Explorer
  products/internetexplorer.md
Labels: new-product

#1351 Add Ansible 6.0
  products/ansible.md
Labels: release-updates

#1353 [dotnet] Fix eol dates and add 3.1.26
  products/dotnet.md
Labels: release-updates, product-fixes

#1349 [eks] Update EOL dates
  products/eks.md
Labels: product-fixes

#1362 [sharepoint] Update latest
  products/mssharepoint.md
Labels: release-updates

#1361 [msexchange] Update all versions, Add 2000-4.0
  products/msexchange.md
Labels: release-updates

#1360 Downgrade ruby temporarily
  .ruby-version
  Gemfile.lock
  netlify.toml
Labels: bug

#1363 [CFEngine] 3.18.2 and 3.15.6 released
  products/cfengine.md
Labels: release-updates
