Repository endoflife-date/endoflife.date, pull requests merged in 2022-01, with the labels that each got.

#693 [site] Link to recommendations in header
  README.md
  _config.yml
  recommendations.md
Labels: enhancement

#673 PAN GlobalProtect app
  products/pan-gp.md
Labels: new-product

#700 [gitlab] Update 14.6.1
  products/gitlab.md
Labels: release-updates

#692 Add Apache HTTP Server product
  products/apache-http-server.md
Labels: new-product

#707 [rabbitmq] Update 3.8.27
  products/rabbitmq.md
Labels: release-updates

#712 [rabbitmq] Update 3.9.12
  products/rabbitmq.md
Labels: release-updates

#715 [rails] Update 7.0.1
  products/ruby-on-rails.md
Labels: release-updates

#716 [golang] new releases
  products/go.md
Labels: release-updates

#723 [Kindle] Update Info
  products/kindle.md
Labels: release-updates

#670 Initial release of PAN-OS
  products/pan-os.md
Labels: new-product

#672 Initial release of PAN Cortex XDR
  products/pan-xdr.md
Labels: new-product

#728 Update nodejs.md
  products/nodejs.md
Labels: release-updates

#729 [electron] Update releases
  products/electron.md
Labels: release-updates

#731 [qt] Adds 5.15.8
  products/qt.md
Labels: release-updates

#732 [ansible] Ansible 4.10 is not supported
  products/ansible.md
Labels: release-updates

#733 [ansible] Ads Ansible 5.1.0
  products/ansible.md
Labels: release-updates

#738 [Laravel] Update to latest version
  products/laravel.md
Labels: release-updates

#737 [electron] New releases
  products/electron.md
Labels: release-updates

#741 [gitlab] Update 14.6.2, 14.5.3, 14.4.5
  products/gitlab.md
Labels: release-updates

#746 [angular] Update 13.1.2
  products/angular.md
Labels: release-updates

#744 [Consul] Added 1.11.x
  products/consul.md
Labels: release-updates

#748 [spring] Update 5.3.15
  products/spring-framework.md
Labels: release-updates

#736 Add nginx
  products/nginx.md
Labels: new-product

#750 [mssqlserver] Update 2017 CU28
  products/mssqlserver.md
Labels: release-updates

#752 [macos] Fix release specific links
  products/macos.md
Labels: product-fixes

#756 [nodejs] Update 17.4.0
  products/nodejs.md
Labels: release-updates

#760 [rabbitmq] Update 3.9.13
  products/rabbitmq.md
Labels: release-updates

#766 [angular] Update 13.1.3
  products/angular.md
Labels: release-updates

#767 [docs] Add Gitter.im badge on README
  README.md
Labels: enhancement

#771 [symfony] Update version info
  products/symfony.md
Labels: release-updates

#757 Fix Debian API URLs
  products/debian.md
Labels: product-fixes

#773 [eks] EoL for 1.18 changed
  products/eks.md
Labels: release-updates

#774 [Kubernetes] Add releaseImage and update version info
  products/kubernetes.md
Labels: release-updates

#770 [alpinelinux] add 3.14.3
  products/alpinelinux.md
Labels: release-updates

#769 [linux] Update version info
  products/linuxkernel.md
Labels: release-updates

#768 [java] upgrade to 8u312
  products/java.md
Labels: release-updates

#780 Add FFmpeg
  products/ffmpeg.md
Labels: new-product

#781 [openSuse] Add releaseImage
  products/opensuse.md
Labels: product-fixes

#782 [gitlab] Add 14.7
  products/gitlab.md
Labels: release-updates

#775 [Firefox] update versions
  products/firefox.md
Labels: release-updates

#786 Bump Django latest versions
  products/django.md
Labels: release-updates

#788 [kubernetes] Update 1.23.3
  products/kubernetes.md
Labels: release-updates

#791 [PHP] Update versions
  products/php.md
Labels: release-updates

#794 Update MediaWiki latest releases
  products/mediawiki.md
Labels: release-updates

#792 [django] Add Python Support information
  products/django.md
Labels: product-fixes

#795 [angular] Update 13.2.0, 12.2.16
  products/angular.md
Labels: release-updates

#796 [mssqlserver] Update 2019 CU15
  products/mssqlserver.md
Labels: release-updates
