Repository endoflife-date/endoflife.date, pull requests merged in 2022-05, with the labels that each got.

#1119 [powershell] Update 7.2.3, 7.1.7, 7.0.10
  products/powershell.md
Labels: release-updates

#1064 [ffmpeg] Update 5.0.1, 4.4.2, 4.3.4, Add actual and old releases
  products/ffmpeg.md
Labels: release-updates

#1121 [angular] Update 13.3.5
  products/angular.md
Labels: release-updates

#1122 [electron] Update 18.2.0, 17.4.2, 16.2.4, 15.5.3
  products/electron.md
Labels: release-updates

#1123 [mongodb] Update 5.0.8
  products/mongodb.md
Labels: release-updates

#1124 [rails] Update 7.0.2.4, 6.1.5.1, 6.0.4.8, 5.2.7.1
  products/ruby-on-rails.md
Labels: release-updates

#1126 Add UnrealIRCd to products
  products/unrealircd.md
Labels: new-product

#1133 [nodejs] Update 18.1.0
  products/nodejs.md
Labels: release-updates

#1135 [fedora] Update 34 EoL
  products/fedora.md
Labels: release-updates

#1131 [gitlab] Update 14.10.1, 14.9.4, 14.8.6
  products/gitlab.md
Labels: release-updates

#1132 [zabbix] Update 6.0.4, 5.0.23, 4.0.40
  products/zabbix.md
Labels: release-updates

#1130 [emberjs] Update 4.4.0
  products/emberjs.md
Labels: release-updates

#1136 [laravel] Update 9.11.0, 8.83.11
  products/laravel.md
Labels: release-updates

#1141 [elasticsearch] Add 8.2
  products/elasticsearch.md
Labels: release-updates

#1142 [nodejs] Update 14.19.2
  products/nodejs.md
Labels: release-updates

#1143 [angular] Update 13.3.6
  products/angular.md
Labels: release-updates

#1144 [electron] Update 18.2.1, 16.2.5, 15.5.4
  products/electron.md
Labels: release-updates

#1148 [electron] Update 17.4.3
  products/electron.md
Labels: release-updates

#1147 [gitlab] Update 14.10.2
  products/gitlab.md
Labels: release-updates

#1146 [ansible] Update 5.7.1
  products/ansible.md
Labels: release-updates

#1159 [rails] Update 7.0.3, 6.1.6, 6.0.5, 5.2.8
  products/ruby-on-rails.md
Labels: release-updates

#1134 [rabbitmq] Add 3.10
  products/rabbitmq.md
Labels: release-updates

#1160 [dotnet] Update 6.0.5, 5.0.17, Core 3.1.25
  products/dotnet.md
Labels: release-updates

#1161 [laravel] Update 9.12.0, 8.83.12
  products/laravel.md
Labels: release-updates

#1162 [rabbitmq] Update 3.8.31
  products/rabbitmq.md
Labels: release-updates

#1163 Add OpenSSL
  products/openssl.md
Labels: new-product

#1164 [rabbitmq] Update 3.10.1, 3.9.17
  products/rabbitmq.md
Labels: release-updates

#1165 [electron] Update 18.2.2
  products/electron.md
Labels: release-updates

#1166 [spring] Update 5.3.20, 5.2.22
  products/spring-framework.md
Labels: release-updates

#1167 [fedora] fedora 36 released
  products/fedora.md
Labels: release-updates

#1170 [angular] Update 13.3.7
  products/angular.md
Labels: release-updates

#1171 [electron] Update 18.2.3, 17.4.4, 16.2.6, 15.5.5
  products/electron.md
Labels: release-updates

#1169 [nomad] Add 1.3, Update 1.2.7, 1.1.13
  products/nomad.md
Labels: release-updates

#1172 [Drupal] Update 9.3.12 to 9.3.13, 9.2.18 to 9.2.19
  products/drupal.md
Labels: release-updates

#1177 [postgres] Update 14.3, 13.7, 12.11, 11.16, 10.21
  products/postgresql.md
Labels: release-updates

#1176 [php] Update 8.1.6, 8.0.19
  products/php.md
Labels: release-updates

#1182 [ubuntu] Update 20.04.4
  products/ubuntu.md
Labels: release-updates

#1185 [unity] add 2022.1 and update other latest tags
  products/unity.md
Labels: release-updates

#1179 Laravel 9.12.2
  products/laravel.md
Labels: release-updates

#1184 [surface] update EOL dates
  products/surface.md
Labels: release-updates, product-fixes

#1186 [moodle] Add 4.0 release
  products/moodle.md
Labels: release-updates

#1188 [mongodb] Add rapid cycle 5.3.1
  products/mongodb.md
Labels: release-updates

#1190 [ffmpeg] Update 4.2.7, 3.4.11, 3.2.18, 2.8.20
  products/ffmpeg.md
Labels: release-updates

#1191 [nix] Update 2.8.1
  products/nix.md
Labels: release-updates

#1198 Add issue template for incorrect details
  .github/ISSUE_TEMPLATE/report_incorrect_details.md
Labels: enhancement

#1193 [wagtail] Add 3.0
  products/wagtail.md
Labels: release-updates, product-fixes

#1201 [nodejs] Release update 14.19.3 & 18.2.0
  products/nodejs.md
Labels: release-updates

#1203 [Splunk] Release of Splunk 8.2.6 & 8.1.10
  products/splunk.md
Labels: release-updates

#1205 [Powershell] Update versions and cleanup
  products/powershell.md
Labels: release-updates, product-fixes

#1200 [rocky linux] Release update 8.6
  products/rockylinux.md
Labels: release-updates

#1209 [linux] Switch to the stable tree mirror
  products/linuxkernel.md
Labels: product-fixes

#1202 [wagtail] Declutter compatibility matrix
  products/wagtail.md
Labels: enhancement

#1211 [cfengine] Fix Link
  products/cfengine.md
Labels: product-fixes

#1214 [ror] Fix rails blog URL
  products/ruby-on-rails.md
Labels: product-fixes

#1215 [ubuntu] Fix link
  products/ubuntu.md
Labels: product-fixes

#1213 [godot] Update list of platforms URL
  products/godot.md
Labels: product-fixes

#1208 [unity] 2021 became LTS
  products/unity.md
Labels: product-fixes

#1220 [docker] Update 20.10.16
  products/docker-engine.md
Labels: release-updates

#1221 [laravel] Update 9.13.0, 8.83.13
  products/laravel.md
Labels: release-updates

#1227 [blender] Update 3.1.2, 3.0.1
  products/blender.md
Labels: release-updates

#1232 [gitlab] Update 14.10.3
  products/gitlab.md
Labels: release-updates

#1230 [rabbitmq] Update 3.10.2, 3.9.18, 3.8.32
  products/rabbitmq.md
Labels: release-updates

#1222 [electron] Update 18.2.4, 17.4.5, 16.2.7
  products/electron.md
Labels: release-updates

#1223 [angular] Update 13.3.9
  products/angular.md
Labels: release-updates

#1224 [vue] Update 3.2.35
  products/vue.md
Labels: release-updates

#1226 [linux] Update 5.17.9, 5.15.41, 5.10.117, 5.4.195
  products/linuxkernel.md
Labels: release-updates

#1231 [nomad] Update 1.3.1, 1.2.8, 1.1.14, 1.0 eol
  products/nomad.md
Labels: release-updates

#1225 [ansible] Update 5.8.0
  products/ansible.md
Labels: release-updates

#1234 [gitlab] Add 15.0
  products/gitlab.md
Labels: release-updates

#1238 [python] Fix Python regex
  products/python.md
Labels: bug

#1240 [mariadb] Add 10.8, Update 10.7.4, 10.6.8, 10.5.16, 10.4.25, 10.3.35, 10.2.44
  products/mariadb.md
Labels: release-updates

#1242 [kotlin] Fix auto config
  products/kotlin.md
Labels: bug

#1243 [auto] switch label to dockerhub
  CONTRIBUTING.md
  products/amazon-linux.md
  products/couchbase-server.md
  products/fedora.md
  products/godot.md
Labels: product-fixes

#1239 [electron] Add 19, Update 18.3.0, 16.2.8, 15.5.7, EoL 16, 15
  products/electron.md
Labels: release-updates

#1248 [tarantool] Fix releases sorting and add 2.10 series
  products/tarantool.md
Labels: release-updates, product-fixes

#1251 [linux] Add 5.18 series and update latest version
  products/linuxkernel.md
Labels: release-updates

#1252 [Surface] Fix eol and release dates of Surface Go
  products/surface.md
Labels: product-fixes

#1261 [EKS] Fix 1.19's EOL date and update latest tags
  products/eks.md
Labels: release-updates, product-fixes

#1263 Change issue template labels
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_product_suggestion.md
  .github/ISSUE_TEMPLATE/report_incorrect_details.md
Labels: community

#1262 Update humans.txt
  humans.txt
Labels: enhancement

#1266 [openbsd] Fix release -> releaseDate
  products/openbsd.md
Labels: bug

#1269 Fix links to HTTPS
  products/coldfusion.md
  products/eks.md
  products/emberjs.md
  products/mysql.md
  products/nvidiadriver.md
  products/react.md
Labels: product-fixes

#1274 [symfony] Add 6.1
  products/symfony.md
Labels: release-updates
