Repository endoflife-date/endoflife.date, pull requests merged in 2022-07, with the labels that each got.

#1370 [java] Update 18.0.1.1
  products/java.md
Labels: release-updates

#1377 [Composer] Update to latest versions add missing tags
  products/composer.md
Labels: release-updates

#1375 [CFEngine] Add 3.20 series and missing latestReleaseDate tags
  products/cfengine.md
Labels: release-updates, product-fixes

#1378 [vue] Relase ver 2.7.0 and fixed EoL date of v2.x
  products/vue.md
Labels: release-updates, product-fixes

#1379 [pan-xdr] Fix EOL date for 7.6
  products/pan-xdr.md
Labels: product-fixes

#1388 [couchbase] Add 7.1
  products/couchbase-server.md
Labels: release-updates

#1390 [auto] Mark products as custom-automated
  products/eks.md
  products/haproxy.md
  products/macos.md
  products/pan-gp.md
  products/unrealircd.md
Labels: enhancement

#1400 [dotnet] Update 3.1.27 and 6.0.7
  products/dotnet.md
Labels: release-updates

#1407 Update rockylinux.md
  products/rockylinux.md
Labels: release-updates

#1413 Update Netlify Build dependencies
  .ruby-version
  netlify.toml
  package-lock.json
  package.json
  runtime.txt
Labels: enhancement

#1422 [ffmpeg] 5.1 Relesed
  products/ffmpeg.md
Labels: release-updates

#1426 [pixel] add Pixel 6a
  products/pixel.md
Labels: release-updates

#1424 New product : Nextcloud [server]
  products/nextcloud.md
Labels: new-product

#1432 [solr] fix alternate urls
  products/solr.md
Labels: product-fixes

#1439 Add Roundcube 1.6.0
  products/roundcube.md
Labels: release-updates

#1443 Faster builds!
  _includes/nav.html
Labels: enhancement

#1437 [vmware-esxi] Update ESXi releases to latest
  products/vmware-esxi.md
Labels: release-updates
