Repository endoflife-date/endoflife.date, pull requests merged in 2022-04, with the labels that each got.

#988 [angular] Update 13.3.1
  products/angular.md
Labels: release-updates

#991 [Alpine] Update versions
  products/alpinelinux.md
Labels: release-updates

#983 [citrix-apps-desktops] Add 2203 & LTSLabel
  products/citrix-apps-desktops.md
Labels: release-updates

#996 [mssqlserver] Update 2017 CU29
  products/mssqlserver.md
Labels: release-updates

#995 [gitlab] Update 14.9.2, 14.8.5, 14.7.7, 14.6.7
  products/gitlab.md
Labels: release-updates

#998 [kotlin] Update 1.6.20
  products/kotlin.md
Labels: release-updates

#993 Add product React
  products/react.md
Labels: new-product

#1000 Update alpinelinux.md
  products/alpinelinux.md
Labels: release-updates

#1002 [gitlab] Update gitlab regex
  products/gitlab.md
Labels: product-fixes

#1001 [eks] Amazon EKS 1.22 released
  products/eks.md
Labels: release-updates

#1005 [macos] Attempt to clarify the n-1,n-2 problem
  products/macos.md
Labels: product-fixes

#1007 [django] Update latest versions
  products/django.md
Labels: release-updates

#1006 [spring] Fix missing v in template of changelog
  products/spring-framework.md
Labels: product-fixes

#1008 [nodejs] Update 12.22.12
  products/nodejs.md
Labels: release-updates

#1010 [New release] Ansible
  products/ansible.md
Labels: release-updates

#1011 [electron] Add 18.0.2, Update 17.4.0, Update 14.x EoL
  products/electron.md
Labels: release-updates

#1012 [laravel] Update 9.7.0, 8.83.7
  products/laravel.md
Labels: release-updates

#1013 [log4j] update to latest version
  products/log4j.md
Labels: release-updates

#1015 [angular] Update 13.3.2
  products/angular.md
Labels: release-updates

#1016 [firefox] Update 91.8.0, 99.0
  products/firefox.md
Labels: release-updates

#1023 [nodejs] Update 17.9.0
  products/nodejs.md
Labels: release-updates

#1021 [elixir] Update 1.13.4
  products/elixir.md
Labels: release-updates

#1020 [electron] Update 18.0.3, 16.2.2, 15.5.2
  products/electron.md
Labels: release-updates

#1022 [mongodb] Update 5.0.7
  products/mongodb.md
Labels: release-updates

#1032 [django] Update 4.0.4, 3.2.13, 2.2.28
  products/django.md
Labels: release-updates

#1033 [vue] Update 3.2.32
  products/vue.md
Labels: release-updates

#1034 [composer] Addback 2.x series with 2.3.4
  products/composer.md
Labels: release-updates

#1039 [qt] Add 6.3
  products/qt.md
Labels: release-updates

#1040 [ruby] Update 3.1.2, 3.0.4, 2.7.6, 2.6.10
  products/ruby.md
Labels: release-updates

#1037 [dotnet] Update 6.0.4, 5.0.16, 3.1.24
  products/dotnet.md
Labels: release-updates

#1046 [consul] Update 1.11.5, 1.10.10
  products/consul.md
Labels: release-updates

#1049 [vue] Update 3.2.33
  products/vue.md
Labels: release-updates

#1048 [gitlab] Update 14.9.3
  products/gitlab.md
Labels: release-updates

#1042 [spring] Update 5.3.19, 5.2.21
  products/spring-framework.md
Labels: release-updates

#1043 [rabbitmq] Update 3.9.15
  products/rabbitmq.md
Labels: release-updates

#1044 [angular] Update 13.3.3
  products/angular.md
Labels: release-updates

#1052 [consul] Update 1.9.17
  products/consul.md
Labels: release-updates

#1057 [firefox] Update 99.0.1
  products/firefox.md
Labels: release-updates

#1038 [php] Update 8.1.5, 8.0.18, 7.4.29
  products/php.md
Labels: release-updates

#1051 Add zabbix
  products/zabbix.md
Labels: new-product

#1068 Add information of reload4j fork
  products/log4j.md
Labels: product-fixes

#1067 [magento] Update 2.4.4
  products/magento.md
Labels: release-updates

#1065 [drupal] Update 9.3.11, 9.2.17
  products/drupal.md
Labels: release-updates

#1066 [laravel] Update 9.8.1
  products/laravel.md
Labels: release-updates

#1045 The Windows Server 2003 release date is incorrect on the site
  products/windows.md
  products/windowsServer.md
Labels: release-updates, product-fixes

#1072 [laravel] Update 9.9.0, 8.83.9
  products/laravel.md
Labels: release-updates

#1060 [NVIDIADriver] Update releases and branches
  products/nvidiadriver.md
Labels: release-updates

#1082 [Drupal] Update 9.3.11 to 9.3.12, 9.2.17 to 9.2.18
  products/drupal.md
Labels: release-updates

#1083 [consul] Add 1.12
  products/consul.md
Labels: release-updates

#1085 [angular] Update 13.3.4
  products/angular.md
Labels: release-updates

#1081 [kubernetes] Update 1.23.6, 1.22.9, 1.21.12
  products/kubernetes.md
Labels: release-updates

#1084 [electron] Update 18.1.0, 17.4.1, 16.2.3
  products/electron.md
Labels: release-updates

#1073 [mssqlserver] Update 2019 CU16
  products/mssqlserver.md
Labels: release-updates

#1080 [java] Update 18.0.1, 17.0.3, 11.0.15, 8u331, 7u341
  products/java.md
Labels: release-updates

#1074 [kotlin] Update 1.6.21
  products/kotlin.md
Labels: release-updates

#1078 [nix] Add 2.8
  products/nix.md
Labels: release-updates

#1089 [ubuntu] 22.04 Jammy Jellyfish released
  products/ubuntu.md
Labels: release-updates

#1087 Adds Talk Page URL
  _layouts/post.html
Labels: enhancement, community

#1093 [blender] Update 2.93.9, 2.83.20
  products/blender.md
Labels: release-updates

#1094 [elasticsearch] Update 8.1.3, 7.17.3
  products/elasticsearch.md
Labels: release-updates

#1098 [gitlab] Add 14.10
  products/gitlab.md
Labels: release-updates

#1086 [android] Add 12.1 (aka 12L)
  products/android.md
Labels: release-updates

#1099 LineageOS 19
  products/lineageos.md
Labels: release-updates

#1101 [lineage] fix date
  products/lineageos.md
Labels: product-fixes

#1107 [Qt] Add release image
  products/qt.md
Labels: enhancement

#1105 [lineageos] Fix date (again)
  products/lineageos.md
Labels: product-fixes

#1114 [lineageos] Fix EOL for 17.1
  products/lineageos.md
Labels: product-fixes

#1116 [tomcat] update version info
  products/tomcat.md
Labels: release-updates
