Repository endoflife-date/endoflife.date, pull requests merged in 2022-02, with the labels that each got.

#798 [nodejs] Update 14.19.0
  products/nodejs.md
Labels: release-updates

#800 [nodejs] 12.22.10 'Erbium' (LTS)
  products/nodejs.md
Labels: release-updates

#802 [linux] Update latest info
  products/linuxkernel.md
Labels: release-updates

#801 [electron] Update Electron releases
  products/electron.md
Labels: release-updates

#804 [symfony] Update the latest versions
  products/symfony.md
Labels: release-updates

#783 [api] Switch from jekyll-openapi to Stoplight Elements
  HACKING.md
  _includes/parameters.html
  _includes/request_body.html
  _includes/response.html
  _includes/schema.html
  _includes/schema/array.html
  _includes/schema/object.html
  _includes/schema/properties.html
  _includes/schema/reference.html
  _includes/utils/idify.html
  _includes/utils/query_string.html
  _includes/utils/request_method.html
  _includes/utils/response_status_code.html
  _includes/utils/titleize.html
  _includes/variables.html
  _layouts/schema.html
  assets/css/style.scss
  assets/js/bootstrap.min.js
  assets/js/jquery.min.js
  assets/js/prism.min.js
  assets/js/script.js
  schema.html
Labels: enhancement

#797 Add LineageOS
  products/lineageos.md
Labels: new-product

#805 move docs link from left to top nav
  _config.yml
  schema.html
Labels: bug

#806 Update GKE releases
  _data/gke.yml
  products/gke.md
Labels: release-updates

#814 Fix for empty releasePolicyLink bug
  _layouts/post.html
Labels: product-fixes

#816 [gitlab] Update 14.7.1, 14.6.4, 14.5.4
  products/gitlab.md
Labels: release-updates

#808 [angular] Update 13.2.1
  products/angular.md
Labels: release-updates

#817 [eks] Updated EoL dates
  products/eks.md
Labels: product-fixes

#815 Add Composer
  products/composer.md
Labels: new-product

#811 update contributing with missing options
  CONTRIBUTING.md
Labels: bug, enhancement

#829 [angular] Update 13.2.2
  products/angular.md
Labels: release-updates

#830 [rails] Update 7.0.2
  products/ruby-on-rails.md
Labels: release-updates

#831 [dotnet] Update 6.0.2, 5.0.14
  products/dotnet.md
Labels: release-updates

#832 [nodejs] Update 16.14.0
  products/nodejs.md
Labels: release-updates

#834 [gitlab] Update 14.7.2
  products/gitlab.md
Labels: release-updates

#833 [ci] Add Lighthouse CI
  .github/workflows/lighthouse.yml
Labels: enhancement

#819 Add jQuery
  products/jquery.md
Labels: new-product

#826 [SamsungMobile] Update relevant end of life dates
  products/samsungmobile.md
Labels: release-updates

#839 [go] New go releases
  products/go.md
Labels: release-updates

#844 [nodejs] Update 17.5.0
  products/nodejs.md
Labels: release-updates

#845 [kernel] Timeline image updated, latest versions updated
  products/linuxkernel.md
Labels: release-updates

#849 [consul] Update 1.11.3, 1.10.8, 1.9.15
  products/consul.md
Labels: release-updates

#852 Update electron.md
  products/electron.md
Labels: release-updates

#857 Update lineageos.md
  products/lineageos.md
Labels: product-fixes

#863 [spring] Update 5.3.16
  products/spring-framework.md
Labels: release-updates

#864 [Drupal] 7.88, 9.2.13, 9.36 have been released
  products/drupal.md
Labels: release-updates

#866 [angular] Update 13.2.3
  products/angular.md
Labels: release-updates

#865 [kubernetes] Update 1.23.4, 1.22.7, 1.21.10
  products/kubernetes.md
Labels: release-updates

#846 Adds Ember frontend framework
  products/emberjs.md
Labels: new-product

#872 [nodejs] Update 17.6.0
  products/nodejs.md
Labels: release-updates

#873 [gitlab] Add 14.8
  products/gitlab.md
Labels: release-updates

#871 [kindle] New release (5.14.2)
  products/kindle.md
Labels: release-updates

#869 [eks] New releases
  products/eks.md
Labels: release-updates

#878 [electron] New releases
  products/electron.md
Labels: release-updates

#882 [gitlab] Update 14.8.1
  products/gitlab.md
Labels: release-updates

#885 [gitlab] Update 14.8.2, 14.7.4, 14.6.5
  products/gitlab.md
Labels: release-updates
