Repository endoflife-date/endoflife.date, pull requests merged in 2022-03, with the labels that each got.

#881 [angular] Update 13.2.4
  products/angular.md
Labels: release-updates

#890 [Consul] Updates to 1.11.4, 1.10.9 and 1.9.16
  products/consul.md
Labels: release-updates

#894 [gitlab] Update 14.6.6
  products/gitlab.md
Labels: release-updates

#893 [angular] Update 13.2.5
  products/angular.md
Labels: release-updates

#898 [Drupal] 9.3.7
  products/drupal.md
Labels: release-updates

#862 [jekyll] Enable jemoji plugin
  Gemfile
  Gemfile.lock
  _config.yml
  _headers
Labels: bug

#896 [Laravel] Update to 9.3
  products/laravel.md
Labels: release-updates

#903 [go] New releases
  products/go.md
Labels: release-updates

#902 [amazon-linux] New release: 2.0.20220218.1
  products/amazon-linux.md
Labels: release-updates

#913 [openbsd] hide support column and update summary
  products/openbsd.md
Labels: product-fixes

#914 [dotnet] update to latest versions
  products/dotnet.md
Labels: release-updates

#908 [blender] New 3.1 released
  products/blender.md
Labels: release-updates

#915 [composer] update newer versions , temporaryly disable 2.2 version
  products/composer.md
Labels: release-updates

#912 [citrix-apps-desktops] update to latest version
  products/citrix-apps-desktops.md
Labels: release-updates

#916 [Drupal] 9.2.14
  products/drupal.md
Labels: release-updates

#917 [rails] Update 7.0.2.3, 6.1.5, 6.0.4.7, 5.2.7
  products/ruby-on-rails.md
Labels: release-updates

#919 [gitlab] Update 14.7.5
  products/gitlab.md
Labels: release-updates

#925 [Python] Update 3.10.2 to 3.10.3, 3.9.10 to 3.9.11, 3.8.12 to 3.8.13, 3.7.12 to 3.7.13
  products/python.md
Labels: release-updates

#923 [nodejs] Update 16.14.1
  products/nodejs.md
Labels: release-updates

#931 [Unity] Update releases
  products/unity.md
Labels: release-updates

#929 [kubernetes] Update 1.23.5, 1.22.8, 1.21.11
  products/kubernetes.md
Labels: release-updates

#926 [powershell] Update 7.2.2, 7.1.6, 7.0.9
  products/powershell.md
Labels: release-updates

#927 [angular] Update 13.3.0
  products/angular.md
Labels: release-updates

#933 [Laravel] Update 9.x and 8.x
  products/laravel.md
Labels: release-updates

#934 [PHP] Update 8.0 and 8.1
  products/php.md
Labels: release-updates

#936 [nodejs] Update 17.7.2, 16.14.2, 14.19.1, 12.22.11
  products/nodejs.md
Labels: release-updates

#827 Add KDE Plasma
  products/kdeplasma.md
Labels: new-product

#938 [composer] Update 2.2.9
  products/composer.md
Labels: release-updates

#942 Add Microsoft SharePoint
  products/mssharepoint.md
Labels: new-product

#911 Add AlmaLinux
  products/almalinux.md
Labels: new-product

#944 Add Azure DevOps
  products/azure-devops.md
Labels: new-product

#940 Added Vue.js
  assets/openapi.yml
  products/vue.md
Labels: new-product

#930 Adds Tomcat
  products/tomcat.md
Labels: new-product

#909 Add Tarantool page
  products/tarantool.md
Labels: new-product

#949 New Alpine releases
  products/alpinelinux.md
Labels: release-updates

#948 Update amazon-linux.md
  products/amazon-linux.md
Labels: release-updates

#955 Add Java 18
  products/java.md
Labels: release-updates

#952 [rabbitmq] Update 3.9.14, 3.8.28
  products/rabbitmq.md
Labels: release-updates

#953 [nodejs] Update 17.8.0
  products/nodejs.md
Labels: release-updates

#951 [kernel] Linux 5.17 released
  products/linuxkernel.md
Labels: release-updates

#956 [EmberJs] Update latest release info
  products/emberjs.md
Labels: release-updates

#960 [Python] Update 3.9.11 to 3.9.12
  products/python.md
Labels: release-updates

#961 [Python] Update 3.10.3 to 3.10.4
  products/python.md
Labels: release-updates

#957 [automation] Add upstream information for automation
  CONTRIBUTING.md
  products/alpinelinux.md
  products/amazon-linux.md
  products/angular.md
  products/ansible.md
  products/api-platform.md
  products/blender.md
  products/bootstrap.md
  products/composer.md
  products/consul.md
  products/couchbase-server.md
  products/django.md
  products/docker-engine.md
  products/dotnet.md
  products/drupal.md
  products/elasticsearch.md
  products/electron.md
  products/elixir.md
  products/emberjs.md
  products/fedora.md
  products/ffmpeg.md
  products/gitlab.md
  products/go.md
  products/godot.md
  products/haproxy.md
  products/jquery.md
  products/kotlin.md
  products/kubernetes.md
  products/laravel.md
  products/linuxkernel.md
  products/magento.md
  products/mariadb.md
  products/mediawiki.md
  products/mongodb.md
  products/mysql.md
  products/nginx.md
  products/nodejs.md
  products/nomad.md
  products/openzfs.md
  products/perl.md
  products/php.md
  products/postgresql.md
  products/powershell.md
  products/python.md
  products/qt.md
  products/rabbitmq.md
  products/redis.md
  products/roundcube.md
  products/ruby-on-rails.md
  products/ruby.md
  products/spring-framework.md
  products/symfony.md
  products/tarantool.md
  products/vue.md
  products/wagtail.md
Labels: enhancement

#836 Add ReadyNAS devices
  products/readynas.md
Labels: new-product

#963 [Firefox] Update 98.0.2 and 91.7.1 ESR
  products/firefox.md
Labels: release-updates

#964 [MySQL] Update 8.0.28 and 5.7.37
  products/mysql.md
Labels: release-updates

#965 [Perl] Update 5.34.1
  products/perl.md
Labels: release-updates

#966 [Kotlin] Update 1.6.10 and 1.5.32
  products/kotlin.md
Labels: release-updates

#969 [Qt] Update 6.2.4 and 5.12.12
  products/qt.md
Labels: release-updates

#970 [Elasticsearch] Add 8.1, update 8.0.1 and 7.17.1
  products/elasticsearch.md
Labels: release-updates

#972 [alpinelinux] 3.15.2 released
  products/alpinelinux.md
Labels: release-updates

#971 [rails] Update 4.2.11.3
  products/ruby-on-rails.md
Labels: release-updates

#959 [openzfs] Update 2.1.4
  products/openzfs.md
Labels: release-updates

#958 [gitlab] Update 14.9.1, 14.7.6
  products/gitlab.md
Labels: release-updates

#841 Updates to Couchbase Server
  products/couchbase-server.md
Labels: release-updates

#973 [auto] Switch to GitHub URLs
  products/alpinelinux.md
  products/ffmpeg.md
  products/haproxy.md
  products/linuxkernel.md
  products/ruby.md
Labels: bug

#979 Add regex and templates for products
  products/go.md
  products/postgresql.md
  products/rabbitmq.md
Labels: enhancement

#981 Switch to rebase merges for dependabot
  .github/workflows/auto-merge-release-updates.yml
Labels: bug
