Repository endoflife-date/endoflife.date, pull requests merged in 2023-10, with the labels that each got.

#3649 [citrix-apps-desktops] Add latestReleaseDate for all cycles
  products/citrix-apps-desktops.md
Labels: release-updates

#3638 [magento] Update 2.0 and 2.1 links
  products/magento.md
Labels: product-fixes

#3639 [apache-hadoop] Remove 2.0 and 2.1
  products/apache-hadoop.md
Labels: product-fixes

#3640 [openjdk-builds-from-oracle] Fix 9 link
  products/openjdk-builds-from-oracle.md
Labels: product-fixes

#3641 [quarkus] Fix description regarding the LTS policy
  products/quarkus.md
Labels: product-fixes

#3646 [tails] Update latest 5 to 5.17
  products/tails.md
Labels: release-updates

#3644 [amazon-corretto] Add 21
  products/amazon-corretto.md
Labels: release-updates

#3651 [python] Add 3.12
  products/python.md
Labels: release-updates

#3650 [cos] Add 109
  products/cos.md
Labels: release-updates

#3661 [apache-kafka] Add 3.6, update 3.5 eol
  products/apache-kafka.md
Labels: release-updates

#3522 [new-product] Veeam Backup & Replication
  products/veeam-backup-and-replication.md
Labels: new-product

#3663 [pixel] Pixel 8 & Pixel 8 Pro
  products/pixel.md
Labels: release-updates

#3515 [new-product] add Kong Gateway
  products/kong-gateway.md
Labels: new-product

#3666 [amazon-corretto] Fix 21
  products/amazon-corretto.md
Labels: product-fixes

#3619 [gradle] Add 5-1
  products/gradle.md
Labels: release-updates

#3676 [terraform] Add 1.6, update 1.4 eol
  products/terraform.md
Labels: release-updates

#3685 CFEngine 3.18.6 and 3.21.3 released
  products/cfengine.md
Labels: release-updates

#3686 [nutanix-aos] Add 6.7, update latest releases
  products/nutanix-aos.md
Labels: release-updates

#3687 [nutanix-files] Add 4.4-4.3, update 4.2
  products/nutanix-files.md
Labels: release-updates

#3688 [nutanix-prism] Add 2023.3 + 2023.1, update 2022.9 + 2022.6
  products/nutanix-prism.md
Labels: release-updates

#3690 Allow overriding the data directory in latest.py
  .gitignore
  _auto/latest.py
Labels: enhancement

#3691 Fix broken link
  products/ffmpeg.md
Labels: product-fixes

#3694 Fix Broken Link
  products/confluence.md
Labels: product-fixes

#3740 [craft-cms] Normalize page
  products/craft-cms.md
Labels: chore

#3739 [freebsd] Normalize page
  products/freebsd.md
Labels: chore

#3737 [eurolinux] Normalize page
  products/eurolinux.md
Labels: chore

#3736 [elasticsearch] Normalize page
  products/elasticsearch.md
Labels: chore

#3734 [docker] Normalize page
  products/docker-engine.md
Labels: chore

#3733 [django] Normalize page
  products/django.md
Labels: chore

#3732 [dependencytrack] Normalize page
  products/dependencytrack.md
Labels: chore

#3730 [cakephp] Normalize page
  products/cakephp.md
Labels: chore

#3728 [beats] Normalize page
  products/beats.md
Labels: chore

#3727 [api-platform] Normalize page
  products/api-platform.md
Labels: chore

#3721 [antixlinux] Normalize page
  products/antixlinux.md
Labels: chore

#3720 [angularjs] Normalize page
  products/angularjs.md
Labels: chore

#3719 [android] Normalize page
  products/android.md
Labels: chore

#3717 [xcp-ng] Drop unnecessary lts=false
  products/xcp-ng.md
Labels: chore

#3716 [wagtail] Drop unnecessary lts=false
  products/wagtail.md
Labels: chore

#3715 [vuetify] Drop unnecessary lts=false
  products/vuetify.md
Labels: chore

#3714 [vue] Drop unnecessary lts=false
  products/vue.md
Labels: chore

#3713 [typo3] Drop unnecessary lts=false
  products/typo3.md
Labels: chore

#3712 [sonarqube] Drop unnecessary lts=false
  products/sonarqube.md
Labels: chore

#3711 [powershell] Drop unnecessary lts=false
  products/powershell.md
Labels: chore

#3710 [oracle-database] Drop unnecessary lts=false
  products/oracle-database.md
Labels: chore

#3709 [neo4j] Drop unnecessary lts=false
  products/neo4j.md
Labels: chore

#3708 [linuxmint] Drop unnecessary lts=false
  products/linuxmint.md
Labels: chore

#3707 [moodle] Drop unnecessary lts=false
  products/moodle.md
Labels: chore

#3706 [kdeplasma] Drop unnecessary lts=false
  products/kdeplasma.md
Labels: chore

#3705 [graalvm] Drop unnecessary lts=false
  products/graalvm.md
Labels: chore

#3704 [dotnet] Drop unnecessary lts=false
  products/dotnet.md
Labels: chore

#3703 [cfengine] Drop unnecessary lts=false
  products/cfengine.md
Labels: chore

#3702 [azul-zulu] Drop unnecessary lts=false
  products/azul-zulu.md
Labels: chore

#3738 [fortios] Normalize page
  products/fortios.md
Labels: chore

#3735 [drush] Normalize page
  products/drush.md
Labels: chore

#3731 [cos] Normalize page
  products/cos.md
Labels: chore

#3729 [bootstrap] Normalize page
  products/bootstrap.md
Labels: chore

#3725 [apache-groovy] Normalize page
  products/apache-groovy.md
Labels: chore

#3724 [apache-cassandra] Normalize page
  products/apache-cassandra.md
Labels: chore

#3723 [apache-airflow] Normalize page
  products/apache-airflow.md
Labels: chore

#3718 [amazon-linux] Normalize page
  products/amazon-linux.md
Labels: chore

#3680 [electron] Update EOL dates
  products/electron.md
Labels: release-updates

#3745 Exclude IE link from mandatory link checks
  _plugins/product-data-validator.rb
Labels: chore

#3744 [gradle] Fix 1 latest version
  products/gradle.md
Labels: product-fixes

#3753 Update os/EuroLinux
  products/eurolinux.md
Labels: release-updates

#3760 [moodle] Add 4.3
  products/moodle.md
Labels: release-updates

#3758 [confluence] Add 8.6
  products/confluence.md
Labels: release-updates

#3748 [mongodb] Update description to mention extended support
  products/mongodb.md
Labels: product-updates

#3747 [laravel] Clarify the difference between the framework and the application
  products/laravel.md
Labels: product-updates

#3743 [telegraph] Fix links for 1.0 to 1.13 releases
  products/telegraf.md
Labels: product-fixes

#3742 Disable the check-links workflow on forks
  .github/workflows/check-links.yml
Labels: enhancement

#3722 [antixlinux] Add 23
  products/antixlinux.md
Labels: release-updates

#3700 Add links on Nutanix pages for easier maintenance
  products/nutanix-aos.md
  products/nutanix-files.md
  products/nutanix-prism.md
Labels: documentation

#3693 [jira] Set up auto configuration and update releases
  products/jira.md
Labels: release-updates, product-updates

#3692 [confluence] Set auto configuration, add 8.6 and update release dates
  products/confluence.md
Labels: release-updates, product-updates

#3697 [azure-devops] Update latest releases
  products/azure-devops.md
Labels: release-updates

#3765 [jira] Fix duplicate keys in 7.13
  products/jira.md
Labels: bug, product-fixes

#3774 [amazon-rds-mysql] Update 8.0 and 5.7 EOL date
  products/amazon-rds-mysql.md
Labels: release-updates

#3772 [apache-camel] Add 4.1
  products/apache-camel.md
Labels: release-updates

#3773 [qt] Add 6.6
  products/qt.md
Labels: release-updates

#3769 [plesk] Add 18.0.56
  products/plesk.md
Labels: release-updates

#3768 [oraclelinux] Update 7 EOL and 6 extended support dates
  products/oraclelinux.md
Labels: release-updates

#3699 [mule-runtime] Add 4.5
  products/muleruntime.md
Labels: release-updates

#3746 [visual-cobol] Add 9.0 and remaining 2.x, clarify description
  products/visual-cobol.md
Labels: release-updates, product-updates

#3343 [new-product] KEDA
  products/keda.md
Labels: new-product

#3779 [iphone] Add 15 and mark some models as discontinued
  products/iphone.md
Labels: release-updates

#3695 [kindle] Major releases update
  products/kindle.md
Labels: release-updates, breaking-change

#3643 [angularjs] Update extended support description
  products/angularjs.md
Labels: product-updates

#3785 [mssqlserver] Update 2022 CU9, 2019 CU23, 2017 CU31 GDR, 2016 SP3 GDR, 2014 SP3 CU4 GDR
  products/mssqlserver.md
Labels: release-updates

#3784 [msexchange] Update 2019 CU13 SU3, 2016 CU23 SU10
  products/msexchange.md
Labels: release-updates

#3787 [mssharepoint] Update subscription, 2019
  products/mssharepoint.md
Labels: release-updates

#3786 [visualstudio] Update 17.7.5, 17.6.8, 17.4.12, 17.2.20, 16.11.31
  products/visualstudio.md
Labels: release-updates

#3778 [openwrt] Add 23.05
  products/openwrt.md
Labels: release-updates

#3771 [Centos] Updated "releasePolicyLink"
  products/centos.md
Labels: product-updates

#3791 [iphone] Split entries containing mutiple models
  products/iphone.md
Labels: release-updates, product-fixes, api, breaking-change

#3792 [new-product] Apple Watch
  products/apple-watch.md
Labels: new-product

#3798 [new-product] Add Rocket.Chat
  products/rocket-chat.md
Labels: new-product

#3799 [new-product] Apache Hop
  products/apache-hop.md
Labels: new-product

#3793 [android] Mention Android Go
  products/android.md
Labels: product-updates

#3802 [centos] Fix changelog links
  products/centos.md
Labels: release-updates

#3800 [vmware-horizon] Fix 8.2006 link
  products/vmware-horizon.md
Labels: release-updates

#3817 [weechat] Add 4.1, update 4.0 eol
  products/weechat.md
Labels: release-updates

#3814 [mattermost] Add 9.1
  products/mattermost.md
Labels: release-updates

#3812 [openzfs] Add 2.2, update 2.1 eol, apply style guide
  products/openzfs.md
Labels: release-updates

#3809 [iphone] Add 5-1
  products/iphone.md
Labels: release-updates

#3801 [centos-stream] Fix some links
  products/centos-stream.md
Labels: release-updates, product-updates

#3788 [api-platform] Add 3.2
  products/api-platform.md
Labels: release-updates

#3813 [silverstripe] Add 5.1, apply style guide
  products/silverstripe.md
Labels: release-updates

#3822 [dependencytrack] Add 4.9
  products/dependencytrack.md
Labels: release-updates

#3816 [joomla] Add 5, update eol/support for 4-3
  products/joomla.md
Labels: release-updates

#3828 [nodejs] Add 21
  products/nodejs.md
Labels: release-updates

#3677 [mongodb] Add 7.1 Rapid Release
  products/mongodb.md
Labels: release-updates

#3805 [new-product] Add dbt Core
  products/dbt-core.md
Labels: new-product

#3842 [samsungmobile] Remove duplicated entry ( galaxy fold 5g )
  products/samsungmobile.md
Labels: product-fixes

#3846 [openzfs] Add supported kernels table with details
  products/openzfs.md
Labels: enhancement

#3818 [new-product] Erlang
  products/erlang.md
Labels: new-product

#3701 [looker] Set auto configuration, add 22.20 to 23.18
  products/looker.md
Labels: release-updates, product-updates

#3849 [azul-zulu] Highlight update types and distribution packages details
  products/azul-zulu.md
Labels: product-updates

#3855 [pan-os] Fix link for 9.1
  products/pan-os.md
Labels: release-updates

#3856 [azul-zulu] Prevent link to support.azul.com from raising errors
  _plugins/product-data-validator.rb
Labels: chore

#3851 [samsungmobile] Update release and EOL dates for Galaxy S20 family
  products/samsungmobile.md
Labels: release-updates

#3848 [envoy] Add 1.28
  products/envoy.md
Labels: release-updates

#3861 [yarn] Add 4
  products/yarn.md
Labels: release-updates

#3794 [new-product] Add Oracle Solaris
  products/oracle-solaris.md
Labels: new-product

#3853 [gitlab] Add 16.5
  products/gitlab.md
Labels: release-updates

#3866 [neo4j] Add 5.13
  products/neo4j.md
Labels: release-updates

#3874 [artifactory] Add 7.71
  products/artifactory.md
Labels: release-updates

#3873 [grafana] Add 10.2, update 10.1 supprt, update 10.0 eol
  products/grafana.md
Labels: release-updates

#3868 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: chore

#3872 [firefox] Add 119, update 115 and 102 eol, notes for ESR/LTS
  products/firefox.md
Labels: release-updates

#3847 [jira] Add 8.19-8.14, 8.12-8.6, 8.4-8.0, 7.12-1.0
  products/jira.md
Labels: release-updates

#3829 [windows] Update api friendly releaseCycles and use releaseLabel, Remove Windows Prefix
  products/windows.md
Labels: api, breaking-change

#3876 [redhat-build-of-openjdk] Use a changelogTemplate
  products/redhat-build-of-openjdk.md
Labels: release-updates, product-updates

#3875 [quarkus] Add 3.5
  products/quarkus.md
Labels: release-updates

#3877 [eks] Normalize page
  products/eks.md
Labels: chore

#3878 [emberjs] Normalize page
  products/emberjs.md
Labels: chore

#3879 [fairphone] Normalize page
  products/fairphone.md
Labels: chore

#3880 [gitlab] Normalize page
  products/gitlab.md
Labels: chore

#3881 [gke] Normalize page
  products/gke.md
Labels: chore

#3882 [grails] Normalize page
  products/grails.md
Labels: chore

#3883 [internetexplorer] Normalize page
  products/internetexplorer.md
Labels: chore

#3884 [ios] Normalize page
  products/ios.md
Labels: chore

#3885 [ipados] Normalize page
  products/ipados.md
Labels: chore

#3886 [jekyll] Normalize page
  products/jekyll.md
Labels: chore

#3887 [jhipster] Normalize page
  products/jhipster.md
Labels: chore

#3888 [joomla] Normalize page
  products/joomla.md
Labels: chore

#3889 [jquery] Normalize page
  products/jquery.md
Labels: chore

#3890 [jreleaser] Normalize page
  products/jreleaser.md
Labels: chore

#3891 [kdeplasma] Normalize page
  products/kdeplasma.md
Labels: chore

#3892 [kirby] Normalize page
  products/kirby.md
Labels: chore

#3893 [lineageos] Normalize page
  products/lineageos.md
Labels: chore
