Repository endoflife-date/endoflife.date, pull requests merged in 2023-09, with the labels that each got.

#3508 Update postfix 3.8.2, 3.7.7, 3.6.11, 3.5.21
  products/postfix.md
Labels: release-updates

#3514 [composer] Add 2.6
  products/composer.md
Labels: release-updates

#3509 [apache-kafka] Fix 3.2 and 3.3 latest releases
  _plugins/product-data-validator.rb
  products/apache-kafka.md
Labels: release-updates

#3519 [istio] Add 1.19, update eol details
  products/istio.md
Labels: release-updates

#3387 Add jsonschema
  CONTRIBUTING.md
  _config.yml
  product-schema.json
Labels: enhancement

#3541 [telegraf] Add 1.28, Update 1.26 eol
  products/telegraf.md
Labels: release-updates

#3540 [artifactory] Add 7.68
  products/artifactory.md
Labels: release-updates

#3545 [mssharepoint] Update 16.0.16731.20180, 16.0.10402.20016, 16.0.5413.1001
  products/mssharepoint.md
Labels: release-updates

#3544 [visualstudio] Update 17.7.4, 17.6.7, 17.4.11, 17.2.19, 16.11.30, 15.9.57
  products/visualstudio.md
Labels: release-updates

#3546 [postgresql] Add 16
  products/postgresql.md
Labels: release-updates

#3533 [CakePhp] Add 5.x ( aka Chiffon )
  products/cakephp.md
Labels: release-updates

#3559 [mssqlserver] 2022 CU8
  products/mssqlserver.md
Labels: release-updates

#3563 [mattermost] Add 9.0
  products/mattermost.md
Labels: release-updates

#3564 [numpy] Add 1.26
  products/numpy.md
Labels: release-updates

#3565 [neo4j] Add 5.12
  products/neo4j.md
Labels: release-updates

#3569 [java] New LTS (21) Released
  products/java.md
Labels: release-updates

#3575 [graalvm] Add JDK 21
  products/graalvm.md
Labels: release-updates

#3574 [eclipse-temurin] Add auto configuration for 21
  products/eclipse-temurin.md
Labels: release-updates

#3573 [azul-zulu] Add 21
  products/azul-zulu.md
Labels: release-updates

#3572 [amazon-corretto] Add auto configuration for 21
  products/amazon-corretto.md
Labels: release-updates

#3579 [jira] Update 9.11.1
  products/jira.md
Labels: release-updates

#3576 [microsoft-build-of-openjdk] Add 21
  products/microsoft-build-of-openjdk.md
Labels: release-updates

#3597 [mastodon] Add 4.2
  products/mastodon.md
Labels: release-updates

#3581 [ios] Add 17
  products/ios.md
Labels: release-updates

#3583 [ipados] Add 17
  products/ipados.md
Labels: release-updates

#3571 [sapmachine] Add 21
  products/sapmachine.md
Labels: release-updates

#3600 [jira] Update 9.10.2
  products/jira.md
Labels: release-updates

#3606 Fix CSP for /doc/api
  _headers
Labels: bug

#3609 [typo3] Switch to a custom auto configuration
  products/typo3.md
Labels: auto

#3608 [unity] Set up auto configuration
  products/unity.md
Labels: auto

#3607 [vmware-esxi] Update latest release data
  products/vmware-esxi.md
Labels: release-updates

#3335 [new-product] Apache Hadoop
  products/apache-hadoop.md
Labels: new-product

#3336 [new-product] Add Apache Spark
  products/apache-spark.md
Labels: new-product

#3332 [new-product] Oracle JDK and OpenJDK builds from Oracle
  products/openjdk-builds-from-oracle.md
  products/oracle-jdk.md
Labels: new-product

#3610 Exclude some URLs from being validated
  _plugins/product-data-validator.rb
Labels: bug

#3493 [new-product] AWS Glue
  products/amazon-glue.md
Labels: new-product

#3578 [new-product] Quasar
  products/quasar.md
Labels: new-product

#3604 [emberjs] Add 5.3
  products/emberjs.md
Labels: release-updates

#3603 [nix] Add 2.18
  products/nix.md
Labels: release-updates

#3613 [apache-spark] Add 3.5
  products/apache-spark.md
Labels: release-updates

#3585 [watchos] Add 10
  products/watchos.md
Labels: release-updates

#3596 [bellsoft-liberica] Add 21
  products/bellsoft-liberica.md
Labels: release-updates

#3616 [protractor] Normalization and minor updates
  products/protractor.md
Labels: product-updates

#3623 [firefox] Add 118
  products/firefox.md
Labels: release-updates

#3625 [oracle-jdk] Update 11 extendedSupport
  products/oracle-jdk.md
Labels: release-updates

#3628 [hashicorp-vault] Add 1.15
  products/hashicorp-vault.md
Labels: release-updates
