Repository endoflife-date/endoflife.date, pull requests merged in 2023-08, with the labels that each got.

#3345 [rabbitmq] Add dates for 3.12
  products/rabbitmq.md
Labels: release-updates

#3341 [new-product] Akeneo PIM
  products/akeneo-pim.md
Labels: new-product

#3349 Update jekyll dependencies
  Gemfile.lock
Labels: dependencies, ruby

#3352 [sles] 15.5 is not yet EOL
  products/sles.md
Labels: product-fixes

#3360 [splunk] Add 9.1
  products/splunk.md
Labels: release-updates

#3348 [mxlinux] Add 23
  products/mxlinux.md
Labels: release-updates

#3355 [firefox] Add 116
  products/firefox.md
Labels: release-updates

#3356 [wagtail] Add 5.1
  products/wagtail.md
Labels: release-updates

#3367 [zookeeper] Add 3.9
  products/zookeeper.md
Labels: release-updates

#3366 [eks] Precise EOL date for 1.24
  products/eks.md
Labels: product-fixes

#3365 [craft] EOL is April, not May
  products/craft-cms.md
Labels: product-fixes

#3334 [new-product] Add Graylog
  products/graylog.md
Labels: new-product

#3337 [new-product] Add Argo CD
  products/argocd.md
Labels: new-product

#3373 [vmware-horizon] 2212.1 released
  products/vmware-horizon.md
Labels: release-updates

#3372 [opensearch] 1.x is not yet EOL
  products/opensearch.md
Labels: product-fixes

#3374 [visualstudio] Update 16.11.28
  products/visualstudio.md
Labels: release-updates

#3376 [Pixel] Add Fold
  products/pixel.md
Labels: release-updates

#3342 [qt] Better commercial support documentation with an extendedSupport column
  products/qt.md
Labels: bug, release-updates

#3379 [visualstudio] Add 17.7, update 17.6.6, 17.2.18, 17.4.10, 16.11.29, 15.9.56
  products/visualstudio.md
Labels: release-updates

#3380 [msexchange] Update Aug23SU for 2019, 2016
  products/msexchange.md
Labels: release-updates

#3381 [mssharepoint] Update latest for Subscription Edition, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#3384 [argocd] Add 2.8
  products/argocd.md
Labels: release-updates

#3385 [wordpress] Add 6.3
  products/wordpress.md
Labels: release-updates

#3389 [python] Mark support: false for old releases
  products/python.md
Labels: bug

#3391 [neptune] Add some alternate URLs
  products/amazon-neptune.md
Labels: product-fixes

#3392 [rocky] Custom automation
  products/rockylinux.md
Labels: product-fixes

#3369 [graalvm] Set up automation
  products/graalvm.md
Labels: enhancement

#3395 [amazonlinux] Switch to the new docker_hub method
  products/amazon-linux.md
Labels: enhancement

#3358 [new-product] Salt
  products/salt.md
Labels: new-product

#3406 [firefox] Mark 115 as ESR
  products/firefox.md
Labels: product-fixes

#3410 [visualstudio] Update 17.7.1
  products/visualstudio.md
Labels: release-updates

#3402 [mssqlserver] Update 2022 CU7, 2019 CU22
  products/mssqlserver.md
Labels: release-updates

#3414 [devuan] Add 5
  products/devuan.md
Labels: release-updates

#3415 [electron] Add 26
  products/electron.md
Labels: release-updates

#3416 [neo4j] Add 5.11
  products/neo4j.md
Labels: release-updates

#3417 [apache-camel] Add 4.0
  products/apache-camel.md
Labels: release-updates

#3418 [contao] Add 5.2
  products/contao.md
Labels: release-updates

#3419 [mongodb] Add 7.0
  products/mongodb.md
Labels: release-updates

#3423 [msexchange] Update 2019 CU13 SU2V2, 2016 CU23 SU9V2, 2013 CU23 SU21
  products/msexchange.md
Labels: release-updates

#3424 [opensearch] Updates to release schedule
  products/opensearch.md
Labels: product-fixes

#2859 Migrate validation to Jekyll hooks
  .github/dependabot.yml
  .github/workflows/auto-merge-release-updates.yml
  .github/workflows/check-links.yml
  .github/workflows/validate.yaml
  Gemfile
  Gemfile.lock
  _auto/deploy.sh
  _auto/validate.py
  _config.yml
  _plugins/product-data-enricher.rb
  _plugins/product-data-validator.rb
  netlify.toml
  products/dotnet.md
  products/graylog.md
  products/nodejs.md
  products/pop_os.md
Labels: enhancement, breaking-change

#3329 Add tag-related pages
  _config.yml
  _includes/product-icon.html
  _layouts/product-list.html
  _layouts/product-tags.html
  _layouts/product.html
  _plugins/generate-tag-pages.rb
  _sass/custom/custom.scss
  products/etcd.md
  products/pan-gp.md
  products/symfony.md
Labels: bug, enhancement

#3429 Allow the new check-links workflow to be triggered manually
  .github/workflows/check-links.yml
Labels: enhancement

#3438 [salt] Fix changelogTemplate
  products/salt.md
Labels: product-fixes

#3437 [numpy] Update changelogTemplate
  products/numpy.md
Labels: product-fixes

#3404 [LibreOffice] Update to 7.6
  products/libreoffice.md
Labels: release-updates

#3446 [emberjs] Add 5.2
  products/emberjs.md
Labels: release-updates

#3450 [redis] Update 6.0 eol, 5.0 eol as date
  products/redis.md
Labels: release-updates

#3456 [clamav] Update 1.1 eol as date
  products/clamav.md
Labels: release-updates

#3439 [scala] Fix latest for 3.3
  products/scala.md
Labels: product-fixes

#3434 [fairphone] Fix links
  products/fairphone.md
Labels: product-fixes

#3458 [visualstudio] Update 17.7.2
  products/visualstudio.md
Labels: release-updates

#3433 [bellsoft-liberica] Update changelogTemplate
  products/bellsoft-liberica.md
Labels: product-fixes

#3430 [yarn] Fix link for 1.x
  products/yarn.md
Labels: product-fixes

#3465 [bellsoft-liberica] Remove duplicate changelogTemplate
  products/bellsoft-liberica.md
Labels: bug, product-fixes

#3440 Exclude links from causing validation error
  _plugins/product-data-validator.rb
Labels: bug

#3468 [angular] Update icons
  products/angularjs.md
Labels: product-updates

#3467 [quarkus] Add 3.3
  products/quarkus.md
Labels: release-updates, product-updates

#3473 [mattermost] Add 8.1 ESR
  products/mattermost.md
Labels: release-updates

#3432 [activemq] Fix links
  products/apache-activemq.md
Labels: product-fixes

#3400 [dotnet] adding rpm PURLs
  products/dotnet.md
Labels: enhancement

#3479 Update azure-kubernetes-service.md
  products/azure-kubernetes-service.md
Labels: release-updates

#3478 [opensuse] update 15.1 and 15.2 EOL dates
  products/opensuse.md
Labels: release-updates

#3420 [new-product] Flux
  products/flux.md
Labels: new-product

#3475 [new-product] Next.js framework
  products/nextjs.md
Labels: new-product

#3472 [grafana] Add 10.1
  products/grafana.md
Labels: release-updates

#3483 [elasticsearch][logstash][kibana][beats] Fix 7.x EOL dates
  products/beats.md
  products/elasticsearch.md
  products/kibana.md
  products/logstash.md
Labels: product-fixes

#3481 Ignore web.archive.org error during links check
  _plugins/product-data-validator.rb
Labels: bug

#3495 [linuxkernel] Add 6.5, set EOL for 6.3 and update releaseImage
  products/linuxkernel.md
Labels: release-updates

#3497 [mageia] Add 9 and set EOL for 8
  products/mageia.md
Labels: release-updates

#3503 [plesk] Add 18.0.55
  products/plesk.md
Labels: release-updates

#3502 [firefox] Add 117
  products/firefox.md
Labels: release-updates

#3501 [visualstudio] Update 17.7.3
  products/visualstudio.md
Labels: release-updates

#3500 [apache-kafka] Update extendedSupport for 3.5
  products/apache-kafka.md
Labels: release-updates
