Repository endoflife-date/endoflife.date, pull requests merged in 2023-06, with the labels that each got.

#3023 [nixos] Add 23.05 (Stoat)
  products/nixos.md
Labels: release-updates

#3058 [electron] Adds v25
  products/electron.md
Labels: release-updates

#3060 [haproxy] Adds 2.8.0
  products/haproxy.md
Labels: release-updates

#3061 [docker] Update EOL
  products/docker-engine.md
Labels: product-fixes

#3062 [Ansible] Add release cycle 8
  products/ansible.md
Labels: release-updates

#3033 [quarkus] Add 3.1
  products/quarkus.md
Labels: release-updates

#3064 [eks] Pin EKS versions to published ones
  products/eks.md
Labels: product-fixes

#3074 [dep] Upgrade Python deps
  .github/dependabot.yml
  .github/workflows/auto-merge-release-updates.yml
  .github/workflows/validate.yaml
  requirements.txt
Labels: dependencies

#3072 [nix] Add 2.16, Update 2.15 eol
  products/nix.md
Labels: release-updates

#3024 [scala] Add 3.3
  products/scala.md
Labels: release-updates

#3078 [mariadb] Adds v11.0
  products/mariadb.md
Labels: release-updates

#2868 [openssl] Document Premium Enterprise Level Support
  products/openssl.md
Labels: release-updates

#3090 [firefox] Adds 114
  products/firefox.md
Labels: release-updates

#3097 [postfix] Improve regex
  products/postfix.md
Labels: product-fixes

#3088 [plesk] Adds 18.0.53
  products/plesk.md
Labels: release-updates

#3054 [New Product] squid
  products/squid.md
Labels: new-product

#3092 [istio] Adds v1.18
  products/istio.md
Labels: release-updates

#3089 [drush] Adds v12
  products/drush.md
Labels: release-updates

#3100 [plesk] Lower EOL warn threshold
  products/plesk.md
Labels: product-fixes

#3087 [craft] Adds Craft CMS
  products/craft-cms.md
Labels: new-product

#2901 [New Product] phpBB
  products/phpbb.md
Labels: new-product

#3102 Add Coldfusion 2023 release details
  products/coldfusion.md
Labels: release-updates

#3096 [postfix] Fix links
  products/postfix.md
Labels: product-fixes

#3107 [cfengine] Set up automation
  products/cfengine.md
Labels: enhancement

#3110 [yocto] Fix EOL for 3.3
  products/yocto.md
Labels: product-fixes

#3114 [terraform] Add 1.5
  products/terraform.md
Labels: release-updates

#3041 [couchbase-server] Add 7.2 and fix EOL dates
  products/couchbase-server.md
Labels: release-updates

#3077 [auto] Switch to cgit for linuxkernel
  products/linuxkernel.md
Labels: enhancement

#3115 [visualstudio] Add 17.6, Update 17.5.4, 17.4.7, 17.2.15, 17.0.21, 16.11.26, 15.9.54
  products/visualstudio.md
Labels: release-updates

#3126 [rockylinux] Fix dates
  products/rockylinux.md
Labels: product-fixes

#3118 [telegraf] Add 1.27, update 1.25 eol, add iconSlug
  products/telegraf.md
Labels: release-updates

#3138 [gke] Add 1.27
  products/gke.md
Labels: release-updates

#3137 [neo4j] Add 5.9
  products/neo4j.md
Labels: release-updates

#3119 [apache-kafka] Add 3.5, update 3.4 eol
  products/apache-kafka.md
Labels: release-updates

#3129 [scala] update jdk compatibility
  products/scala.md
Labels: release-updates

#3136 [msexchange] Update 2019 CU13 Jun23SU, 2016 CU23 Jun23SU
  products/msexchange.md
Labels: release-updates

#3135 [mssharepoint] Update subscription, 2019, 2016, 2013
  products/mssharepoint.md
Labels: release-updates

#3133 [visualstudio] Update 17.6.3, 17.4.8, 17.2.16, 17.0.22, 16.11.27, 15.9.55
  products/visualstudio.md
Labels: release-updates

#3127 [jenkins] Add 2.401 LTS
  products/jenkins.md
Labels: release-updates

#3142 [cassandra] Improve readability of versioning description
  products/apache-cassandra.md
Labels: product-fixes

#3153 [oraclelinux] Update 8.8
  products/oraclelinux.md
Labels: release-updates

#3158 [hashicorp-vault] Add 1.14
  products/hashicorp-vault.md
Labels: release-updates

#3159 [elixir] Add 1.15, Apply Style Guide
  products/elixir.md
Labels: release-updates

#3160 [gitlab] Add 16.1
  products/gitlab.md
Labels: release-updates

#3040 [emberjs] Adds 5.0
  products/emberjs.md
Labels: release-updates

#3149 [vmware-vcenter] 8.0c -> 8.0 U1a
  products/vmware-vcenter.md
Labels: release-updates

#3173 [visualstudio] Update 17.6.4
  products/visualstudio.md
Labels: release-updates

#2708 Enrich cycles by splitting `lts`/`support`/`discontinued`/`eol`/`extendedSupport`
  _layouts/product.html
  _plugins/product-data-enricher.rb
Labels: enhancement

#3140 [redhat-satellite] Set up automation
  products/redhat-satellite.md
Labels: enhancement

#3178 [proxmox-ve] Add 8
  products/proxmox-ve.md
Labels: release-updates

#3177 [grafana] Add 10.0
  products/grafana.md
Labels: release-updates

#3176 [drupal] Add 10.1
  products/drupal.md
Labels: release-updates

#3164 [Pixel] Group Pixel 6, 6 Pro and 7, 7 Pro
  products/pixel.md
Labels: release-updates

#3189 [samsungmobile] Add a note about release dates varying depending on the country or region
  products/samsungmobile.md
Labels: enhancement

#3187 [google-pixel] Make use of releaseLabel
  products/pixel.md
Labels: enhancement, breaking-change

#3186 [pan-gp] Fix 5.3, 5.0 and 4.1 links
  products/pan-gp.md
Labels: bug

#3152 [New Product] Kirby CMS
  products/kirby.md
Labels: new-product

#3182 [istio] Fix 1.18 link
  products/istio.md
Labels: bug

#3183 [coldfusion] Suppress 2023 link
  products/coldfusion.md
Labels: bug

#3193 [kirby] Fix links and label
  products/kirby.md
Labels: bug

#3184 [apache-kafka] Update 3.0 to 3.3 links
  products/apache-kafka.md
Labels: bug

#3188 [quarkus] Switch to github_release auto method
  products/quarkus.md
Labels: enhancement

#3180 [silverstripe] Update changelogTemplate
  products/silverstripe.md
Labels: bug

#3179 [bellsoft-liberica] Fix 18 link
  products/bellsoft-liberica.md
Labels: bug

#3191 [New Product] IBM Semeru Runtime
  products/ibm-semeru.md
Labels: new-product

#3196 [New Product] SapMachine
  products/sapmachine.md
Labels: new-product

#3190 [couchbase-server] Switch to a custom auto configuration
  products/couchbase-server.md
Labels: bug, release-updates

#3203 [consul] 1.16
  products/consul.md
Labels: release-updates

#3204 [blender] 3.6 release
  products/blender.md
Labels: release-updates, product-fixes
