Repository endoflife-date/endoflife.date, pull requests merged in 2023-07, with the labels that each got.

#3211 [umbraco] Add 12
  products/umbraco.md
Labels: release-updates

#3141 [New Product] Amazon-Neptune
  products/amazon-neptune.md
Labels: new-product

#3214 [amazon-linux] Update EOL of AMI
  products/amazon-linux.md
Labels: release-updates

#3218 [mediawiki] 1.40
  products/mediawiki.md
Labels: release-updates

#3219 [neptune] Use AWS icon
  products/amazon-neptune.md
Labels: product-fixes

#3216 [nginx] Add 1.19
  products/nginx.md
Labels: release-updates, product-fixes

#3213 [rhel] Update ELS dates
  products/redhat.md
Labels: release-updates

#3166 [filemaker] Add 2023
  products/filemaker.md
Labels: release-updates

#3220 [amazon-neptune] Add auto configuration
  _auto/latest.py
  products/amazon-neptune.md
Labels: release-updates

#3128 deps: bump ruby to 3.1.4
  .ruby-version
Labels: dependencies, ruby

#3237 [firefox] Adds 115
  products/firefox.md
Labels: release-updates

#3234 [camel] Adds 3.21
  products/apache-camel.md
Labels: release-updates

#3240 [quarkus] Fix regex
  products/quarkus.md
Labels: product-fixes

#3238 [xdr-agent] Adds 8.1
  products/pan-cortex-xdr.md
Labels: release-updates

#3236 [perl] Adds 5.38 release
  products/perl.md
Labels: release-updates

#3235 [godot] Adds 4.1 and date fixes
  products/godot.md
Labels: release-updates

#3246 [squid] Adds 6.1
  products/squid.md
Labels: release-updates

#3247 [squid] v6 is released
  products/squid.md
Labels: product-fixes

#3199 [New Product] Artifactory
  products/artifactory.md
Labels: new-product

#3223 [New Product] "exim"
  products/exim.md
Labels: new-product

#3243 [kotlin] Add 1.9, Update 1.8 eol
  products/kotlin.md
Labels: release-updates

#3265 [visualstudio] Update 17.6.5, 17.4.9, 17.2.17, 17.0.23
  products/visualstudio.md
Labels: release-updates

#3249 [new-product] Adds Red Hat OpenJDK
  products/redhat-build-of-openjdk.md
Labels: new-product

#3252 [new product] Envoy
  products/envoy.md
Labels: new-product

#3253 [new product] Yarn
  products/yarn.md
Labels: new-product

#3269 [mssharepoint] Update latest Subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#3267 [new product] WeeChat
  products/weechat.md
Labels: new-product

#3272 [electron] Mark v22 as supported for now
  products/electron.md
Labels: product-fixes

#3271 Update gerrit.md with Gerrit v3.6.6
  products/gerrit.md
Labels: release-updates

#3120 [SLES] Add details about non-latest minor version releases for each major SLES version
  products/sles.md
Labels: breaking-change

#3274 Switch to cdn.jsdelivr.net to deliver Simple Icons icons
  _headers
  _plugins/product-data-enricher.rb
Labels: enhancement, dependencies

#3277 [mssqlserver] 2022 CU6
  products/mssqlserver.md
Labels: release-updates

#3248 [new product] Prometheus
  products/prometheus.md
Labels: new-product

#3278 [samsung-mobile] Switch H1 to to H2 in description
  products/samsungmobile.md
Labels: bug

#3283 [mattermost] Add 8.0
  products/mattermost.md
Labels: release-updates

#3275 [ipad] Add iPad Pro devices
  products/ipad.md
Labels: release-updates

#3273 [samsung-mobile] Mark Galaxy A50, Galaxy S10e, Galaxy S10 and Galaxy S10+ as EOL
  products/samsungmobile.md
Labels: release-updates

#3294 [vmware-horizon] Add 8.2306
  products/vmware-horizon.md
Labels: release-updates

#3286 [opensearch] Drop few planned releases
  products/opensearch.md
Labels: release-updates

#3290 Update GStreamer to add the logo
  products/gstreamer.md
Labels: enhancement

#3305 [mysql] Fix and simplify version regex
  products/mysql.md
Labels: bug

#3306 [apache-http-server] Set up automation
  products/apache-http-server.md
Labels: enhancement

#3295 [neo4j] Add 5.10
  products/neo4j.md
Labels: release-updates

#3297 [gitlab] Add 16.2
  products/gitlab.md
Labels: release-updates

#3296 [nomad] Add 1.6
  products/nomad.md
Labels: release-updates

#3298 [plesk] Add 18.0.54
  products/plesk.md
Labels: release-updates

#3312 [LibreOffice] Update 7.5.x
  products/libreoffice.md
Labels: release-updates

#3307 [new-product] Apache ActiveMQ
  products/apache-activemq.md
Labels: new-product

#3299 [azul-zulu] Update latest versions
  products/alibaba-dragonwell.md
  products/azul-zulu.md
Labels: release-updates

#3301 [graalvm] Update latest releases
  products/graalvm.md
Labels: release-updates

#3314 [nix] Add 2.17
  products/nix.md
Labels: release-updates

#3315 [grails] Add 6
  products/grails.md
Labels: release-updates

#2243 [dep] Upgrade theme to 0.5.4
  Gemfile
  Gemfile.lock
  HACKING.md
  _config.yml
  _includes/head_custom.html
  _includes/nav.html
  _includes/nav_footer_custom.html
  _redirects
  _sass/custom/custom.scss
  assets/old-favicon.ico
  index.md
  products/java.md
Labels: dependencies, ruby

#3300 [redhat-build-of-openjdk] Update latest releases
  products/redhat-build-of-openjdk.md
Labels: release-updates

#3326 [artifactory] Add 7.63
  products/artifactory.md
Labels: release-updates

#3327 [prometheus] Add 2.46
  products/prometheus.md
Labels: release-updates

#3328 [envoy] Add 1.27
  products/envoy.md
Labels: release-updates

#3325 [apache-http-server] Improve version command
  products/apache-http-server.md
Labels: enhancement

#3302 [graalvm] Add GraalVM for JDK 17/20 and update description
  products/graalvm.md
Labels: release-updates, product-fixes

#3331 [visualstudio] Fix typo on 17.6 `lts` field
  products/visualstudio.md
Labels: bug

#3324 Fix page with large version command
  _sass/custom/custom.scss
Labels: bug
