Repository endoflife-date/endoflife.date, pull requests merged in 2023-12, with the labels that each got.

#4188 [kirby] Add 4.0
  products/kirby.md
Labels: release-updates

#4194 [godot] Add 4.2
  products/godot.md
Labels: release-updates

#4201 [visualstudio] Set up automation
  products/visualstudio.md
Labels: product-updates

#4200 [apache-hop] Add 2.7
  products/apache-hop.md
Labels: release-updates

#4199 [rocket-chat] Add 6.5
  products/rocket-chat.md
Labels: release-updates

#4208 [vue] Update some herodev links
  products/vue.md
Labels: product-updates

#4210 Add Oracle 23c
  products/oracle-database.md
Labels: release-updates

#4211 [azure-devops] Add update cycles for 2019-2022, update latest
  products/azure-devops.md
Labels: release-updates

#4217 Update RDS MySQL 5.7.44 EOL date
  products/amazon-rds-mysql.md
Labels: release-updates

#4223 [gke] Add 1.28
  products/gke.md
Labels: release-updates

#4221 [electron] Add 28
  products/electron.md
Labels: release-updates

#4206 [nixos] Drop latest column
  products/nixos.md
Labels: product-updates

#4236 [rust] Fix regex
  products/rust.md
Labels: bug

#4222 [django] Add 5.0
  products/django.md
Labels: release-updates

#4203 [linuxmint] Add LMDE 6, update LMDE 5 EOL
  products/linuxmint.md
Labels: release-updates, product-updates

#4251 Fix configuration for products using github_release auto method
  products/amazon-corretto.md
  products/bellsoft-liberica.md
  products/eclipse-temurin.md
  products/ibm-semeru.md
  products/quarkus.md
  products/sapmachine.md
Labels: product-fixes

#4254 [apache-hop] Fix 2.7 link
  products/apache-hop.md
Labels: product-fixes

#4258 [dependencytrack] Add 4.10
  products/dependencytrack.md
Labels: release-updates

#4095 [rails] Update 6.1 eol
  products/ruby-on-rails.md
Labels: product-updates

#4280 [flux] Add 2.2
  products/flux.md
Labels: release-updates

#4271 [nextcloud] Add 28
  products/nextcloud.md
Labels: release-updates

#4275 [mssharepoint] Update latest subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#4279 [windows] Add 10 21H2 IoT
  products/windows.md
Labels: product-updates

#4284 [openjdk-builds-from-oracle] Update latest 21
  products/openjdk-builds-from-oracle.md
Labels: release-updates

#4202 [kindle] Update latest releases
  products/kindle.md
Labels: release-updates

#4248 [new-product] Traefik
  products/traefik.md
Labels: new-product

#4292 [panos] Updated PAN-OS 11.1 EOL date and PAN-OS 10.1.11-h4
  products/pan-os.md
Labels: release-updates

#4290 [kubernetes] update kubernetes with 1.29 release
  products/kubernetes.md
Labels: release-updates

#4285 Improve lts field documentation in the contribution guide
  CONTRIBUTING.md
Labels: documentation

#4256 [new-product ] cert-manager
  products/cert-manager.md
Labels: new-product

#4289 Use date instead of date-time in JSON schema.
  product-schema.json
Labels: api

#4185 [pixel] Add Android versions range to a custom column
  products/pixel.md
Labels: product-updates

#4235 [samsungmobile] Update EOL statuses for 4+ year old devices
  products/samsungmobile.md
Labels: product-updates

#4240 Update Next.js EOL details
  products/nextjs.md
Labels: product-updates

#4261 [new-product ] bazel
  products/bazel.md
Labels: new-product

#4297 [umbraco] Add 13
  products/umbraco.md
Labels: release-updates

#4295 [samsungmobile] Drop duplicate entry for Galaxy Tab A 8.0 & S Pen (2019)
  products/samsungmobile.md
Labels: product-fixes

#4300 [openbsd] Fix 3.9 release date
  products/openbsd.md
Labels: release-updates

#4298 [linuxmint] Fix releases order
  products/linuxmint.md
Labels: chore

#4299 [vmware-cloudfoundation] Fix releases order
  products/vmware-cloudfoundation.md
Labels: chore

#4301 [sles] Fix releases order
  products/sles.md
Labels: chore

#4302 [vmware-horizon] Fix releases order
  products/vmware-horizon.md
Labels: chore

#4304 [hbase] Fix releases order
  products/hbase.md
Labels: chore

#4305 [dotnet] Improve regex
  products/dotnet.md
Labels: product-fixes

#4306 [kdeplasma] Improve regex
  products/kdeplasma.md
Labels: product-fixes

#4311 Refactor and improve latest.py script
  .github/workflows/auto-merge-release-updates.yml
  _auto/deploy.sh
  _auto/latest.py
  products/apache-hadoop.md
  products/apache-maven.md
  products/exim.md
  products/grails.md
  products/laravel.md
  products/squid.md
  requirements.txt
Labels: enhancement, chore

#4313 Migrate latest.py from endoflife.date to release-data
  .github/workflows/auto-merge-release-updates.yml
  _auto/bulk-update.py
  _auto/deploy.sh
  _auto/latest.py
  requirements.txt
Labels: chore

#4303 [aws-lambda] Fix a few releaseDates / latestReleaseDates
  products/aws-lambda.md
Labels: release-updates, chore

#4309 [kdeplasma] Fix latest for 5.27, 5.26 5.25 and 5.23
  products/kdeplasma.md
Labels: release-updates

#4316 [neo4j] Add 5.15
  products/neo4j.md
Labels: release-updates

#4319 [dotnet] Update regex comment for SDK versions
  products/dotnet.md
Labels: documentation

#4315 [drupal] Add 10.2
  products/drupal.md
Labels: release-updates

#4310 [tails] Update latest 5 to 5.20
  products/tails.md
Labels: release-updates

#4322 [aws-lambda] Add Python 3.12
  products/aws-lambda.md
Labels: release-updates

#4324 [panos] Updated panos 10.2.7 to 10.2.7-h3
  products/pan-os.md
Labels: release-updates

#4317 Convert Ruby regexes to Python regexes
  CONTRIBUTING.md
  products/alibaba-dragonwell.md
  products/apache-activemq.md
  products/apache-cassandra.md
  products/apache-hadoop.md
  products/clamav.md
  products/docker-engine.md
  products/dotnet.md
  products/erlang.md
  products/exim.md
  products/ffmpeg.md
  products/gitlab.md
  products/go.md
  products/godot.md
  products/gradle.md
  products/gstreamer.md
  products/hbase.md
  products/jenkins.md
  products/kubernetes.md
  products/mariadb.md
  products/microsoft-build-of-openjdk.md
  products/mongodb.md
  products/mysql.md
  products/nextcloud.md
  products/nexus.md
  products/nginx.md
  products/openssl.md
  products/openwrt.md
  products/openzfs.md
  products/perl.md
  products/phpbb.md
  products/phpmyadmin.md
  products/postfix.md
  products/postgresql.md
  products/python.md
  products/rabbitmq.md
  products/ruby.md
  products/salt.md
  products/solr.md
  products/sonarqube.md
  products/spring-boot.md
  products/spring-framework.md
  products/sqlite.md
  products/squid.md
  products/umbraco.md
  products/varnish.md
  products/wordpress.md
  products/yocto.md
Labels: chore

#4330 [mysql] Fix a regex
  products/mysql.md
Labels: bug, product-fixes

#4326 [apache-camel] Add 4.3
  products/apache-camel.md
Labels: release-updates

#4323 [zabbix] Update 6.4 eol
  products/zabbix.md
Labels: release-updates

#4308 [qt] Rollback 6.4 and 5.15 to latest non-commercial releases
  products/qt.md
Labels: release-updates

#4331 [firefox] Add 121
  products/firefox.md
Labels: release-updates

#4335 [mssqlserver] Update 2022 CU10, 2019 CU24
  products/mssqlserver.md
Labels: release-updates

#4327 [emberjs] Add 5.5
  products/emberjs.md
Labels: release-updates

#4341 [citrix-apps-desktops] Add 2311
  products/citrix-apps-desktops.md
Labels: release-updates

#4314 Delete a few little-used tags
  CONTRIBUTING.md
  _redirects
  products/amazon-rds-mysql.md
  products/amazon-rds-postgresql.md
  products/cert-manager.md
  products/kong-gateway.md
  products/puppet.md
  products/react.md
  products/yarn.md
Labels: documentation, product-updates

#4364 [vmware-vcenter] update latest release
  products/vmware-vcenter.md
Labels: release-updates

#4366 [elixir] add 1.16 release
  products/elixir.md
Labels: release-updates

#4368 [gitlab] Fix 16.7
  products/gitlab.md
Labels: product-fixes

#4318 [Nextcloud] Correct EOL dates
  products/nextcloud.md
Labels: release-updates

#4336 remove localization from urls
  products/azul-zulu.md
  products/fairphone.md
  products/ibm-aix.md
  products/ios.md
  products/ipad.md
  products/red-hat-jboss-eap.md
  products/vuetify.md
Labels: documentation, chore

#4370 [internetexplorer] update download url
  products/internetexplorer.md
Labels: product-updates

#4371 [electron] update template changelog url
  products/electron.md
Labels: product-updates

#4112 [new-product] Add memcached
  products/memcached.md
Labels: new-product

#4122 [new-product] Eclipse Jetty
  products/eclipse-jetty.md
Labels: new-product

#4380 Update Ruby dependencies
  Gemfile.lock
Labels: dependencies, ruby

#4234 Update mongodb.md
  products/mongodb.md
Labels: release-updates

#4378 [redhat-openjdk] add openjdk21 LTS version
  products/redhat-build-of-openjdk.md
Labels: release-updates

#4383 [rabbitmq] Simplify regexes
  products/rabbitmq.md
Labels: chore

#4391 [photon] Adds VMWare Photon 5.0
  products/vmware-photon.md
Labels: release-updates

#4395 [sonarqube] replace sonarqube.org by sonarsource.com
  products/sonarqube.md
Labels: product-updates

#4396 :crab: Announcing Rust 1.75.0
  products/rust.md
Labels: release-updates

#4399 Update almalinux.md - Correct URL for 9.3 release
  products/almalinux.md
Labels: product-fixes

#4386 [apache-camel] Add 3.22
  products/apache-camel.md
Labels: release-updates

#4387 [tarantool] Add 3.0
  products/tarantool.md
Labels: release-updates

#4401 [oracle-linux] Update latest 8 to 8.9
  products/oracle-linux.md
Labels: release-updates
