Repository endoflife-date/endoflife.date, pull requests merged in 2023-02, with the labels that each got.

#2420 [neo4j] Add 5.4, EOL 5.3 and 5.2
  products/neo4j.md
Labels: release-updates

#2427 [moodle] Update releaseImage
  products/moodle.md
Labels: release-updates

#2339 [NewProduct] Fairphone
  products/fairphone.md
Labels: new-product

#2418 [New Product] Jekyll
  products/jekyll.md
Labels: new-product

#2453 [docker-engine] Add 23.0, EoL 20.10, Update changelogTemplate
  products/docker-engine.md
Labels: release-updates

#2456 [fairphone] Remove unnecessary lang indication from links
  products/fairphone.md
Labels: release-updates

#2458 [wordpress] Remove 3.9 link
  products/wordpress.md
Labels: release-updates

#2457 [moodle] Remove link for 4.1
  products/moodle.md
Labels: release-updates

#2460 [openbsd] Use a changelogTemplate instead of links
  products/openbsd.md
Labels: release-updates

#2455 [centos] Add link for Centos Stream 9
  products/centos.md
Labels: release-updates

#2469 [electron] Add 23
  products/electron.md
Labels: release-updates

#2467 [drupal] Update git URL used for automation
  products/drupal.md
Labels: product-fixes

#2452 [cakephp] Remove some releases link
  products/cakephp.md
Labels: release-updates

#2428 [mssqlserver] Add 2008, 2005 and links to latest
  products/mssqlserver.md
Labels: release-updates

#2468 [wagtail] Add 4.2
  products/wagtail.md
Labels: release-updates

#2480 Fix `product-data-enricher.rb`
  _plugins/product-data-enricher.rb
Labels: bug

#2445 [NewProduct] XCP-ng
  .gitignore
  products/xcp-ng.md
Labels: new-product

#2475 [java] Add 1.5
  products/java.md
Labels: release-updates

#2423 [New Product] Amazon Corretto
  products/amazon-corretto.md
Labels: new-product

#2483 [api] Mark link as nullable
  assets/openapi.yml
Labels: bug

#2486 [gerrit] fix date
  products/gerrit.md
Labels: bug

#2489 [perl] Remove odd releases and clarify description
  products/perl.md
Labels: release-updates

#2487 [jenkins] Remove `activeSupport` column and declare 2.375 as LTS
  products/jenkins.md
Labels: release-updates

#2491 [SonarQube] Declare 9 as the new LTS version and add eol date for 8
  products/sonarqube.md
Labels: release-updates

#2442 [New Product] SQLite
  products/sqlite.md
Labels: new-product

#2507 [gradle] Add 8 and clarify support description
  products/gradle.md
Labels: release-updates, product-fixes

#2510 [visualstudio] Add 17.4
  products/visualstudio.md
Labels: release-updates

#2516 [mssqlserver] Update 2022-2014 latest
  products/mssqlserver.md
Labels: release-updates

#2508 [kdeplasma] Add 5.27
  products/kdeplasma.md
Labels: release-updates

#2519 [msexchange] Update 2019-2013 latest
  products/msexchange.md
Labels: release-updates

#2511 [Jenkins] Remove activeSupportColumn
  products/jenkins.md
Labels: product-fixes

#2532 [contao] Add 5.1
  products/contao.md
Labels: release-updates

#2520 Display the products count on the homepage
  index.md
Labels: enhancement

#2531 [mattermost] Add 7.8
  products/mattermost.md
Labels: release-updates

#2537 Reformat README and fix 'powered by Jekyll' badge link
  README.md
Labels: documentation

#2542 [neo4j] Add 5.5
  products/neo4j.md
Labels: release-updates

#2544 [New Product] Plesk
  products/plesk.md
Labels: new-product

#2538 Use endoflife logo as the default logo for products without a simpleicons.org icon
  _layouts/product.html
  assets/default-product-logo.svg
Labels: enhancement

#2555 [mariadb] Add 10.11
  products/mariadb.md
Labels: release-updates

#2559 [plesk] Set up automation (#2544)
  products/plesk.md
Labels: enhancement

#2584 [visualstudio] Add changelogTemplate and links
  products/visualstudio.md
Labels: release-updates

#2582 [office] Add links to release cycles
  products/office.md
Labels: release-updates

#2592 [surface] Add links
  products/surface.md
Labels: release-updates

#2588 [iphone] Update page
  products/iphone.md
Labels: release-updates

#2579 [gorilla] Add link, add latest releases and normalize page
  products/gorilla.md
Labels: release-updates

#2574 [eks] Add 1.25
  products/eks.md
Labels: release-updates

#2599 [office] Transfer SP information to `releaseLabels`
  products/office.md
Labels: release-updates

#2573 [keycloak] Add 21.0
  products/keycloak.md
Labels: release-updates

#2597 [visualstudio] Add 17.5
  products/visualstudio.md
Labels: release-updates
