Repository endoflife-date/endoflife.date, pull requests merged in 2023-11, with the labels that each got.

#4003 [nutanix-aos][nutanix-files][nutanix-prism] Add missing auto configuration
  products/nutanix-aos.md
  products/nutanix-files.md
  products/nutanix-prism.md
Labels: chore

#3821 [lineageos] Add corresponding Android versions
  products/lineageos.md
Labels: release-updates

#4009 [windows] Add Windows 11 23H2 (E) and (W)
  products/windows.md
Labels: release-updates

#3997 [redmine] Add 5.1
  products/redmine.md
Labels: release-updates

#4011 docs(wagtail): add 5.2 LTS version
  products/wagtail.md
Labels: release-updates

#3996 Fix main navigation panel when JS is disabled
  _includes/css/activation.scss.liquid
Labels: bug

#4012 [graylog] Fix changelogTemplate
  products/graylog.md
Labels: product-fixes

#4005 [graylog] Add 5.2
  products/graylog.md
Labels: release-updates

#4018 [mysql] Adds 8.2
  products/mysql.md
Labels: release-updates

#4020 [jhipster] Add 8
  products/jhipster.md
Labels: release-updates

#3995 [new-product] Amazon CDK
  products/amazon-cdk.md
Labels: new-product

#4025 [ms-jdk] Add EOL date for 21
  products/microsoft-build-of-openjdk.md
Labels: product-fixes

#4027 [grails] Fix EOL dates and link
  products/grails.md
Labels: product-fixes

#4019 [dbt-core] Add 1.7
  products/dbt-core.md
Labels: release-updates

#4031 [muleruntime] Fix 4.1 link
  products/muleruntime.md
Labels: release-updates

#4021 [emberjs] Adds 5.4 release cycle
  products/emberjs.md
Labels: release-updates

#4033 [xenserver] XenServer.org redirects to xenserver.com
  _plugins/product-data-validator.rb
  products/xcp-ng.md
Labels: product-fixes

#4002 Add support for custom columns
  CONTRIBUTING.md
  _config.yml
  _includes/custom-column-td.html
  _includes/custom-column-th.html
  _layouts/product.html
  _plugins/product-data-validator.rb
  product-schema.json
Labels: enhancement

#4030 [wagtail] Switch to the pypi auto method
  products/wagtail.md
Labels: release-updates

#4034 Fix Docker Hub auto method name in documentation
  CONTRIBUTING.md
Labels: chore

#4032 Exclude some URLs from triggering a validation error
  _plugins/product-data-validator.rb
Labels: chore

#4037 [iphone] Migrate the iOS Compatibility table to a custom column
  products/iphone.md
Labels: product-updates

#4046 [consul] Add 1.17
  products/consul.md
Labels: release-updates

#4047 [exim] Add 4.97
  products/exim.md
Labels: release-updates

#4052 [argocd] Add 2.9
  products/argocd.md
Labels: release-updates

#4053 [ansible-core] Add 2.16
  products/ansible-core.md
Labels: release-updates

#3991 [new-product] Red Hat JBoss EAP
  products/red-hat-jboss-eap.md
Labels: new-product

#4057 [visualstudio] Update 15.9.58
  products/visualstudio.md
Labels: release-updates

#4054 [exim] Update wording for obsolete versions
  products/exim.md
Labels: documentation

#4035 [apache-camel] Migrate the java support table to a custom column
  products/apache-camel.md
Labels: product-updates

#4036 [azul-zulu] Migrate the Zulu's / OpenJDK correspondance table to a custom column
  products/azul-zulu.md
Labels: product-updates

#4060 [nexus] Adjust version template
  products/nexus.md
Labels: product-fixes

#4059 [wordpress] Add 6.4
  products/wordpress.md
Labels: release-updates

#4062 [iphone] Compact supportedIosVersions for 5c
  products/iphone.md
Labels: product-updates

#4069 [kong-gateway] Add 3.5
  products/kong-gateway.md
Labels: release-updates

#4068 [redhat-satellite] Add 6.14
  products/redhat-satellite.md
Labels: release-updates

#4070 Simplify auto configurations
  CONTRIBUTING.md
  products/docker-engine.md
  products/dotnet.md
  products/ffmpeg.md
  products/gerrit.md
  products/gitlab.md
  products/go.md
  products/gradle.md
  products/gstreamer.md
  products/hbase.md
  products/kubernetes.md
  products/mongodb.md
  products/nextcloud.md
  products/nginx.md
  products/openzfs.md
  products/phpmyadmin.md
  products/postgresql.md
  products/python.md
  products/rabbitmq.md
  products/ruby-on-rails.md
  products/ruby.md
  products/spring-boot.md
  products/spring-framework.md
  products/varnish.md
  products/yocto.md
Labels: chore

#4080 [ibm-aix] Flag as UNIX system
  products/ibm-aix.md
Labels: product-updates

#4079 [openbsd] Add unix-distribution tag
  products/openbsd.md
Labels: product-updates

#4061 [wordpress] supportedPHPVersions compact and migrate to custom column
  products/wordpress.md
Labels: product-updates

#4075 [looker] Add 23.20
  products/looker.md
Labels: release-updates

#4084 Exclude some URLs from triggering a validation error
  _plugins/product-data-validator.rb
Labels: chore

#4083 [wagtail] Update latest 2.12
  products/wagtail.md
Labels: release-updates

#4082 [ffmpeg] Mark 5.0 as EOL
  products/ffmpeg.md
Labels: release-updates

#4089 [ibm-aix] Add 7.3.2
  products/ibm-aix.md
Labels: release-updates

#4088 [puppet] Add 3 and 4
  products/puppet.md
Labels: release-updates

#4092 [opensearch] Add active development column
  products/opensearch.md
Labels: product-fixes

#4096 [dotnet] Add 8.0
  products/dotnet.md
Labels: release-updates

#4100 [istio] Add 1.20, Update 1.17 eol
  products/istio.md
Labels: release-updates

#4097 [visualstudio] Add 17.8, Update 17.7.7, 14.0 KB
  products/visualstudio.md
Labels: release-updates

#4045 [mattermost] Add 9.2
  products/mattermost.md
Labels: release-updates

#4105 [grafana] Update version regex
  products/grafana.md
Labels: product-updates

#4106 [apache-camel] Add 4.2
  products/apache-camel.md
Labels: release-updates

#4107 [powershell] Add 7.4
  products/powershell.md
Labels: release-updates

#4108 [spring-framework] Add 6.1
  products/spring-framework.md
Labels: release-updates

#4109 [prometheus] Add 2.48
  products/prometheus.md
Labels: release-updates

#4115 [linux] 6.6 became LTS
  products/linuxkernel.md
Labels: release-updates, product-fixes

#4114 [amazon-neptune] Add 1.3.0.0, add changelogTemplate, apply Style Guide
  products/amazon-neptune.md
Labels: release-updates

#4104 [gitlab] Add 16.6
  products/gitlab.md
Labels: release-updates

#4119 Exclude visualstudio.microsoft.com from links validation
  _plugins/product-data-validator.rb
Labels: chore

#4118 [pan-os] Fix 9.1 link
  products/pan-os.md
Labels: release-updates

#4123 [amazon-rds-postgresql] Add 16.1
  products/amazon-rds-postgresql.md
Labels: release-updates

#4110 [spring-framework] Add supportedJakartaVersions
  products/spring-framework.md
Labels: release-updates

#4133 [gradle] Rename testedKotlinVersoins to testedKotlinVersions
  products/gradle.md
Labels: product-fixes

#4131 [nix] Add 2.19
  products/nix.md
Labels: release-updates

#4128 [freebsd] Add 14
  products/freebsd.md
Labels: release-updates

#4135 Jenkins 2.414 is EOL, add Jenkins 2.426
  products/jenkins.md
Labels: release-updates

#3675 [eks] Add notes about extended support
  products/eks.md
Labels: product-updates

#4139 [firefox] Add 120
  products/firefox.md
Labels: release-updates

#4138 [gradle] Update compatibility information
  products/gradle.md
Labels: product-updates

#4140 [plesk] Add 18.0.57
  products/plesk.md
Labels: release-updates

#4143 [gitlab] Remove 16.6 link
  products/gitlab.md
Labels: release-updates

#3982 [new-product] Add AWS Lambda
  products/aws-lambda.md
Labels: new-product

#4120 [sles] Add suse tag
  products/sles.md
Labels: product-updates

#4151 [keycloak] Add 23.0
  products/keycloak.md
Labels: release-updates

#4150 [spring-boot] Add 3.2
  products/spring-boot.md
Labels: release-updates

#4156 [apache-maven] Flag as a build-tool
  products/apache-maven.md
Labels: product-updates

#4166 [almalinux] Set iconSlug
  products/almalinux.md
Labels: product-updates

#4164 [apache-activemq] Fix 6.0 link
  products/apache-activemq.md
Labels: product-fixes

#4165 Exclude forums.unrealircd.org from links validation
  _plugins/product-data-validator.rb
Labels: chore

#4158 [aws-lambda] Add Amazon Linux 2023, Node.js 20 and Java 21
  products/aws-lambda.md
Labels: release-updates

#4167 [coldfusion] Set up automation
  products/coldfusion.md
Labels: product-updates

#4168 [msexchange] Update latest 2016 and 2019
  products/msexchange.md
Labels: release-updates

#4157 [Gradle] Flag as a build-tool
  products/gradle.md
Labels: product-updates

#4159 [neo4j] Add 5.14
  products/neo4j.md
Labels: release-updates

#4172 [gerrit] Add 3.9
  products/gerrit.md
Labels: release-updates

#4173 [mariadb] Update 11.0 eol
  products/mariadb.md
Labels: release-updates

#4175 [visualstudio] Update 17.8.1, 17.6.10, 17.4.14, 16.11.32
  products/visualstudio.md
Labels: release-updates

#4073 [new product] rancher
  products/rancher.md
Labels: new-product

#4180 [visualstudio] Update 17.8.2
  products/visualstudio.md
Labels: release-updates

#4174 [mssharepoint] Update latest
  products/mssharepoint.md
Labels: release-updates
