Repository endoflife-date/endoflife.date, pull requests merged in 2023-01, with the labels that each got.

#2125 Normalize a few product files
  products/almalinux.md
  products/alpinelinux.md
  products/amazon-linux.md
  products/android.md
  products/angular.md
Labels: enhancement

#2231 Add Java automation
  products/java.md
Labels: enhancement

#2201 [apple] Add active support column.
  products/ios.md
  products/ipados.md
  products/watchos.md
Labels: product-fixes

#2244 [headers] Update _headers
  _headers
Labels: bug

#2264 [linux] fix eol date : 4.9.x became eol yesterday
  products/linuxkernel.md
Labels: release-updates, product-fixes

#2266 [Qt] update 6.2 to latest version
  products/qt.md
Labels: release-updates

#2259 [java] Add identifiers
  products/java.md
Labels: release-updates

#2260 [nodejs] Add identifiers
  products/nodejs.md
Labels: release-updates

#2258 [golang] Add identifiers
  products/go.md
Labels: release-updates

#2276 [typo3] Add 12 blog link
  products/typo3.md
Labels: release-updates

#2297 [windows] remove 'Windows ' part from releaseCycle
  products/windows.md
Labels: product-fixes

#2295 [gke] Updated EOL dates and version infos
  products/gke.md
Labels: release-updates

#2303 [office] Add 365
  products/office.md
Labels: release-updates

#2305 [linuxkernel] 6.0 EoL
  products/linuxkernel.md
Labels: release-updates

#2304 [mattermost] New releases and automation
  products/mattermost.md
Labels: release-updates, product-fixes

#2323 [firefox] Update 109
  products/firefox.md
Labels: release-updates

#2322 [nix] Add 2.13
  products/nix.md
Labels: release-updates

#2307 [redis] Add identifiers
  products/redis.md
Labels: release-updates, product-fixes

#2352 [gitlab] Add 15.8
  products/gitlab.md
Labels: release-updates

#2353 [Samsung Mobile] Remove 'Samsung' from Galaxy A23 5G cycle name
  products/samsungmobile.md
Labels: product-fixes

#2358 [end-of-life-filters] improve performance for .0 droping
  _plugins/end-of-life-filters.rb
Labels: enhancement

#2356 [Postfix] Fix links
  products/postfix.md
Labels: product-fixes

#2367 Fix changelog links handling in product template
  _auto/validate.py
  _layouts/product.html
  products/vmware-horizon.md
Labels: bug

#2371 [oracle-linux] Update dates and add support tiers
  products/oraclelinux.md
Labels: product-fixes

#2328 [NewProduct] Apache Camel
  _plugins/end-of-life-filters.rb
  products/apache-camel.md
Labels: new-product

#2381 Closes #2376
  README.md
Labels: community

#2383 [rabbitmq] Mention VMWare for extended support
  products/rabbitmq.md
Labels: product-fixes

#2385 [nexus] Remove iconSlug
  products/nexus.md
Labels: product-fixes

#2378 [spring-boot] Update page
  products/spring-boot.md
Labels: release-updates

#2377 [spring-framework] Update page
  products/spring-framework.md
Labels: release-updates

#2391 [quarkus] Add 2.16
  products/quarkus.md
Labels: release-updates

#2388 [spring-framework] Improve Java support documentation
  products/spring-framework.md
Labels: product-fixes

#2397 [amazon-linux] Fix `changelogTemplate`
  products/amazon-linux.md
Labels: product-fixes

#2389 [spring-boot] Improve Java support documentation
  products/spring-boot.md
Labels: product-fixes

#2396 [ie] Break down all 11 versions.
  products/internetexplorer.md
Labels: product-fixes

#2393 [LibreOffice] Update 7.4.x
  products/libreoffice.md
Labels: release-updates

#2409 [vmware-srm] Focus on supported releases
  products/vmware-srm.md
Labels: product-fixes

#2410 [apple] Mark iOS12 devices as supported
  products/ios.md
  products/ipad.md
  products/iphone.md
Labels: product-fixes

#2412 [quarkus] Add extended support column (#2246)
  products/quarkus.md
Labels: release-updates

#2415 [api-platform] Add 3.1
  products/api-platform.md
Labels: release-updates

#2416 [haproxy] Update 2.5 eol date
  products/haproxy.md
Labels: release-updates
