Repository endoflife-date/endoflife.date, pull requests merged in 2023-04, with the labels that each got.

#2780 [vmware-esxi] Update latest release data
  products/vmware-esxi.md
Labels: release-updates

#2727 [azul-zulu] Add 20
  products/azul-zulu.md
Labels: release-updates

#2728 [amazon-corretto] Add 20
  products/amazon-corretto.md
Labels: release-updates

#2723 [ansible] Fix Python Compatibility table
  products/ansible.md
Labels: product-fixes

#2732 [samsungmobile] Add links and remove some models
  products/samsungmobile.md
Labels: release-updates

#2783 [VMWARE] Vcenter - Add release 8.0c
  products/vmware-vcenter.md
Labels: release-updates

#2788 [eks] Improve EOL for 1.22
  products/eks.md
Labels: product-fixes

#2792 [sonarqube] Adds 10.0.0
  products/sonarqube.md
Labels: release-updates

#2791 [electron] Adds v24
  products/electron.md
Labels: release-updates

#2769 [ionic] Add 7.0
  products/ionic.md
Labels: release-updates, product-fixes

#2778 [New Product] ISC DHCP
  products/isc-dhcp.md
Labels: new-product

#2773 [New Product] Alibaba Dragonwell
  products/alibaba-dragonwell.md
Labels: new-product

#2814 FreeBSD 13.2 released
  products/freebsd.md
Labels: release-updates

#2815 [qt] Add 6.5
  products/qt.md
Labels: release-updates

#2821 [red-hat-openshift] Update 4.12.11, 4.11.35, 4.10.55, 4.9.59
  products/red-hat-openshift.md
Labels: release-updates

#2774 [New Product] Microsoft Build of OpenJDK
  products/microsoft-build-of-openjdk.md
Labels: new-product

#2738 [magento] Update description and links
  products/magento.md
Labels: product-fixes

#2830 [quarkus] Add 3.0
  products/quarkus.md
Labels: release-updates

#2827 [nginx] Add 1.24 and mark 1.22 EOL
  products/nginx.md
Labels: release-updates

#2826 [nix] Add 2.15 and mark 2.14 as EOL
  products/nix.md
Labels: release-updates

#2833 [mssqlserver] Update 2022 CU3, 2019 CU20
  products/mssqlserver.md
Labels: release-updates

#2829 [kubernetes] Add 1.27
  products/kubernetes.md
Labels: release-updates

#2828 [firefox] Add 112
  products/firefox.md
Labels: release-updates

#2834 [mattermost] Add 7.10
  products/mattermost.md
Labels: release-updates

#2836 [gke] Adds 1.26
  products/gke.md
Labels: release-updates

#2835 [cos] Adds COS-105
  products/cos.md
Labels: release-updates

#2839 [firefox] Add unmaintained releaseCycles > 102
  products/firefox.md
Labels: release-updates

#2841 [grafana] Manually update to 9.4.7
  products/grafana.md
Labels: release-updates

#2843 [php] Switch to custom automation
  products/php.md
Labels: product-fixes

#2842 [aks] Adds note about LTS
  products/azure-kubernetes-service.md
Labels: product-fixes

#2846 [postfix] Add 3.8
  products/postfix.md
Labels: release-updates

#2848 [nodejs] Adds v20.
  products/nodejs.md
Labels: release-updates

#2849 [fedora] 38 release
  products/fedora.md
Labels: release-updates

#2860 [vmware-horizon] Update latest release data
  products/vmware-horizon.md
Labels: release-updates

#2862 [hbase] Normalize page
  products/hbase.md
Labels: enhancement

#2840 [mongodb] Adds 6.3 rapid release
  products/mongodb.md
Labels: release-updates

#2879 [visualcobol] Fix oldest releases links
  products/visual-cobol.md
Labels: product-fixes

#2875 [vue] Fix release cycle 1 link
  products/vue.md
Labels: product-fixes

#2871 [eclipse-temurin] Fix changelogTemplate
  products/eclipse-temurin.md
Labels: product-fixes

#2885 Update Pan-OS 10.1.9-h3
  products/pan-os.md
Labels: release-updates

#2887 [fedora] Fix 38 EOL date
  products/fedora.md
Labels: product-fixes

#2876 [nodejs] Fix links for oldest releases
  products/nodejs.md
Labels: product-fixes

#2881 [moodle] Add 4.2
  products/moodle.md
Labels: release-updates

#2863 [neo4j] Add 5.7 and mark 5.6 as EOL
  products/neo4j.md
Labels: release-updates

#2864 [keycloak] Add 21.1 and mark 21.0 as EOL
  products/keycloak.md
Labels: release-updates

#2891 [ubuntu] Update `changelogTemplate`
  products/ubuntu.md
Labels: product-fixes

#2896 [vmware-photon] Fix 1.0 and 2.0 links
  products/vmware-photon.md
Labels: product-fixes

#2893 [quarkus] Fix 0.28 link
  products/quarkus.md
Labels: product-fixes

#2895 [splunk] Fix link to 7.1 and 7.2
  products/splunk.md
Labels: product-fixes

#2874 [rabbitmq] Fix oldest release links
  products/rabbitmq.md
Labels: product-fixes

#2865 [gitlab] Add 15.11
  products/gitlab.md
Labels: release-updates

#2866 [azul-zulu] Update latest releases and improve description
  products/azul-zulu.md
Labels: release-updates
