Repository endoflife-date/endoflife.date, pull requests merged in 2023-03, with the labels that each got.

#2591 [ipados] Add links
  products/ipados.md
Labels: release-updates

#2589 [watchos] Add changelogTemplate and links
  products/watchos.md
Labels: release-updates

#2585 [windows-embedded] Update page
  products/windowsEmbedded.md
Labels: enhancement, release-updates

#2600 [consul] Add 1.15 and mark 1.12 EOL
  products/consul.md
Labels: release-updates

#2581 [ipad] Add links to release cycles
  products/ipad.md
Labels: release-updates

#2558 Updating amazon linux release cycles
  products/amazon-linux.md
Labels: release-updates

#2577 Fix pages description
  CONTRIBUTING.md
  _includes/head_custom.html
  _plugins/product-data-enricher.rb
  index.md
  recommendations.md
Labels: bug

#2576 [New Product] Add Mastodon
  products/mastodon.md
Labels: new-product

#2580 [azure-kubernetes-service] Add links to release cycles
  products/azure-kubernetes-service.md
Labels: release-updates

#2603 [debian] Separate EOL and EOL LTS
  products/debian.md
Labels: release-updates

#2604 [rabbitmq] Rename general -> community support
  products/rabbitmq.md
Labels: product-fixes

#2549 [mssqlserver] Add 2000, 7.0, 6.5, 6.0, Add codenames
  products/mssqlserver.md
Labels: release-updates

#2601 [grafana] Add 9.4
  products/grafana.md
Labels: release-updates

#2615 [sonarqube] Switch auto configuration from docker to git
  products/sonarqube.md
Labels: release-updates

#2614 [vault] Add 1.13, make 1.10 EOL, update changelogTemplate
  products/hashicorp-vault.md
Labels: release-updates, product-fixes

#2617 [godot] Add 4.0
  products/godot.md
Labels: release-updates

#2545 [New Product] Eclipse Temurin
  products/eclipse-temurin.md
Labels: new-product

#2618 [unity3d] Update version info
  products/unity.md
Labels: release-updates

#2629 [linux] Update releaseImage
  products/linuxkernel.md
Labels: product-fixes

#2639 Update docker-engine.md
  products/docker-engine.md
Labels: product-fixes

#2641 Replace Amazon Linux 2022 with Amazon Linux 2023
  products/amazon-linux.md
Labels: product-fixes

#2645 [pixel] Move wikipedia links to release links
  products/pixel.md
Labels: release-updates

#2643 [filemaker] Update release data (#39)
  products/filemaker.md
Labels: release-updates

#2642 [zabbix] Add 6.4
  products/zabbix.md
Labels: release-updates

#2644 [intelprocessors] Add links and normalize page
  products/intelprocessors.md
Labels: release-updates

#2646 [haproxy] Update description regarding EOL dates
  products/haproxy.md
Labels: product-fixes

#2621 [nomad] Add 1.5, set 1.2 EOL
  products/nomad.md
Labels: release-updates

#2594 Hide oldest unmaintained releases cycles by default
  _layouts/product.html
  _plugins/product-data-enricher.rb
  assets/register-show-hidden-releases-handler.js
Labels: enhancement

#2602 [ffmpeg] Add 6.0
  products/ffmpeg.md
Labels: release-updates

#2652 [amazon-linux] Take note of the 2022->23 rename
  products/amazon-linux.md
Labels: product-fixes

#2658 [terraform] Add 1.4
  products/terraform.md
Labels: release-updates

#2476 [New Product] Oracle Database
  products/oracle-database.md
Labels: new-product

#2492 [New Product] Add Azul Zulu
  products/azul-zulu.md
Labels: new-product

#2669 Fix the discontinued column label
  _layouts/product.html
Labels: bug

#2668 [telegraf] Add 1.26
  products/telegraf.md
Labels: release-updates

#2620 [visualstudio] Add latest details
  products/visualstudio.md
Labels: release-updates

#2686 [openssl] Add 3.1 and update `changelogTemplate`
  products/openssl.md
Labels: release-updates

#2689 [firefox] Add 111
  products/firefox.md
Labels: release-updates

#2688 [plesk] Add 18.0.51
  products/plesk.md
Labels: release-updates

#2682 [amazon-linux] AL2023 is now GA
  products/amazon-linux.md
Labels: product-fixes

#2694 [mattermost] Add 7.9
  products/mattermost.md
Labels: release-updates

#2707 [jenkins] Use `x.y` date for `releaseDate` and `x.y.1` date for `lts`
  products/jenkins.md
Labels: release-updates

#2713 [pan-cortex-xdr] Add 8.0
  products/pan-cortex-xdr.md
Labels: release-updates

#2714 [lineageos] Add 20.0
  products/lineageos.md
Labels: release-updates

#2719 [visualstudio] Update 17.5.3, 17.4.6, 17.2.14, 17.0.20, 16.11.25, 15.9.53
  products/visualstudio.md
Labels: release-updates

#2718 [Gitlab] Add 15.10
  products/gitlab.md
Labels: release-updates

#2387 [Samsung] Add missing devices
  products/samsungmobile.md
Labels: release-updates

#2730 [blender] Mark 3.4 as still supported / not EOL
  products/blender.md
Labels: release-updates

#2733 [New Product] Umbraco CMS
  products/umbraco.md
Labels: new-product

#2649 Add OpenShift
  products/red-hat-openshift.md
Labels: new-product

#2736 Update kindle firmware version
  products/kindle.md
Labels: release-updates

#2743 [rockylinux] Use changelogTemplate
  products/rockylinux.md
Labels: product-fixes

#2742 [proxmox-ve] Update changelogTemplate
  products/proxmox-ve.md
Labels: product-fixes

#2741 [neo4j] Add 5.6
  products/neo4j.md
Labels: release-updates

#2729 [eclipse-temurin] Add 20
  products/eclipse-temurin.md
Labels: release-updates

#2726 [java] Add 20
  products/java.md
Labels: release-updates

#2753 [windows-embedded] Add releaseLabel back
  products/windowsEmbedded.md
Labels: product-fixes

#2739 [kindle] Add kindle scribe and normalize page
  products/kindle.md
Labels: release-updates

#2760 [blender] Add 3.5
  products/blender.md
Labels: release-updates

#2759 Display title and tags on product pages
  _layouts/product.html
  _sass/custom/custom.scss
Labels: enhancement

#2768 [wordpress] Adds 6.2.0
  products/wordpress.md
Labels: release-updates

#2624 [New Product] Add RDS Postgres
  products/amazon-rds-mysql.md
  products/amazon-rds-postgresql.md
Labels: new-product

#2770 [amazon-rds-mysql][amazon-rds-postgresql] Add auto configuration
  products/amazon-rds-mysql.md
  products/amazon-rds-postgresql.md
Labels: product-fixes

#2775 [New product] Nuxt
  products/nuxt.md
Labels: new-product

#2779 [wordpress] Update regex to drop the `.0` suffix from versions
  products/wordpress.md
Labels: product-fixes
