Repository endoflife-date/endoflife.date, pull requests merged in 2024-05, with the labels that each got.

#5071 [php] Release Cycle is 4 years now
  products/php.md
Labels: product-fixes

#5068 [traefik] add 3.0 and update eol for 2.11
  products/traefik.md
Labels: release-updates

#5073 [rabbitmq] Drop release cycle automation configuration
  products/rabbitmq.md
Labels: product-fixes

#5074 [rockylinux] Update auto configuration
  products/rockylinux.md
Labels: product-updates

#5072 [ubuntu] Drop releaseImage
  products/ubuntu.md
Labels: product-fixes

#5076 [rabbitmq] Use precise dates
  products/rabbitmq.md
Labels: product-fixes

#5077 [opentofu] Adds 1.7 release
  products/opentofu.md
Labels: release-updates

#5082 [quarkus] Add 3.10
  products/quarkus.md
Labels: release-updates

#5084 [yocto] Add 5.0
  products/yocto.md
Labels: release-updates

#5083 [wagtail] Add 6.1
  products/wagtail.md
Labels: release-updates

#5085 [keycloak] Switch automation to GitHub releases
  products/keycloak.md
Labels: product-updates

#5070 [mysql] add 8.4
  products/mysql.md
Labels: release-updates

#5087 [csp] Add new github user assets domain
  _headers
Labels: bug

#5081 [api-platform] Add 3.3
  products/api-platform.md
Labels: release-updates

#5094 Revert "[ubuntu] Drop releaseImage"
  products/ubuntu.md
Labels: bug

#5110 [argocd] Add 2.11
  products/argocd.md
Labels: release-updates

#5111 [dbt-core] Add 1.8
  products/dbt-core.md
Labels: release-updates

#5112 [dependencytrack] Add 4.11
  products/dependencytrack.md
Labels: release-updates

#5113 [graylog] Add 6.0
  products/graylog.md
Labels: release-updates

#5114 [looker] Add 24.8
  products/looker.md
Labels: release-updates

#5115 [meilisearch] Add 1.8
  products/meilisearch.md
Labels: release-updates

#5117 Upgrade Ruby to 3.3.1
  .ruby-version
Labels: dependencies, ruby

#5126 [linuxkernel] Add 6.9
  products/linuxkernel.md
Labels: release-updates

#5123 [artifactory] Add 7.84
  products/artifactory.md
Labels: release-updates

#5122 [apache-camel] Add 4.6, update 4.5 eol
  products/apache-camel.md
Labels: release-updates

#5127 [linuxkernel] Add 6.7 EOL link
  products/linuxkernel.md
Labels: release-updates

#5136 [firefox] Add 126, update 15 eol
  products/firefox.md
Labels: release-updates

#5141 [composer] Update 2.2 eol
  products/composer.md
Labels: release-updates

#5137 [flux] Add 2.3, update 2.0 eol
  products/flux.md
Labels: release-updates

#5142 [fedora] F38 EOL date correction
  products/fedora.md
Labels: product-fixes

#5139 [Gitlab] Add 17.0
  products/gitlab.md
Labels: release-updates

#5150 (Debian) corrected links
  products/debian.md
Labels: product-fixes

#5156 [linux] update releaseImage
  products/linuxkernel.md
Labels: release-updates

#5152 [mssqlserver] Update 2022 CU13
  products/mssqlserver.md
Labels: release-updates

#5158 [cockroachdb] Fix auto configuration
  products/cockroachdb.md
Labels: product-updates

#5159 [emberjs] Fix auto configuration
  products/emberjs.md
Labels: product-updates

#5160 [rockylinux] Fix auto configuration
  products/rockylinux.md
Labels: product-updates

#5161 [node-feature-discovery] Fix auto configuration
  products/node-feature-discovery.md
Labels: product-updates

#5157 [Gerrit] Introduce v3.10.0 and make v3.7.x EOL
  products/gerrit.md
Labels: release-updates

#5143 [mssharepoint] Update latest subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#5138 [mattermost] Add 9.8
  products/mattermost.md
Labels: release-updates

#5021 [emberjs] Adds 5.8
  products/emberjs.md
Labels: release-updates

#5155 [new product] apache flink
  products/apache-flink.md
Labels: new-product

#5175 [alpinelinux] Add 3.20
  products/alpinelinux.md
Labels: release-updates

#5179 [spring-boot] Add 3.3
  products/spring-boot.md
Labels: release-updates

#5177 [cockroachdb] Add 24.1
  products/cockroachdb.md
Labels: release-updates

#5178 [plesk] Add 18.0.61
  products/plesk.md
Labels: release-updates

#5189 [jenkins] Add 2.452 LTS
  products/jenkins.md
Labels: release-updates

#5196 [nutanix-aos] Add 6.8
  products/nutanix-aos.md
Labels: release-updates

#5194 [jira] Add 9.16
  products/jira.md
Labels: release-updates

#5193 [apache-hop] Add 2.9
  products/apache-hop.md
Labels: release-updates

#5201 [weechat] Add 4.3
  products/weechat.md
Labels: release-updates

#5185 [eks] Adds 1.30
  products/eks.md
Labels: release-updates

#5176 [angular] Add 18
  products/angular.md
Labels: release-updates

#5203 [vmware-esxi] Update latest release
  products/vmware-esxi.md
Labels: release-updates

#5188 [apache-flink] Fix changelogTemplate
  products/apache-flink.md
Labels: product-fixes

#5200 [visualstudio] Add 17.10
  products/visualstudio.md
Labels: release-updates

#5186 [kubernetes-csi-node-driver-registrar] Drop 0.4
  products/kubernetes-csi-node-driver-registrar.md
Labels: release-updates

#5199 [rocket-chat] Add 6.8
  products/rocket-chat.md
Labels: release-updates

#5198 [nutanix-prism] Add pc.2024.1, update pc.2023.4, pc.2023.3
  products/nutanix-prism.md
Labels: release-updates

#5197 [nutanix-files] Add 5.0
  products/nutanix-files.md
Labels: release-updates

#5187 [muleruntime] Update latest releases
  products/muleruntime.md
Labels: release-updates

#5184 [mariadb] Update 11.3 eol for rolling release
  products/mariadb.md
Labels: release-updates

#5208 [eks] 1.30 latest is eks2
  products/eks.md
Labels: release-updates

#5209 [ibm-semeru] Adds v22
  products/ibm-semeru.md
Labels: release-updates

#5207 Updated openSUSE release image
  products/opensuse.md
Labels: product-updates

#5212 [nutanix-prism] Remove duplicate key
  products/nutanix-prism.md
Labels: bug

#5223 [oraclelinux] Adds 8.10
  products/oracle-linux.md
Labels: release-updates

#5219 [haproxy] add 3.0
  products/haproxy.md
Labels: release-updates

#5218 [mediawiki] Update image
  products/mediawiki.md
Labels: product-updates

#5226 [nomad] Add 1.8
  products/nomad.md
Labels: release-updates

#5228 [umbraco] Add 14
  products/umbraco.md
Labels: release-updates

#5227 [quarkus] Add 3.11
  products/quarkus.md
Labels: release-updates

#5220 [nginx] add 1.27.x
  products/nginx.md
Labels: release-updates

#5233 [linuxkernel] Update 6.8 eol
  products/linuxkernel.md
Labels: release-updates
