Repository endoflife-date/endoflife.date, pull requests merged in 2024-08, with the labels that each got.

#5577 [apache-flink] add 1.20
  products/apache-flink.md
Labels: release-updates

#5578 [contour] add 1.30
  products/contour.md
Labels: release-updates

#5576 [quarkus]: add 3.13
  products/quarkus.md
Labels: release-updates

#5574 [unity]: Update latest for Unity 6 and 2022.3
  products/unity.md
Labels: release-updates

#5534 [New Product] Amazon RDS for MariaDB
  products/amazon-rds-mariadb.md
Labels: new-product

#5557 [opentofu] add 1.8
  products/opentofu.md
Labels: release-updates

#5572 [gke] Document channel information
  products/gke.md
Labels: product-updates

#5580 [confluence] Add 9.0
  products/confluence.md
Labels: release-updates

#5581 [rancher] Add 2.9
  products/rancher.md
Labels: release-updates

#5582 [wagtail] Add 6.2
  products/wagtail.md
Labels: release-updates

#5587 [keda] add 2.15
  products/keda.md
Labels: release-updates

#5588 [drupal] add 11.0
  products/drupal.md
Labels: release-updates

#5088 [new product] SUSE Manager
  products/suse-manager.md
Labels: new-product

#5496 [new product] add Coder
  products/coder.md
Labels: new-product

#5518 [New Product] add Kuma
  products/kuma.md
Labels: new-product

#5590 [coder] Make eoasColumn visible
  products/coder.md
Labels: product-updates

#5595 [nexus] Fix releaseDate regex in auto configuration
  products/nexus.md
Labels: auto

#5593 [chef-infra-server] Update the name of the Chef Docs site + add CPE
  products/chef-infra-server.md
Labels: product-updates

#5606 [netbsd] Automate versions and EOL retrieval
  products/netbsd.md
Labels: auto

#5602 [product-data-validator] Update excluded links list
  _plugins/product-data-validator.rb
Labels: chore

#5359 [new product] add apache-apisix
  products/apache-apisix.md
Labels: new-product

#5164 [new product] grafana loki
  products/grafana-loki.md
  products/grafana.md
Labels: new-product

#5603 [red-hat-satellite] Update 6.0 and 6.1 links
  products/red-hat-satellite.md
Labels: release-updates

#5600 [openssl] Update links
  products/openssl.md
Labels: product-updates

#5589 [nix] Add 2.24
  products/nix.md
Labels: release-updates

#5604 [apache-flink] Update changelogTemplate
  products/apache-flink.md
Labels: product-fixes

#5598 [drush] Add 13
  products/drush.md
Labels: release-updates

#5601 [salt] Automate eoas and eol retrieval
  products/salt.md
Labels: auto

#5618 Fix PAN-OS
  products/pan-os.md
Labels: product-fixes

#5610 v6.1, v6.2 and v6.3 don't get security fixes any more
  products/shopware.md
Labels: release-updates

#5630 [django] Adds 5.1
  products/django.md
Labels: release-updates

#5619 [coder] Add 2.14
  products/coder.md
Labels: release-updates

#5625 [pci-dss] Minor updates for 3.2.1 EOL
  products/pci-dss.md
Labels: product-fixes

#5638 [amazon-neptune] add 1.3.3.0 and 1.2.1.2
  products/amazon-neptune.md
Labels: release-updates

#5637 [nexus] add 3.71
  products/nexus.md
Labels: release-updates

#5636 [plesk] add 18.0.63
  products/plesk.md
Labels: release-updates

#5634 Update the latest releases of JBoss 7 and 8
  products/red-hat-jboss-eap.md
Labels: release-updates

#5641 [apache-subversion] Suppress 1.0 link
  products/apache-subversion.md
Labels: release-updates

#5640 [mongodb] Fix 1.2 to 3.0 release notes links
  products/mongodb.md
Labels: release-updates

#5639 [oracle-linux] Update link to avoid redirects
  products/oracle-linux.md
Labels: chore

#5642 Update contributing guide link in the README
  README.md
Labels: documentation

#5649 [linuxkernel] Update 6.9 eol
  products/linuxkernel.md
Labels: release-updates

#5650 [mssqlserver] Update 2019 CU28
  products/mssqlserver.md
Labels: release-updates

#5635 Add Rails 7.2, explain new EOL policy, and update EOL dates
  products/ruby-on-rails.md
Labels: release-updates, product-fixes

#5645 [rocket-chat] add 6.11
  products/rocket-chat.md
Labels: release-updates

#5654 [kubernetes] add 1.31 release
  products/kubernetes.md
Labels: release-updates

#5648 [pan-os]Update PAN-OS version(s)
  products/pan-os.md
Labels: release-updates

#5657 Revert "Bump just-the-docs from 0.8.2 to 0.9.0"
  Gemfile
  Gemfile.lock
Labels: bug, dependencies, ruby

#5594 [new product] Chef InSpec
  products/chef-inspec.md
Labels: new-product

#5669 [visualstudio] add 17.11
  products/visualstudio.md
Labels: release-updates

#5666 [apache-apisix] add 3.10
  products/apache-apisix.md
Labels: release-updates, auto

#5658 [mattermost] Switch to github_releases auto method
  products/mattermost.md
Labels: auto

#5672 Update zerto.md
  products/zerto.md
Labels: release-updates

#5670 [cockroachdb] Adds 24.2 and new policy
  products/cockroachdb.md
Labels: release-updates, product-fixes

#5676 Add new 'discontinued' tag
  _layouts/product.html
  products/angularjs.md
  products/centos.md
  products/google-nexus.md
  products/isc-dhcp.md
Labels: enhancement

#5677 [pan-os] Update auto configuration
  products/pan-os.md
Labels: auto

#5182 [new product] Add Zentyal
  products/zentyal.md
Labels: new-product

#5679 [dce] Update latest 5.0
  products/dce.md
Labels: release-updates

#5680 [filemaker] Automate release date and EOL retrieval
  products/filemaker.md
Labels: release-updates

#5678 [azul-zulu] Update latest releases
  products/azul-zulu.md
Labels: release-updates

#5682 [lua] Automate release and version retrieval
  products/lua.md
Labels: auto

#5688 [godot] Add 4.3
  products/godot.md
Labels: release-updates

#5690 [istio] Add 1.23
  products/istio.md
Labels: release-updates

#5686 [gitlab] Add 17.3
  products/gitlab.md
Labels: release-updates

#5687 [contao] Add 5.4
  products/contao.md
Labels: release-updates

#5681 [kindle] Update latest releases
  products/kindle.md
Labels: release-updates

#5674 [centos] Update description
  products/centos.md
Labels: product-updates

#5685 [unity] Update latest releases
  products/unity.md
Labels: release-updates

#5697 [apache-hop] Switch to maven method for automation
  products/apache-hop.md
Labels: auto

#5698 [mariadb] Automate release date and EOL retrieval
  products/mariadb.md
Labels: auto

#5693 [scala] update to use github_releases
  products/scala.md
Labels: auto

#5694 various: syntax updates
  products/amazon-corretto.md
  products/bellsoft-liberica.md
  products/eclipse-temurin.md
  products/ibm-semeru.md
  products/keycloak.md
  products/sapmachine.md
Labels: chore

#5699 [angular] Automate releaseDate, eoas and eol retrieval
  products/angular.md
Labels: auto

#5118 [new product] Control-M
  products/controlm.md
Labels: new-product

#5705 [mariadb] Add 11.5.x
  products/mariadb.md
Labels: release-updates

#5703 [filemaker] add 2024
  products/filemaker.md
Labels: release-updates

#5702 [looker] add 24.14
  products/looker.md
Labels: release-updates

#5709 [controlm] Fix cpe identififer
  products/controlm.md
Labels: bug

#5712 [citrix-apps-desktops] Add 2407
  products/citrix-apps-desktops.md
Labels: release-updates

#5713 [mssharepoint] Update subscription, 2019
  products/mssharepoint.md
Labels: release-updates

#5700 [new product] jQuery UI
  products/jquery-ui.md
Labels: new-product

#5717 [vault] Document LTS releases
  products/hashicorp-vault.md
Labels: product-fixes

#5718 [citrix-apps-desktops] Update 2402 CU1
  products/citrix-apps-desktops.md
Labels: release-updates

#5727 Update windows.md fixed releaseDate for 10-1903
  products/windows.md
Labels: product-fixes

#5724 [electron] add 32
  products/electron.md
Labels: release-updates

#5729 Update windows.md 10-1803-w EOL date
  products/windows.md
Labels: product-fixes

#5725 [numpy] add 2.1
  products/numpy.md
Labels: release-updates

#5723 [clamav] add 1.4
  products/clamav.md
Labels: release-updates

#5726 [weechat] add 4.4
  products/weechat.md
Labels: release-updates

#5719 [jenkins] Add 2.462 LTS
  products/jenkins.md
Labels: release-updates

#5728 [nvidia-driver] Add R560 Release
  products/nvidia-driver.md
Labels: release-updates

#5599 [gke] Add 1.30
  products/gke.md
Labels: release-updates

#5741 [scala] Add 3.5
  products/scala.md
Labels: release-updates

#5745 [embersj] Fix auto configuration
  products/emberjs.md
Labels: auto

#5744 [kubernetes-csi-node-driver-registrar] add 2.12
  products/kubernetes-csi-node-driver-registrar.md
Labels: release-updates

#5742 [neo4j] add 5.23
  products/neo4j.md
Labels: release-updates

#5743 [jira] add 10
  products/jira.md
Labels: release-updates

#5730 Update windows.md
  products/windows.md
Labels: release-updates

#5748 [meilisearch] add 1.10
  products/meilisearch.md
Labels: release-updates

#5758 [tarantool] add 3.2
  products/tarantool.md
Labels: release-updates

#5763 [wireshark] add 4.4
  products/wireshark.md
Labels: release-updates

#5764 [gradle] update compatibility matrix for 8.10
  products/gradle.md
Labels: release-updates
