Repository endoflife-date/endoflife.date, pull requests merged in 2024-07, with the labels that each got.

#5303 [new product] dce
  products/dce.md
Labels: new-product

#5389 [k8s] Drop releaseImage
  products/kubernetes.md
Labels: bug

#5385 [vue] Remove incorrect repology identifier
  products/vue.md
Labels: product-fixes

#5355 [bazel] Adds Identifiers
  products/bazel.md
Labels: product-fixes

#5396 [rabbitmq] Correct EOL for 3.13
  products/rabbitmq.md
Labels: product-fixes

#5393 Update EOL date for elasticsearch 8
  products/elasticsearch.md
Labels: product-fixes

#5400 [netbsd] netbsd 8.x
  products/netbsd.md
Labels: release-updates

#5295 [new product] Harbor OSS
  products/harbor.md
  products/vmware-harbor-registry.md
Labels: new-product

#5407 [vue] Fix YAML
  products/vue.md
Labels: bug

#5403 [centreon] Document upcoming release policy
  _config.yml
  products/centreon.md
Labels: product-fixes

#5412 [electron] Remove empty lines
  products/electron.md
Labels: chore

#5410 Add SLES 15 SP6 release information
  products/sles.md
Labels: release-updates

#5413 [rocket-chat] Fix auto configuration
  products/rocket-chat.md
Labels: product-updates

#5392 [rocket-chat] General Updates
  products/rocket-chat.md
Labels: product-fixes

#5301 Fix product identifiers
  products/apache-http-server.md
  products/citrix-apps-desktops.md
  products/intel-processors.md
  products/internet-explorer.md
  products/mule-runtime.md
  products/nvidia-driver.md
  products/nvidia-products.md
  products/pan-gp.md
  products/pan-os.md
  products/raspberrypi.md
  products/red-hat-build-of-openjdk.md
  products/red-hat-jboss-eap.md
  products/red-hat-satellite.md
  products/rhel.md
  products/vmware-esxi.md
  products/windows-embedded.md
  products/windows-server.md
Labels: product-fixes

#5415 Update Ruby dependencies
  Gemfile.lock
Labels: dependencies, ruby

#5416 [alpinelinux] Update identifiers
  products/alpinelinux.md
Labels: product-updates

#5417 [antixlinux] Drop identifiers
  products/antixlinux.md
Labels: product-updates

#5418 [bellsoft-liberica] Fix identifiers
  products/bellsoft-liberica.md
Labels: product-fixes

#5419 [cfengine] Fix identifier
  products/cfengine.md
Labels: product-fixes

#5420 [devuan] Drop identifiers
  products/devuan.md
Labels: product-fixes

#5422 [mariadb] Fix identifiers
  products/mariadb.md
Labels: product-fixes

#5423 [mxlinux] Drop identifiers
  products/mxlinux.md
Labels: product-fixes

#5424 [mysql] Remove wrong identifier
  products/mysql.md
Labels: product-fixes

#5425 [nginx] Fix identifier
  products/nginx.md
Labels: product-fixes

#5426 [node-feature-discovery] Fix identifier
  products/node-feature-discovery.md
Labels: product-fixes

#5427 [red-hat-build-of-openjdk] Fix identifiers
  products/red-hat-build-of-openjdk.md
Labels: product-fixes

#5428 [vmware-photon] Fix identifiers
  products/vmware-photon.md
Labels: product-fixes

#5421 [dotnet] Fix identifiers
  products/dotnet.md
Labels: product-fixes

#5429 Regenerate Gemfile.lock
  Gemfile.lock
Labels: dependencies, ruby

#5414 [mattermost] Fix auto configuration
  products/mattermost.md
Labels: product-updates, auto

#5444 [firefox] Add 128
  products/firefox.md
Labels: release-updates

#5445 [fluent-bit] Add 3.1
  products/fluent-bit.md
Labels: release-updates

#5447 [freebsd] Upcoming release policy change
  products/freebsd.md
Labels: product-updates

#5440 [mssharepoint] Update latest Subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#5438 [mssqlserver] 2022 CU13 GDR, 2019 CU27 GDR, 2017 CU31 GDR, 2016 SP3 GDR, Add 2014 eoes
  products/mssqlserver.md
Labels: release-updates

#5449 [squid] Update auto configuration
  products/squid.md
Labels: auto

#5434 Update eurolinux.md
  products/eurolinux.md
Labels: product-updates

#5453 [exim] Add 4.98
  products/exim.md
Labels: release-updates

#5452 [emberjs] Add 5.10
  products/emberjs.md
Labels: release-updates

#5457 [azure-devops] Add 2022.2
  products/azure-devops.md
Labels: release-updates

#5460 [linuxkernel] Add 6.10
  products/linuxkernel.md
Labels: release-updates

#5471 [gitlab] Add 17.2
  products/gitlab.md
Labels: release-updates

#4388 [new product] chef-infra-client
  products/chef-infra-client.md
Labels: new-product

#5472 [vue] Drop anchors
  products/vue.md
Labels: product-fixes

#5473 [rocket-chat] Update auto configuration
  products/rocket-chat.md
Labels: product-updates

#5479 [traefik] Automate release date and EOL retrieval
  products/traefik.md
Labels: auto

#5480 Update Ruby dependencies
  Gemfile.lock
Labels: dependencies, ruby

#5356 [products] Show Identifiers in product pages
  Gemfile
  Gemfile.lock
  _includes/identifiers.html
  _layouts/product.html
  _plugins/end-of-life-filters.rb
  _plugins/identifier-to-url.rb
  _plugins/product-data-validator.rb
  products/node-feature-discovery.md
  products/phpmyadmin.md
Labels: enhancement

#5481 Validate CPE 2.2 and 2.3 identifiers
  _plugins/identifier-to-url.rb
Labels: enhancement

#5504 Add a few websites to the ignore list in product-data-validator.rb
  _plugins/product-data-validator.rb
Labels: chore

#3796 [oneplus] Add OnePlus devices
  products/oneplus.md
Labels: new-product

#5499 Update apache-activemq.md
  products/apache-activemq.md
Labels: release-updates

#5502 [eclipse-jetty] Update a few links
  products/eclipse-jetty.md
Labels: product-updates

#5503 [harbor] Update changelogTemplate
  products/harbor.md
Labels: product-updates

#5501 [opensuse] Fix broken links
  products/opensuse.md
Labels: release-updates

#5506 [chef-infra-client] Fix support column
  products/chef-infra-client.md
Labels: product-fixes

#5512 [unity] Add 6, update 2022.3
  products/unity.md
Labels: release-updates

#5511 [mysql] Add 9
  products/mysql.md
Labels: release-updates

#5500 [exim] Fix 4.98
  products/exim.md
Labels: product-fixes

#5498 [vue] Fix release cycles order
  products/vue.md
Labels: product-fixes

#5497 [sles] Fix release cycles order
  products/sles.md
Labels: product-fixes

#5495 [shopware] Fix release cycles order
  products/shopware.md
Labels: product-fixes

#5494 [red-hat-satellite] Fix 6.14 release date
  products/red-hat-satellite.md
Labels: release-updates

#5493 [python] Fix release cycles order
  products/python.md
Labels: product-fixes

#5490 [kyverno] Fix 1.9 releaseDate
  products/kyverno.md
Labels: release-updates

#5489 [google-nexus] Fix release cycles order
  products/google-nexus.md
Labels: product-fixes

#5487 [eclipse-temurin] Fix release cycles order
  products/eclipse-temurin.md
Labels: product-fixes

#5484 [azul-zulu] Fix release cycles order
  products/azul-zulu.md
Labels: product-fixes

#5483 [amazon-neptune] Fix release cycles order
  products/amazon-neptune.md
Labels: product-fixes

#5485 [bellsoft-liberica] Fix 8 release date
  products/bellsoft-liberica.md
Labels: release-updates

#5486 [couchbase-server] Fix 7.6 release date
  products/couchbase-server.md
Labels: release-updates

#5478 [traefik] Add 3.1
  products/traefik.md
Labels: release-updates

#5477 [envoy] Add 1.31
  products/envoy.md
Labels: release-updates

#5476 [blender] Add 4.2
  products/blender.md
Labels: release-updates

#5454 [looker] Add 24.12
  products/looker.md
Labels: release-updates, product-updates

#5455 [mattermost] Add 9.10
  products/mattermost.md
Labels: release-updates

#5475 [apache-camel] Add 4.7
  products/apache-camel.md
Labels: release-updates

#5514 [ffmpeg] Update 6.0, 4.1 eol
  products/ffmpeg.md
Labels: release-updates

#5515 [mysql] Update eoas/eol for 8.3, 8.2, Update dates remarks
  products/mysql.md
Labels: release-updates

#5348 [new product] Add Vision OS
  products/visionos.md
Labels: new-product

#5062 [new product] pnpm
  products/pnpm.md
Labels: new-product

#5491 [mssqlserver] Fix 12.0 and 13.0 release dates
  products/mssqlserver.md
Labels: release-updates

#5492 [office] Fix release dates
  products/office.md
Labels: release-updates

#5519 [mssqlserver] Update 2022 CU14
  products/mssqlserver.md
Labels: release-updates

#4440 [new product] wireshark
  products/wireshark.md
Labels: new-product

#5430 [nvidia-driver] Add R555 and update latest releases
  products/nvidia-driver.md
Labels: release-updates

#5520 [vmware-vcenter] Update 8.0 U3a
  products/vmware-vcenter.md
Labels: release-updates

#5522 [rocket-chat] Add 6.10
  products/rocket-chat.md
Labels: release-updates

#4394 Rework nexus repo
  products/nexus.md
Labels: product-updates

#5524 [wireshark] Fix auto configuration
  products/wireshark.md
Labels: product-fixes

#5527 [nexus] Fix releases and adjust auto configuration
  products/nexus.md
Labels: release-updates, auto

#5532 [opnsense] Add 24.7, update eol 24.1
  products/opnsense.md
Labels: release-updates

#5531 [linuxmint] Add 22
  products/linuxmint.md
Labels: release-updates

#5530 [artifactory] Add 7.90
  products/artifactory.md
Labels: release-updates

#5537 [neo4j] Automate releaseDate and EOL retrieval
  products/neo4j.md
Labels: auto

#5237 [new product] OpenVPN
  products/openvpn.md
Labels: new-product

#4428 [new product] icinga
  products/icinga-web.md
  products/icinga.md
Labels: new-product

#5539 Fix CONTRIBUTING documentation
  CONTRIBUTING.md
Labels: documentation

#3961 Add a validation rule to make sure releases are properly ordered
  _plugins/product-data-validator.rb
  products/hbase.md
  products/ibm-aix.md
  products/ibm-i.md
  products/jenkins.md
  products/log4j.md
  products/nutanix-aos.md
  products/nutanix-files.md
  products/office.md
Labels: enhancement

#4657 [new product] privatebin
  products/privatebin.md
Labels: new-product

#4827 [new product] mautic
  products/mautic.md
Labels: new-product

#5536 [neo4j] Add 5.22
  products/neo4j.md
Labels: release-updates

#5541 Update centos.md
  products/centos.md
Labels: product-fixes

#4903 Update angularjs.md
  products/angularjs.md
Labels: product-updates

#4998 [samsungmobile] Add Galaxy Tab S9 variants
  products/samsungmobile.md
Labels: release-updates

#5542 [samsungmobile] Fix order
  products/samsungmobile.md
Labels: product-fixes

#5354 docs: Adds new page asking for help on identifiers
  CONTRIBUTING.md
  pages/help/identifiers-needed.md
Labels: community, documentation

#5550 [splunk] Add 9.3
  products/splunk.md
Labels: release-updates

#5547 [nix] Update changelogTemplate
  products/nix.md
Labels: product-updates

#5546 [godot] Update changelogTemplate
  products/godot.md
Labels: product-updates

#5545 [bun] Update changelogTemplate
  products/bun.md
Labels: product-updates

#5544 [prometheus] Rollback latest 2.52 to 2.52.0
  products/prometheus.md
Labels: release-updates

#5543 [oracle-database] Update links
  products/oracle-database.md
Labels: release-updates

#5549 [apache-kafka] Add 3.8
  products/apache-kafka.md
Labels: release-updates

#5556 [debian] update eol for 11
  products/debian.md
Labels: release-updates

#5553 [Update] Amazon RDS Extended Support for MySQL and PostgreSQL
  products/amazon-rds-mysql.md
  products/amazon-rds-postgresql.md
Labels: release-updates
