Repository endoflife-date/endoflife.date, pull requests merged in 2024-06, with the labels that each got.

#5240 [freebsd] Adds 14.1 release
  products/freebsd.md
Labels: release-updates

#5245 [ansible] add 10.x and eol for 9.x
  products/ansible.md
Labels: release-updates

#5247 [citrix-apps-desktops] Update 2203 CU5
  products/citrix-apps-desktops.md
Labels: release-updates

#5246 [zabbix] Add 7.0
  products/zabbix.md
Labels: release-updates

#5253 [cert-manager] add cert-manager 1.15 release
  products/cert-manager.md
Labels: release-updates

#5252 [Harbor] add new 2.11 release
  products/vmware-harbor-registry.md
Labels: release-updates

#5255 [solr] Add EOL versions v1, v3, v4, v5, v6, v7
  products/solr.md
Labels: release-updates

#5242 [activemq] Mark unsupported releases
  products/apache-activemq.md
Labels: release-updates

#5257 [new product] add neos
  products/neos.md
Labels: new-product

#5020 [electron] Adds v31
  products/electron.md
Labels: release-updates

#5265 [Firefox] Add 127.0
  products/firefox.md
Labels: release-updates

#5264 [MariaDB] Set EOL for 11.3
  products/mariadb.md
Labels: release-updates

#5270 [Electron] Add chromium and node info and bump version
  products/electron.md
Labels: release-updates

#5274 [azure-devops] Update 2022.1patch4
  products/azure-devops.md
Labels: release-updates

#5275 [mssharepoint] Update latest subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#5269 [Debian] Add historical Debian releases
  products/debian.md
Labels: release-updates

#5204 [angular] drop `lts` for all release lines
  products/angular.md
Labels: product-updates

#5276 [mssqlserver] Update 2019 CU27
  products/mssqlserver.md
Labels: release-updates

#5278 [rust] add 1.79
  products/rust.md
Labels: release-updates

#5284 [hashicorp-vault] Add 1.17
  products/hashicorp-vault.md
Labels: release-updates

#5285 [keycloak] Add 25.0
  products/keycloak.md
Labels: release-updates

#5283 [emberjs] Add 5.9
  products/emberjs.md
Labels: release-updates

#5282 [elixir] Add 1.17
  products/elixir.md
Labels: release-updates

#5281 [consul] Add 1.19
  products/consul.md
Labels: release-updates

#5290 [nix] Add 2.23
  products/nix.md
Labels: release-updates

#5289 [neo4j] Add 4.19 and 4.20
  products/neo4j.md
Labels: release-updates

#5293 [telegraf] Add 1.31
  products/telegraf.md
Labels: release-updates

#5292 [rocket-chat] Add 6.9
  products/rocket-chat.md
Labels: release-updates

#5288 [mediawiki] Add 1.42
  products/mediawiki.md
Labels: release-updates

#5286 [looker] Add 24.10
  products/looker.md
Labels: release-updates

#5287 [mattermost] Add 9.9
  products/mattermost.md
Labels: release-updates

#5280 [amazon-neptune] Add 1.3.0.0, 1.3.1.0 and 1.3.2.0
  products/amazon-neptune.md
Labels: release-updates

#5291 [perl] Add 5.40
  products/perl.md
Labels: release-updates

#5299 Update Ruby version to 3.3 for check-links.yml
  .github/workflows/check-links.yml
Labels: bug

#5297 [envoy] Adds more identifiers
  products/envoy.md
Labels: product-fixes

#5298 [airflow] Adds container image identifiers
  products/apache-airflow.md
Labels: product-updates

#5305 [numpy] 2.0 Release
  products/numpy.md
Labels: release-updates

#5311 [oracle-apex] Adds 24.1
  products/oracle-apex.md
Labels: release-updates

#5327 [electron] Automate releaseDate retrieval
  products/electron.md
Labels: release-updates

#5330 [gitlab] Automate releaseDate retrieval
  products/gitlab.md
Labels: auto

#5331 [coldfusion] Disable automatic versions retrieval
  products/coldfusion.md
Labels: auto

#5332 [spring-boot] Fix auto configuration
  products/spring-boot.md
Labels: auto

#5333 [spring-framework] Fix auto configuration
  products/spring-framework.md
Labels: auto

#5334 [apache-flink] Fix auto configuration
  products/apache-flink.md
Labels: auto

#5335 [unity] Disable automatic versions retrieval
  products/unity.md
Labels: auto

#5336 Update coldfusion 2023 and 2021
  products/coldfusion.md
Labels: release-updates

#5344 [libreoffice] Set up automation
  products/libreoffice.md
Labels: product-updates, auto

#5328 [gitlab] Add 17.1
  products/gitlab.md
Labels: release-updates

#5340 [opensuse] Fix links
  products/opensuse.md
Labels: product-updates

#5342 [oracle-apex] Fix changelogTemplate
  products/oracle-apex.md
Labels: product-fixes

#5325 [amazon-neptune] Add 1.3.2.1
  products/amazon-neptune.md
Labels: release-updates

#5339 [veeam-backup-and-replication] Update product page link
  products/veeam-backup-and-replication.md
Labels: release-updates

#5341 [solr] Fix 1 and 3 links
  products/solr.md
Labels: product-fixes

#5326 [drupal] Add 10.3
  products/drupal.md
Labels: release-updates

#5329 [kdeplasma] Add 6.1
  products/kdeplasma.md
Labels: release-updates

#5338 [erlang] Fix latest for 27
  products/erlang.md
Labels: product-fixes

#5313 [prometheus] Adds 2.53 - Check on July 2
  products/prometheus.md
Labels: release-updates

#5302 [bellsoft-liberica] Adds more identifiers
  products/bellsoft-liberica.md
Labels: product-fixes

#5357 [vmware-esxi] Update 8.0 Update 3
  products/vmware-esxi.md
Labels: release-updates

#5323 [new product] Microsoft Nano Server, Microsoft Windows Server Core
  products/windows-nano-server.md
  products/windows-server-core.md
  products/windowsServer.md
Labels: new-product
