Repository endoflife-date/endoflife.date, pull requests merged in 2024-12, with the labels that each got.

#6314 [rust] add 1.83
  products/rust.md
Labels: release-updates

#6095 [samsungmobile] Add Galaxy A15 and A25
  products/samsungmobile.md
Labels: release-updates

#6315 [azure-devops] Update 2022.2patch2, 2020.1.2patch14
  products/azure-devops.md
Labels: release-updates

#6316 [citrix-apps-desktops] Update 1912 CU10
  products/citrix-apps-desktops.md
Labels: release-updates

#6321 [tarantool] add 3.3
  products/tarantool.md
Labels: release-updates

#6320 [svelte] add 5.3,5.4
  products/svelte.md
Labels: release-updates

#6326 [svelte] Update changelogTemplate
  products/svelte.md
Labels: product-updates

#6330 [Oracle Database] 23ai updated Premier Support
  products/oracle-database.md
Labels: product-fixes

#6337 [amazon-corretto] Fix callout
  products/amazon-corretto.md
Labels: bug

#6335 [svelte] Split policy from description
  products/svelte.md
Labels: product-updates

#6339 [svelte] Merge minor release cycles to major
  products/svelte.md
Labels: product-fixes

#6348 [linuxkernel] Update 6.11 eol, 4.19 eol
  products/linuxkernel.md
Labels: release-updates

#6349 [linux] 6.12 became LTS
  products/linuxkernel.md
Labels: release-updates, product-fixes

#6168 [new product] add nvm
  products/nvm.md
Labels: new-product

#6352 [spring-boot] Fix auto configuration
  products/spring-boot.md
Labels: auto

#6353 [spring-framework] Fix auto configuration
  products/spring-framework.md
Labels: auto

#6218 Update quarkus.md
  products/quarkus.md
Labels: release-updates

#6216 [rhel] update latest release for 9.x
  products/rhel.md
Labels: release-updates

#6101 [apache struts] adding purl identifier
  products/apache-struts.md
Labels: release-updates

#6104 [pnpm] add purl identifiers
  products/pnpm.md
Labels: release-updates

#6099 Remove the outdated release schedule for Chef Infra Client
  products/chef-infra-client.md
Labels: product-updates

#5953 [vault] EOL 1.16 and 1.17 from standard maintenance
  products/hashicorp-vault.md
Labels: product-updates

#6364 [rocket-chat] Add 7.1
  products/rocket-chat.md
Labels: release-updates

#6363 [react] Add 19.0
  products/react.md
Labels: release-updates

#6362 [nutanix-prism] Add pc.2024.3
  products/nutanix-prism.md
Labels: release-updates

#6361 [nutanix-aos] Add 7.0
  products/nutanix-aos.md
Labels: release-updates

#6360 [jira] Add 10.3
  products/jira.md
Labels: release-updates

#6358 [aws-lambda] Add Python 3.13 and Node 22
  products/aws-lambda.md
Labels: release-updates

#6357 [apache-camel] Add 4.9, set 4.8 and 4.7 EOL
  products/apache-camel.md
Labels: release-updates

#6359 [grafana] Add 11.4
  products/grafana.md
Labels: release-updates

#6356 [alpinelinux] Add 3.21
  products/alpinelinux.md
Labels: release-updates

#6377 [kuma] Disable custom auto method
  products/kuma.md
Labels: auto

#6373 [bazel] Add 8
  products/bazel.md
Labels: release-updates

#6376 [docker-engine] Add 27.4
  products/docker-engine.md
Labels: release-updates

#6382 [zabbix] Add 7.2
  products/zabbix.md
Labels: release-updates

#6369 [zerto] Add 10.0 Update 6
  products/zerto.md
Labels: release-updates

#6386 [confluence] add 9.2
  products/confluence.md
Labels: release-updates

#6385 [apache-hop] add 2.11
  products/apache-hop.md
Labels: release-updates

#6389 [scala] add 3.6
  products/scala.md
Labels: release-updates

#6388 [numpy] add 2.2
  products/numpy.md
Labels: release-updates

#6387 [neo4j] add 5.26
  products/neo4j.md
Labels: release-updates

#6390 [telegraf] add 1.33
  products/telegraf.md
Labels: release-updates

#6399 [kubernetes] add 1.32 release
  products/kubernetes.md
Labels: release-updates

#6400 [linux] Update Release image
  products/linuxkernel.md
Labels: product-fixes

#6403 [pan-os]Update PAN-OS version(s)
  products/pan-os.md
Labels: release-updates

#6412 [citrix-apps-desktops] Add 2411
  products/citrix-apps-desktops.md
Labels: release-updates

#6409 [plesk] Add 18.0.66
  products/plesk.md
Labels: release-updates

#6408 [kong-gateway] Add 3.9, update 3.8 eol
  products/kong-gateway.md
Labels: release-updates

#6407 [ibm-aix] Add 7.3.3
  products/ibm-aix.md
Labels: release-updates

#6405 [mssqlserver] Update 2019 CU30
  products/mssqlserver.md
Labels: release-updates

#6404 [mssharepoint] Update latest subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#5787 [windows-server] Add 2003 - and 2003sp1
  products/windows-server.md
Labels: release-updates

#6140 [filemaker] update 19.x
  products/filemaker.md
Labels: release-updates

#3992 [mssqlserver] Add all SP cycles
  products/mssqlserver.md
Labels: release-updates

#6425 [python] 3.13 is released, so 2+3 policy is live
  products/python.md
Labels: product-updates

#6413 [almalinux] update details
  products/almalinux.md
Labels: release-updates

#6429 [doc] Fix purl-spec link
  pages/help/identifiers-needed.md
Labels: bug

#6430 [linux] 6.1 LTS's time recieved +1 year
  products/linuxkernel.md
Labels: product-fixes

#6431 [drupal] add 11.1 and eol update for 11.0
  products/drupal.md
Labels: release-updates

#6432 [mattermost] add 10.3
  products/mattermost.md
Labels: release-updates

#6433 [splunk] add 9.4
  products/splunk.md
Labels: release-updates

#6434 [weechat] add 4.5 and eol for 4.4
  products/weechat.md
Labels: release-updates

#6441 [Solr] Fix eol date for v8.x
  products/solr.md
Labels: release-updates

#6439 [hashicorp-vault] Fix EOL date for 1.16
  products/hashicorp-vault.md
Labels: release-updates

#6450 [visionos] Update EOL for visionOS 1
  products/visionos.md
Labels: release-updates

#6443 [amazon-linux] Fix EOL date
  products/amazon-linux.md
Labels: release-updates

#6464 [apache-struts] Adds v7
  products/apache-struts.md
Labels: release-updates

#6465 [neptune] Adds 1.4.2.0
  products/amazon-neptune.md
Labels: release-updates

#6462 [elixir] 1.18 release
  products/elixir.md
Labels: release-updates

#6463 [mediawiki] Adds 1.43
  products/mediawiki.md
Labels: release-updates

#6454 [nextjs] Update v13 EOL
  products/nextjs.md
Labels: release-updates

#6461 [drupal] Adds 10.4
  products/drupal.md
Labels: release-updates

#6468 [ruby] Adds 3.4.0
  products/ruby.md
Labels: release-updates

#6287 [new product] GHC (Glasgow Haskell Compiler)
  products/ghc.md
Labels: new-product

#6455 [ios] Mark 16 and 17 as EOL
  products/ios.md
Labels: product-fixes

#6457 [pan-gp]Updated GlobalProtect App to version 6.3.2
  products/pan-gp.md
Labels: release-updates

#6474 [artifactory] update 7.98 (7.98.12)
  products/artifactory.md
Labels: release-updates

#6477 [nexus] Add 2.15.2-03
  products/nexus.md
Labels: release-updates

#6473 [chef] Add the latest Chef Infra Client 17.x and 18.x releases
  products/chef-infra-client.md
Labels: release-updates

#6470 [keda] Correct 2.16 supported k8s versions
  products/keda.md
Labels: product-fixes

#6480 [kubernetes-csi-node-driver-registrar] add 2.13
  products/kubernetes-csi-node-driver-registrar.md
Labels: release-updates

#6485 [postmarketos] add 24.12, update 24.06 eol
  products/postmarketos.md
Labels: release-updates

#6484 [nutanix-files] add 5.1
  products/nutanix-files.md
Labels: release-updates

#6483 [node-feature-discovery] add 0.17 and update auto
  products/node-feature-discovery.md
Labels: release-updates, auto

#6482 [meilisearch] add 1.12 and use `github_releases` instead of `tag`
  products/meilisearch.md
Labels: release-updates, auto
