Repository endoflife-date/endoflife.date, pull requests merged in 2024-04, with the labels that each got.

#4925 [apache-airflow] Fix auto-configuration
  products/apache-airflow.md
Labels: product-updates

#4927 [keycloak] Set up icon
  products/keycloak.md
Labels: product-updates

#4941 Remove unnecessary empty lines introduce bu the automation
  products/mattermost.md
  products/rabbitmq.md
Labels: chore

#4942 [oracle-jdk] Set render_javascript_wait_until
  products/oracle-jdk.md
Labels: chore

#4943 [spring-framework][spring-boot] Set render_javascript_wait_until: networkidle
  products/spring-boot.md
  products/spring-framework.md
Labels: chore

#4940 [qt] Add 6.7
  products/qt.md
Labels: release-updates

#4938 [confluence] Add 8.9
  products/confluence.md
Labels: release-updates

#4939 [mongodb] Add 7.3
  products/mongodb.md
Labels: release-updates

#4951 [wordpress] Add 6.5
  products/wordpress.md
Labels: release-updates

#4950 [plesk] Add 18.0.60
  products/plesk.md
Labels: release-updates

#4948 [nvidiadriver] Add R550, R545, Linux R520, and update latest releases
  products/nvidiadriver.md
Labels: release-updates

#4957 [mariadb] Update 11.3 eol and lts
  products/mariadb.md
Labels: product-updates

#4958 [redis] license change
  products/redis.md
Labels: product-fixes

#4914 [new product] Sourcegraph
  products/sourcegraph.md
Labels: new-product

#4960 [aws-lambda] Add Ruby 3.3
  products/aws-lambda.md
Labels: release-updates

#4968 [mssqlserver] Update 2022 CU12+GDR, 2019 CU25+GDR
  products/mssqlserver.md
Labels: release-updates

#4969 [mssharepoint] Update latest for subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#4964 [scala] Upgrade JDK compatibility
  products/scala.md
Labels: product-updates

#4974 [openssl] add 3.3.x
  products/openssl.md
Labels: release-updates

#4983 [mssqlserver] 2019 CU26
  products/mssqlserver.md
Labels: release-updates

#4982 [pan-gp]Updated GlobalProtect to 6.2.3
  products/pan-gp.md
Labels: release-updates

#4980 [terraform] Add 1.8
  products/terraform.md
Labels: release-updates

#4979 [rocket-chat] Add 6.7
  products/rocket-chat.md
Labels: release-updates

#4978 [magento] Add 2.4.7
  products/magento.md
Labels: release-updates

#4977 [looker] Add 24.6
  products/looker.md
Labels: release-updates

#4981 Ruby: Change EOL policy link
  products/ruby.md
Labels: product-updates

#4993 [linuxkernel] Update 6.7 eol
  products/linuxkernel.md
Labels: release-updates

#4996 [mattermost] Add 9.7
  products/mattermost.md
Labels: release-updates

#4991 [citrix-apps-desktops] Add 2402 LTS, Update 2311 eoas, eol
  products/citrix-apps-desktops.md
Labels: release-updates

#4997 [silverstripe] Add 5.2
  products/silverstripe.md
Labels: release-updates

#5001 [tarantool] Add 3.1
  products/tarantool.md
Labels: release-updates

#5011 [cos] Add 113
  products/cos.md
Labels: release-updates

#5023 [moodle] Adds 4.4
  products/moodle.md
Labels: release-updates

#5028 [robo] Adds 5.0
  products/robo.md
Labels: release-updates

#5034 [msexchange] Update 2019 CU14 HU2, 2016 CU23 HU13
  products/msexchange.md
Labels: release-updates

#5040 [nextcloud] Add 29
  products/nextcloud.md
Labels: release-updates

#5060 [redhat-satellite] Add 6.15
  products/redhat-satellite.md
Labels: release-updates

#5059 [pan-cortex-xdr] Add 8.4
  products/pan-cortex-xdr.md
Labels: release-updates

#5058 [nix] Ad 2.22
  products/nix.md
Labels: release-updates

#5057 [keda] Add 2.14
  products/keda.md
Labels: release-updates

#5056 [docker-engine] Add 26.1
  products/docker-engine.md
Labels: release-updates

#5052 [react] Add 18.3
  products/react.md
Labels: release-updates

#5015 [new-product]: fluent-bit
  products/fluent-bit.md
Labels: new-product

#5061 [oracle-linux] Update extended support
  products/oracle-linux.md
Labels: product-fixes

#5054 [netbsd] Add 10
  products/netbsd.md
Labels: release-updates
