Repository endoflife-date/endoflife.date, pull requests merged in 2024-03, with the labels that each got.

#4724 [ibm-aix] Automate EOL retrieval
  products/ibm-aix.md
Labels: product-updates

#4725 [ibm-i] Normalize page
  products/ibm-i.md
Labels: chore

#4726 Update release_table configuration for all products
  products/akeneo-pim.md
  products/alibaba-dragonwell.md
  products/alpinelinux.md
  products/amazon-corretto.md
  products/amazon-neptune.md
  products/amazon-rds-mysql.md
  products/amazon-rds-postgresql.md
  products/apache-airflow.md
  products/apache-kafka.md
  products/bazel.md
  products/couchbase-server.md
  products/craft-cms.md
  products/debian.md
  products/django.md
  products/dotnet.md
  products/dotnetfx.md
  products/eclipse-temurin.md
  products/eks.md
  products/electron.md
  products/emberjs.md
  products/envoy.md
  products/ibm-aix.md
  products/pan-cortex-xdr.md
  products/pan-gp.md
  products/pan-os.md
  products/rocket-chat.md
Labels: chore

#4727 Suppress errors in product-data-validator.rb for a few links
  _plugins/product-data-validator.rb
Labels: chore

#4730 [ibm-i] Automate releaseDate, eol and extendedSupport retrieval
  products/ibm-i.md
Labels: product-updates

#4731 [ibm-semeru] Automate LTS eol retrieval
  products/ibm-semeru.md
Labels: product-updates

#4732 [istio] Automate eol and supportedKubernetesVersions retrieval
  products/istio.md
Labels: product-updates

#4733 [laravel] Automate support, eol and supportedPhpVersions retrieval
  products/laravel.md
Labels: product-updates

#4734 [linuxmint] Automate eol retrieval
  products/linuxmint.md
Labels: product-updates

#4735 [mattermost] Automate eol retrieval
  products/mattermost.md
Labels: product-updates

#4736 [mediawiki] Automate releaseDate and eol retrieval
  products/mediawiki.md
Labels: product-updates

#4738 [microsoft-build-of-openjdk] Automate eol retrieval
  products/microsoft-build-of-openjdk.md
Labels: product-updates

#4739 [mongodb] Automate eol retrieval
  products/mongodb.md
Labels: product-updates

#4740 [moodle] Automate support and eol retrieval
  products/moodle.md
Labels: product-updates

#4742 [nextcloud] Automate releaseDate and eol retrieval
  products/nextcloud.md
Labels: release-updates

#4748 Update nutanix products auto configuration
  products/nutanix-aos.md
  products/nutanix-files.md
  products/nutanix-prism.md
Labels: chore

#4749 [nuxt] Automate EOL retrieval
  products/nuxt.md
Labels: product-updates

#4750 [opensearch] Automate releaseDate, support and eol retrieval
  products/opensearch.md
Labels: product-updates

#4752 [oracle-database] Automate EOL retrieval
  products/oracle-database.md
Labels: product-updates

#4753 [oracle-jdk] Automate releaseDate, eol and extendedSupport retrieval
  products/oracle-jdk.md
Labels: product-updates

#4754 [postgresql] Automate releaseDate and eol retrieval
  products/postgresql.md
Labels: product-updates

#4755 [powershell] Automate releaseDate and eol retrieval
  products/powershell.md
Labels: product-updates

#4728 [tails] Update links to avoid redirects
  products/tails.md
Labels: product-updates

#4729 [vmware-srm] Switch to Wayback Machine for 5.5, 5.8 and 6.0 links
  products/vmware-srm.md
Labels: release-updates

#4437 [new product] icinga web
  products/icinga-web.md
Labels: new-product

#4762 [icinga-web] Fix auto configuration
  _plugins/product-data-validator.rb
  products/icinga-web.md
Labels: bug

#4757 [terraform] update releasePolicyLink
  products/terraform.md
Labels: product-updates

#4766 [keycloak] Add 24.0
  products/keycloak.md
Labels: release-updates

#4765 [gstreamer] Add 1.24
  products/gstreamer.md
Labels: release-updates

#4741 [muleruntime] Add 4.6 and update 4.5/4.4
  products/muleruntime.md
Labels: release-updates

#4702 [Elasticsearch] Add ES 8 and ES 7 EOL in the description
  products/elasticsearch.md
Labels: release-updates

#4774 [pan-os]Updated 10.1.12 to 10.1.13
  products/pan-os.md
Labels: release-updates

#4781 [prometheus] Automate releaseDate and eol retrieval
  products/prometheus.md
Labels: product-updates

#4782 [proxmox-ve] Automate eol retrieval
  products/proxmox-ve.md
Labels: product-updates

#4783 [quasar] Automate releaseDate, support and eol retrieval
  products/quasar.md
Labels: product-updates

#4784 pr[rabbitmq] Automate releaseDate, eol and extendedSupport retrieval
  products/rabbitmq.md
Labels: product-updates

#4785 [python] Automate releaseDate and eol retrieval
  products/python.md
Labels: product-updates

#4786 [rockyinux] Automate releaseDate, support and eol retrieval
  products/rockylinux.md
Labels: product-updates

#4787 [silverstripe] Automate releaseDate, support and eol retrieval
  products/silverstripe.md
Labels: product-updates

#4788 [spring-boot] Automate releaseDate, eol and extendedSupport retrieval
  products/spring-boot.md
Labels: product-updates

#4789 [spring-framework] Automate releaseDate, eol and extendedSupport retrieval
  products/spring-framework.md
Labels: product-updates

#4790 [umbraco] Automate releaseDate, support and eol retrieval
  products/umbraco.md
Labels: product-updates

#4791 [unrealircd] Automate releaseDate, support and eol retrieval
  products/unrealircd.md
Labels: product-updates

#4792 [varnish] Automate eol retrieval
  products/varnish.md
Labels: product-updates

#4793 [visual-cobol] Automate eol retrieval
  products/visual-cobol.md
Labels: product-updates

#4794 [vuetify] Automate releaseDate, support and eol retrieval
  products/vuetify.md
Labels: product-updates

#4795 [wagtail] Automate releaseDate, support and eol retrieval
  products/wagtail.md
Labels: product-updates

#4796 [xcp-ng] Automate releaseDate and eol retrieval
  products/xcp-ng.md
Labels: product-updates

#4797 [zabbix] Automate releaseDate, support and eol retrieval
  products/xcp-ng.md
  products/zabbix.md
Labels: product-updates

#4799 Update ruby dependencies
  Gemfile.lock
Labels: dependencies, ruby

#4800 [visual-cobol] Disable auto configuration
  products/visual-cobol.md
Labels: bug

#4778 [grafana] Add 10.4
  products/grafana.md
Labels: release-updates

#4777 [amazon-neptune] Add 1.2.1.1 and 1.3.1.0
  products/amazon-neptune.md
Labels: release-updates

#4780 [salt] Add 3007
  products/salt.md
Labels: release-updates

#4779 [postfix] Add 3.9
  products/postfix.md
Labels: release-updates

#4698 CockroachDB product
  products/cockroachdb.md
Labels: new-product

#4803 [cockroachdb] Fix auto configuration
  products/cockroachdb.md
Labels: bug

#4706 [new product] containerd
  products/containerd.md
Labels: new-product

#4746 [windows-server] Add Annual Channel 23H2
  products/windowsServer.md
Labels: release-updates, product-updates

#4439 [new product] goaccess
  products/goaccess.md
Labels: new-product

#4806 [goaccess] Fix auto configuration
  products/goaccess.md
Labels: product-fixes

#4425 [new product] chef-infra-server
  products/chef-infra-server.md
Labels: new-product

#4814 [goaccess] Drop regex
  products/goaccess.md
Labels: product-fixes

#4809 [emberjs] Add 5.7
  products/emberjs.md
Labels: release-updates

#4811 [linuxkernel] Add 6.8
  products/linuxkernel.md
Labels: release-updates

#4812 [meilisearch] Add 1.7
  products/meilisearch.md
Labels: release-updates

#4808 [azul-zulu] Update latest versions
  products/azul-zulu.md
Labels: release-updates

#4813 [telegraf] Add 1.30
  products/telegraf.md
Labels: release-updates

#4744 [mssqlserver] Fix "releaseCycle" for newer MS SQL Server versions to align with older versions and most other products
  products/mssqlserver.md
Labels: release-updates, breaking-change

#4807 [Laravel] Add 11.x
  products/laravel.md
Labels: release-updates

#4823 [panos] Updated 10.0 and 9.0
  products/pan-os.md
Labels: release-updates

#4824 Fix missing python version
  products/python.md
Labels: release-updates

#4833 [nix] Add 2.21
  products/nix.md
Labels: release-updates

#4832 [neo4j] Add 5.18
  products/neo4j.md
Labels: release-updates

#4830 [apache-hop] Add 2.8
  products/apache-hop.md
Labels: release-updates

#4815 Add Robo
  products/robo.md
Labels: new-product

#4840 [mssqlserver] Update 2022 CU12
  products/mssqlserver.md
Labels: release-updates

#4841 [msexchange] Update 2019 CU14 SU1, 2016 CU23 SU12
  products/msexchange.md
Labels: release-updates

#4837 [looker] Add 24.4
  products/looker.md
Labels: release-updates

#4836 [istio] Add 1.21
  products/istio.md
Labels: release-updates

#4831 [mattermost] Add 9.6
  products/mattermost.md
Labels: release-updates

#4838 [apache-maven] Update support policy
  products/apache-maven.md
Labels: release-updates, breaking-change, product-updates

#4845 [rabbitmq] Update auto configuration
  products/rabbitmq.md
Labels: product-updates

#4847 [amazon-corretto] Automate releaseDate retrieval
  products/amazon-corretto.md
Labels: product-updates

#4848 Fix formatting and a few typos
  products/akeneo-pim.md
  products/almalinux.md
  products/amazon-cdk.md
  products/amazon-corretto.md
  products/amazon-linux.md
  products/bun.md
  products/cert-manager.md
  products/citrix-apps-desktops.md
  products/composer.md
  products/confluence.md
  products/eks.md
  products/elasticsearch.md
  products/electron.md
  products/emberjs.md
  products/goaccess.md
  products/gstreamer.md
  products/lineageos.md
  products/mattermost.md
  products/micronaut.md
  products/mssqlserver.md
  products/mysql.md
  products/postgresql.md
  products/red-hat-openshift.md
  products/redhat-build-of-openjdk.md
  products/rust.md
  products/silverstripe.md
  products/sonarqube.md
  products/splunk.md
  products/telegraf.md
  products/terraform.md
  products/traefik.md
  products/ubuntu.md
  products/visual-cobol.md
  products/vmware-harbor-registry.md
  products/weechat.md
  products/wordpress.md
  products/yarn.md
Labels: chore

#4850 [drush] Automate eol and supportedPhpVersions retrieval
  products/drush.md
Labels: product-updates

#4849 [django] Automate supported Python versions retrieval
  products/django.md
Labels: product-updates

#4851 [ionic] Automate supported dependencies versions retrieval
  products/ionic.md
Labels: product-updates

#4764 [apache-activemq] Add 6.1
  products/apache-activemq.md
Labels: release-updates

#4852 [mattermost] Fix auto configuration
  products/mattermost.md
Labels: product-fixes

#4846 [alibaba-dragonwell] Add 21
  products/alibaba-dragonwell.md
Labels: release-updates

#4844 [new-product] Centreon
  products/centreon.md
Labels: new-product

#4856 [varnish] add 7.5.x
  products/varnish.md
Labels: release-updates

#4860 [hadoop] add 3.4.x
  products/apache-hadoop.md
Labels: release-updates

#4861 [azure-devops] Update 2022.1patch3, 2020.1.2patch13, 2019.1.2patch8
  products/azure-devops.md
Labels: release-updates

#4864 [firefox] Add 124
  products/firefox.md
Labels: release-updates

#4862 [couchbase-server] Add 7.6
  products/couchbase-server.md
Labels: release-updates

#4863 [sapmachine] Add 22
  products/sapmachine.md
Labels: release-updates

#4865 [graalvm] Add jdk-22
  products/graalvm.md
Labels: release-updates

#4866 [prometheus] Add 2.51
  products/prometheus.md
Labels: release-updates

#4870 [amazon-corretto] Add 22
  products/amazon-corretto.md
Labels: release-updates

#4872 [eclipse-temurin] Add 22
  products/eclipse-temurin.md
Labels: release-updates

#4873 [openjdk-builds-from-oracle] Add 22
  products/openjdk-builds-from-oracle.md
Labels: release-updates

#4874 [oracle-jdk] Add 22
  products/oracle-jdk.md
Labels: release-updates

#4880 [bellsoft-liberica] Add 22
  products/bellsoft-liberica.md
Labels: release-updates

#4881 [docker-engine] Add 26.0
  products/docker-engine.md
Labels: release-updates

#4882 [gitlab] Add 16.10
  products/gitlab.md
Labels: release-updates

#4887 [lineageos] add 21 & EOL 19
  products/lineageos.md
Labels: release-updates

#4894 [lineageos] Fix duplicate releases tag
  products/lineageos.md
Labels: bug

#4896 [arangodb] Add 3.12
  products/arangodb.md
Labels: release-updates

#4897 [blender] Add 4.1
  products/blender.md
Labels: release-updates

#4899 [craft-cms] Add 5
  products/craft-cms.md
Labels: release-updates

#4900 [hashicorp-vault] Add 1.16
  products/hashicorp-vault.md
Labels: release-updates

#4901 [red-hat-openshift] Add 4.15
  products/red-hat-openshift.md
Labels: release-updates

#4905 [rabbitmq] Fix auto configuration
  products/rabbitmq.md
Labels: product-updates

#4907 [quasar] Fix auto configuration
  products/quasar.md
Labels: product-updates

#4908 [envoy] Fix auto configuration
  products/envoy.md
Labels: product-updates

#4911 Update quarkus.md > Quarkus 3.9
  products/quarkus.md
Labels: release-updates

#4916 [oracle-database] Fix Doc ID 2898740.1 link
  products/oracle-database.md
Labels: product-updates

#4917 [silverstripe] Suppress link for 2.4 and 2.3
  products/silverstripe.md
Labels: release-updates

#4918 [apache-kafka] Update 3.4 link
  products/apache-kafka.md
Labels: release-updates

#4919 [icinga-web] Suppress 1 link
  products/icinga-web.md
Labels: product-fixes

#4909 [ubuntu] Adds legacy support
  products/ubuntu.md
Labels: product-fixes

#4922 [jira] Add 9.15
  products/jira.md
Labels: release-updates

#4756 [new product] opentofu
  products/opentofu.md
Labels: new-product

#4921 [apache-camel] Add 4.5
  products/apache-camel.md
Labels: release-updates
