Repository endoflife-date/endoflife.date, pull requests merged in 2024-01, with the labels that each got.

#4407 Suppress support.herodevs.com link validation errors
  _plugins/product-data-validator.rb
Labels: chore

#4412 Change "redhat" tag to "red-hat"
  _redirects
  products/redhat-build-of-openjdk.md
Labels: product-fixes

#4414 Rename the 'db' category to 'database'
  CONTRIBUTING.md
  _plugins/product-data-validator.rb
  _redirects
  products/amazon-rds-mysql.md
  products/amazon-rds-postgresql.md
  products/apache-cassandra.md
  products/apache-hadoop.md
  products/couchbase-server.md
  products/elasticsearch.md
  products/etcd.md
  products/hbase.md
  products/mariadb.md
  products/memcached.md
  products/mongodb.md
  products/mssqlserver.md
  products/mysql.md
  products/neo4j.md
  products/opensearch.md
  products/oracle-database.md
  products/postgresql.md
  products/redis.md
  products/sqlite.md
  products/tarantool.md
Labels: enhancement, product-updates

#4288 [new-product] arangodb
  products/arangodb.md
Labels: new-product

#4282 [new-product] Oracle APEX
  products/oracle-apex.md
Labels: new-product

#4360 [new-product] ovirt.md
  products/ovirt.md
Labels: new-product

#4429 [pan-os] updated 11.1 to 11.1.1
  products/pan-os.md
Labels: release-updates

#4415 [qt] Fix latest 5.15 release
  products/qt.md
Labels: product-fixes

#4420 [android] Update 4.4 to 9 EOL date
  products/android.md
Labels: release-updates

#4436 [nginx] add binary purl
  products/nginx.md
Labels: product-updates

#4435 [haproxy] add purl identifiers
  products/haproxy.md
Labels: product-updates

#4334 [kirby] Add 3.10 with PHP 8.3 support
  products/kirby.md
Labels: release-updates

#4443 Use official redis repo for changelog
  products/redis.md
Labels: product-updates

#4441  [plesk] Add 18.0.58
  products/plesk.md
Labels: release-updates

#4449 [ovirt] Fix regex
  products/ovirt.md
Labels: product-fixes

#4328 [new-product] Add Motorola Mobility product page.
  products/motorola-mobility.md
Labels: new-product

#4385 [new-product] opnsense
  products/opnsense.md
Labels: new-product

#4433 [lua]: initial support
  products/lua.md
Labels: new-product

#4372 [new-product] meilisearch
  products/meilisearch.md
Labels: new-product

#4453 [meilisearch] Fix dates and update description
  products/meilisearch.md
Labels: release-updates, product-fixes, product-updates

#4462 [looker] Add 24.0
  products/looker.md
Labels: release-updates

#4463 [prometheus] Add 2.49
  products/prometheus.md
Labels: release-updates

#4464 [meilisearch] Add 1.6
  products/meilisearch.md
Labels: release-updates

#4465 [mattermost] Add 9.4
  products/mattermost.md
Labels: release-updates

#4461 [envoy] add 1.29 version stream
  products/envoy.md
Labels: release-updates

#4451 [qt] Clarify support policy
  products/qt.md
Labels: release-updates, product-fixes, product-updates

#4477 [pan-os] Update 11.0.3 to 11.0.3-h3
  products/pan-os.md
Labels: release-updates

#4485 [oracle-database] Update 21c EOL
  products/oracle-database.md
Labels: release-updates

#4484 [apache-hadoop] Set 3.2 EOL
  products/apache-hadoop.md
Labels: release-updates

#4483 [terraform] Add 1.7
  products/terraform.md
Labels: release-updates

#4482 [sapmachine] Update EOL dates
  products/sapmachine.md
Labels: release-updates

#4481 [ibm-semeru] Add 21 and update EOL dates
  products/ibm-semeru.md
Labels: release-updates

#4480 [microsoft-build-of-openjdk] Update EOL dates
  products/microsoft-build-of-openjdk.md
Labels: release-updates

#4479 [amazon-corretto] Update LTS EOL dates
  products/amazon-corretto.md
Labels: release-updates

#4470 [gitlab] Add 16.8
  products/gitlab.md
Labels: release-updates

#4469 Update unity.md
  products/unity.md
Labels: release-updates

#4452 [ovirt] Fix changelogTemplate
  products/ovirt.md
Labels: product-fixes

#4442 [mongodb] Adds 7.2 release
  products/mongodb.md
Labels: release-updates

#4497 Drop _auto/bulk-update.py script
  .github/dependabot.yml
  .github/workflows/auto-merge-release-updates.yml
  _auto/bulk-update.py
  requirements.txt
Labels: chore

#4498 [kdeplasma] Exclude 80/90 minor and patch version
  CONTRIBUTING.md
  product-schema.json
  products/kdeplasma.md
Labels: product-updates

#4499 [dotnet] Simplify regex using an exclusion
  products/dotnet.md
Labels: chore

#4500 [gradle] Simplify regex using an exclusion
  products/gradle.md
Labels: chore

#4501 [postfix] Simplify regex using an exclusion
  products/postfix.md
Labels: chore

#4241 [new-product] Zerto
  products/zerto.md
Labels: new-product

#4264 Add PURL identifiers for multiple products
  products/angular.md
  products/angularjs.md
  products/ansible.md
  products/emberjs.md
  products/firefox.md
  products/grafana.md
  products/ionic.md
  products/jquery.md
  products/keycloak.md
  products/kubernetes.md
  products/mariadb.md
  products/neo4j.md
  products/nextjs.md
  products/nexus.md
  products/nginx.md
  products/numpy.md
  products/perl.md
  products/php.md
  products/phpmyadmin.md
  products/postgresql.md
  products/powershell.md
  products/rancher.md
  products/react.md
  products/spring-boot.md
  products/sqlite.md
  products/terraform.md
  products/tomcat.md
  products/zookeeper.md
Labels: product-updates

#4503 [ovirt] Fix changelogTemplate
  products/ovirt.md
Labels: product-fixes

#4504 [openssl] Update 1.1.1 link
  products/openssl.md
Labels: release-updates

#4505 Suppress errors in product-data-validator.rb for a few links
  _plugins/product-data-validator.rb
Labels: chore

#4494 [linuxkernel] Mark 4.14 as EOL
  products/linuxkernel.md
Labels: release-updates

#4495 [new-product] Apache Struts
  products/apache-struts.md
Labels: new-product

#4491 [docker-engine] Add 25.0
  products/docker-engine.md
Labels: release-updates

#4512 [phpmyadmin] Fix duplicate identifiers entries
  products/phpmyadmin.md
Labels: product-fixes

#4421 [pixel] Clarify and fix support and EOL columns
  products/pixel.md
Labels: release-updates, breaking-change

#4514 [emberjs] Add 5.6
  products/emberjs.md
Labels: release-updates

#4517 [weechat] Add 4.2
  products/weechat.md
Labels: release-updates

#4515 [jira] Add 9.13
  products/jira.md
Labels: release-updates

#4492 [keda] Add 2.13
  products/keda.md
Labels: release-updates

#4516 [neo4j] Add 5.16
  products/neo4j.md
Labels: release-updates

#4519 [Firefox] Add 122
  products/firefox.md
Labels: release-updates

#4493 [veeam-backup-and-replication] Add latest release column and set up automation
  products/veeam-backup-and-replication.md
Labels: release-updates, product-updates

#4521 [eks] Add 1.29
  products/eks.md
Labels: release-updates

#4524 [pan-os]Updated pan-os 10.1.11-h4 to 10.1.11-h5
  products/pan-os.md
Labels: release-updates

#4523 [cassandra] 3.11 and 3.10 are not yet EOL
  products/apache-cassandra.md
Labels: product-fixes

#4528 [alpinelinux] Update latest for 3.16, 3.17, 3.18 & 3.19
  products/alpinelinux.md
Labels: release-updates

#4531 [gke] Add 1.29 and update 1.28 EOL
  products/gke.md
Labels: release-updates

#4533 FIX: Updates Silverstripe roadmap graphic to latest
  products/silverstripe.md
Labels: product-updates

#4536 [LibreOffice] Add 24.2
  products/libreoffice.md
Labels: release-updates
