Repository endoflife-date/endoflife.date, pull requests merged in 2024-11, with the labels that each got.

#6132 [calico] add 3.29
  products/calico.md
Labels: release-updates

#6133 [firefox] add 132
  products/firefox.md
Labels: release-updates

#6134 [meilisearch] add 1.11
  products/meilisearch.md
Labels: release-updates

#6135 [traefik] add 3.2
  products/traefik.md
Labels: release-updates

#6136 [plesk] add 18.0.65
  products/plesk.md
Labels: release-updates

#6137 [kyverno] add 1.13
  products/kyverno.md
Labels: release-updates

#5982 [office] added office 2024
  products/office.md
Labels: release-updates

#6146 [wagtail] add 6.3
  products/wagtail.md
Labels: release-updates

#6147 [neo4j] add 5.25
  products/neo4j.md
Labels: release-updates

#6148 [windows-server] Add 2025
  products/windows-server.md
Labels: release-updates

#6152 [silverstripe] add 5.3
  products/silverstripe.md
Labels: release-updates

#6154 [fedora] add 41
  products/fedora.md
Labels: release-updates

#6157 [react-native] Update eol for 0.73 and eoas for 0.74
  products/react-native.md
Labels: release-updates

#6156 [ipados] Update eol for iPadOS 15
  products/ipados.md
Labels: release-updates

#6150 [mssqlserver] Update 2019 CU29
  products/mssqlserver.md
Labels: release-updates

#6159 [unity] Update latest releases
  products/unity.md
Labels: release-updates

#6165 [ipad] update supportedIpadOsVersions
  products/ipad.md
Labels: release-updates

#6169 [argocd] add 2.13 and update eol for 2.10
  products/argocd.md
Labels: release-updates

#6172 [Centreon] Add 24.10 LTS
  products/centreon.md
Labels: release-updates

#6171 [samsungmobile] update links
  products/samsungmobile.md
Labels: enhancement

#6174 [pan-gp]Updated GlobalProtect App from 6.0.10-c823 to 6.0.10-c826
  products/pan-gp.md
Labels: release-updates

#6167 [symfony] Update Symfony 5.4 EOAS
  products/symfony.md
Labels: release-updates

#6183 [coder] Add 2.17 release
  products/coder.md
Labels: release-updates

#6184 [amazon-neptune] add 1.4.0.0 release
  products/amazon-neptune.md
Labels: release-updates

#6185 [ansible-core] add 2.18
  products/ansible-core.md
Labels: release-updates

#6186 [containerd] add 2.0
  products/containerd.md
Labels: release-updates

#6187 [istio] Add 1.24
  products/istio.md
Labels: release-updates

#6193 [ansible]: update eol for ansible 9.x
  products/ansible.md
Labels: release-updates

#6191 [coldfusion] Update latest releases
  products/coldfusion.md
Labels: release-updates

#6194 [harbor] add 2.12 release
  products/harbor.md
Labels: release-updates

#6214 [amazon-corretto] update release_table check, and update eol for 11.x and 8.x again
  products/amazon-corretto.md
Labels: auto

#6212 [nix] add 2.25
  products/nix.md
Labels: release-updates

#6213 [redmine] add 6.0
  products/redmine.md
Labels: release-updates

#6211 [grafana] update eol dates
  products/grafana.md
Labels: product-fixes

#6227 [docker] Fix release notes URL
  products/docker-engine.md
Labels: bug

#6230 [aks] Correct EOL and LTS dates
  products/azure-kubernetes-service.md
Labels: product-fixes

#6219 [dotnet] add 9
  products/dotnet.md
Labels: release-updates

#6220 [apache-spark] update eol for 3.4
  products/apache-spark.md
Labels: release-updates

#6233 [visualstudio] add 17.12
  products/visualstudio.md
Labels: release-updates

#6234 [wordpress] add 6.7
  products/wordpress.md
Labels: release-updates

#6232 [podman] add 5.3
  products/podman.md
Labels: release-updates

#6231 [fluent-bit] add 3.2
  products/fluent-bit.md
Labels: release-updates

#6237 [pan-gp]Update GlobalProtect to 6.2.6
  products/pan-gp.md
Labels: release-updates

#6236 [apple watch] update EOL dates, add watchOS 11 and series 10
  products/apple-watch.md
Labels: release-updates

#6225 [scala] Update JDK Compatibility
  products/scala.md
Labels: product-updates

#6242 [jboss-eap] Update to JBoss 8.0.4
  products/red-hat-jboss-eap.md
Labels: release-updates

#6224 [grafana] Support security release versioning scheme
  products/grafana.md
Labels: product-fixes, auto

#6244 [almalinux] update 9.x (9.5)
  products/almalinux.md
Labels: release-updates

#6251 [spring-framework] Add version 6.2
  products/spring-framework.md
Labels: release-updates

#6253 [react-native] Update latest for 0.76 and 0.73
  products/react-native.md
Labels: release-updates

#6249 [mssqlserver] Update 2019 CU29+GDR
  products/mssqlserver.md
Labels: release-updates

#6256 [ansible] add 11
  products/ansible.md
Labels: release-updates

#6252 [spring-boot] Update latest for 3.3
  products/spring-boot.md
Labels: release-updates

#6263 [blender] add 4.3
  products/blender.md
Labels: release-updates

#6261 [visionos] Update visionos eoas
  products/visionos.md
Labels: release-updates

#6266 [grafana-loki] add 3.3
  products/grafana-loki.md
Labels: release-updates

#6267 [mattermost] add 10.2
  products/mattermost.md
Labels: release-updates

#6269 [cockroachdb] add 24.3
  products/cockroachdb.md
Labels: release-updates

#6270 [amazon-rds-postgresql] add 17
  products/amazon-rds-postgresql.md
Labels: release-updates

#6199 [new product] add svelte
  products/svelte.md
Labels: new-product

#6197 [keda] Add 2.16
  products/keda.md
Labels: release-updates

#6170 [iphone] update eol
  products/iphone.md
Labels: release-updates

#6259 [jira] Add 10.2 release
  products/jira.md
Labels: release-updates

#6262 [unity] Update unity.md
  products/unity.md
Labels: release-updates

#6281 [svelte] Add 5.2 release cycle
  products/svelte.md
Labels: release-updates

#6280 [umbraco] Add 15.0 release
  products/umbraco.md
Labels: release-updates

#6290 [dotnet] Fix regex to ignore RC releases
  products/dotnet.md
Labels: bug

#6288 Add 2024 iPad models
  products/ipad.md
Labels: release-updates

#6295 [pan-gp]Updated GlobalProtect App to version 6.0.11
  products/pan-gp.md
Labels: release-updates

#6292 [amazon-rds-mysql] add 8.4
  products/amazon-rds-mysql.md
Labels: release-updates

#6296 [mariadb] Add 11.6, Update eol 11.5
  products/mariadb.md
Labels: release-updates

#6300 [unity] Update unity 2021.3
  products/unity.md
Labels: release-updates

#6299 [spring-boot] Add 3.4 release
  products/spring-boot.md
Labels: release-updates

#6307 [nvidia-driver] Add R565-Linux, R565-Windows, Update 550.127.08 Linux, 535.216.03 Linux
  products/nvidia-driver.md
Labels: release-updates

#6312 [msexchange] Update 2019 CU14 SU3V2, 2016 CU23 SU14V2
  products/msexchange.md
Labels: release-updates
