Repository endoflife-date/endoflife.date, pull requests merged in 2024-09, with the labels that each got.

#5754 Update API doco to mention slash replacement in cycle parameter
  assets/openapi.yml
Labels: documentation, api

#5757 [grafana] add 11.2
  products/grafana.md
Labels: release-updates, auto

#5781 [vue] Add release cycle 3.5
  products/vue.md
Labels: release-updates

#5785 [firefox] add 130.0
  products/firefox.md
Labels: release-updates

#5792 [logstash] mark 8.x active
  products/logstash.md
Labels: product-fixes

#5791 [nexus] add 3.72
  products/nexus.md
Labels: release-updates

#5797 [unity] Update latest releases for unity 6 and 2022.3
  products/unity.md
Labels: release-updates

#5798 [sourcegraph] Fix github repository link
  products/sourcegraph.md
Labels: auto

#5793 Update JBoss 8 to version 8.0.3
  products/red-hat-jboss-eap.md
Labels: release-updates

#5799 [kibana] Fix 8 EOL
  products/kibana.md
  products/logstash.md
Labels: product-updates

#5795 [pan-os]Update PAN-OS version(s)
  products/pan-os.md
Labels: release-updates

#5804 [red-hat-openshift] add 4.16
  products/red-hat-openshift.md
Labels: release-updates

#5806 [pan-os] Disable auto version updates
  products/pan-os.md
Labels: bug, auto

#5803 [panos]Update panos version(s)
  products/pan-os.md
Labels: release-updates

#5801 [rocket-chat] add 6.12
  products/rocket-chat.md
Labels: release-updates

#5800 [apache-cassandra] add 5.0
  products/apache-cassandra.md
Labels: release-updates

#5817 [firefox] Note ESR 115 extension
  products/firefox.md
Labels: product-fixes

#5818 [cassandra] Don't estimate future release dates
  products/apache-cassandra.md
Labels: bug

#5820 Update raspberrypi.md
  products/raspberrypi.md
Labels: release-updates

#5822 [telegraf] add 1.32
  products/telegraf.md
Labels: release-updates

#5821 [godot] add 3.6
  products/godot.md
Labels: release-updates

#5830 [kong-gateway] add 3.8
  products/kong-gateway.md
Labels: release-updates

#5831 [looker] add 24.16
  products/looker.md
Labels: release-updates

#5833 [nextcloud] add 30
  products/nextcloud.md
Labels: release-updates

#5834 [macos] Add macos 15
  products/macos.md
Labels: release-updates

#5840 [mssqlserver] Update GDR for 2022, 2019, 2017, 2016
  products/mssqlserver.md
Labels: release-updates

#5838 [mssharepoint] Update latest subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#5839 [nvidia-driver] Update 550.90.12
  products/nvidia-driver.md
Labels: release-updates

#5849 [drupal] Add EOL date for 11.0
  products/drupal.md
Labels: product-fixes

#5854 [visionos] add 2
  products/visionos.md
Labels: release-updates

#5855 [watchos] add 11
  products/watchos.md
Labels: release-updates

#5853 [linuxkernel] add 6.11
  products/linuxkernel.md
Labels: release-updates

#5862 [vmware-esxi] 8.0 Update 3b, 6.7 ESXi670-202403001, 6.5 ESXi650-202403001
  products/vmware-esxi.md
Labels: release-updates

#5841 [apache-camel] add 4.8
  products/apache-camel.md
Labels: release-updates

#5867 [rabbitmq] add 4.0
  products/rabbitmq.md
Labels: release-updates

#5870 [plesk] add 18.0.64
  products/plesk.md
Labels: release-updates

#5868 [graalvm] add 23
  products/graalvm.md
Labels: release-updates

#5869 [oracle-jdk] add 23
  products/oracle-jdk.md
Labels: release-updates

#5871 [sapmachine] add 23
  products/sapmachine.md
Labels: release-updates

#5877 [eclipse-temurin] add 23
  products/eclipse-temurin.md
Labels: release-updates

#5882 [bellsoft-liberica] add 23
  products/bellsoft-liberica.md
Labels: release-updates

#5884 [docker-engine] add 27.3
  products/docker-engine.md
Labels: release-updates

#5885 [grafana-loki] add 3.2
  products/grafana-loki.md
Labels: release-updates

#5886 [api-platform] add 3.4 and 4.0
  products/api-platform.md
Labels: release-updates

#5878 [cakephp] Add 5.1
  products/cakephp.md
Labels: release-updates

#5883 [ibm-semeru] add 23
  products/ibm-semeru.md
Labels: release-updates

#5858 [watchos] Update eoas for watchos 10 and eol for watchos 9
  products/watchos.md
Labels: release-updates

#5848 [Gitlab] Add 17.4
  products/gitlab.md
Labels: release-updates

#5505 [new-product] add podman
  products/podman.md
Labels: new-product

#5859 [vault] Switch to N-2 policy for LTS
  products/hashicorp-vault.md
Labels: product-fixes

#5891 [unity] Update latest releases for unity 6 and 2022.3
  products/unity.md
Labels: release-updates

#5897 [nutanix-prism] add pc.2024.2
  products/nutanix-prism.md
Labels: release-updates

#5895 [apache-couchdb] add 3.4
  products/apache-couchdb.md
Labels: release-updates

#5899 [couchbase-server] Update auto configuration
  products/couchbase-server.md
Labels: auto

#5898 [mattermost] Add 9.11 and 10.0
  products/mattermost.md
Labels: release-updates

#5896 [mautic] add 5.1
  products/mautic.md
Labels: release-updates

#5903 [rabbitmq] fix eoes for 3.12
  products/rabbitmq.md
Labels: release-updates

#5909 [postgresql] add 17
  products/postgresql.md
Labels: release-updates

#5908 [quarkus] add 3.15
  products/quarkus.md
Labels: release-updates

#5912 [react-native] Add 0.45 release
  products/react-native.md
Labels: release-updates

#5919 [vmware-vcenter] Update latest release
  products/vmware-vcenter.md
Labels: release-updates

#5918 [visual-cobo] Add Visual Cobol 10
  products/visual-cobol.md
Labels: release-updates

#5916 [eks] add 1.31 release
  products/eks.md
Labels: release-updates

#5915 [neo4j] add 5.24
  products/neo4j.md
Labels: release-updates
