Repository endoflife-date/endoflife.date, pull requests merged in 2024-02, with the labels that each got.

#4538 [eks] Use precise dates for eol
  products/eks.md
Labels: product-fixes

#4543 [cert-manager] Add 1.14
  products/cert-manager.md
Labels: release-updates

#4544 [nix] Add 2.20
  products/nix.md
Labels: release-updates

#4545 [opnsense] Add 24.1
  products/opnsense.md
Labels: release-updates

#4547 [splunk] Add 9.2
  products/splunk.md
Labels: release-updates

#4548 [typo3] Add 13
  products/typo3.md
Labels: release-updates

#4546 [quarkus] Add 3.7
  products/quarkus.md
Labels: release-updates

#4552 [mssharepoint] Update Subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#4550 [mssqlserver] Update 2022 CU11
  products/mssqlserver.md
Labels: release-updates

#4554 Suppress errors in product-data-validator.rb for a few links
  _plugins/product-data-validator.rb
Labels: chore

#4553 [vmware-srm] Add 8.7 and 8.8, update latest
  products/vmware-srm.md
Labels: release-updates

#4566 Revert "[windows-server] Updated EOL, ESU and product link for 2016 (#4557)"
  products/windowsServer.md
Labels: release-updates

#4564 [drupal] Fix language for D7 EOL
  products/drupal.md
Labels: product-fixes

#4567 [argocd] Add 2.10
  products/argocd.md
Labels: release-updates

#4063 [New product] Add IBM i operating system (AS400)
  products/ibm-i.md
Labels: new-product

#4574 [confluence] Add 8.8 and update 8.7 EOL
  products/confluence.md
Labels: release-updates

#4573 [clamav] Add 1.3
  products/clamav.md
Labels: release-updates

#4583 [alibaba-dragonwell] Simplify auto configs
  products/alibaba-dragonwell.md
Labels: chore

#4584 Mention script name in custom auto method declarations
  products/amazon-neptune.md
  products/amazon-rds-mysql.md
  products/amazon-rds-postgresql.md
  products/apache-http-server.md
  products/artifactory.md
  products/aws-lambda.md
  products/coldfusion.md
  products/confluence.md
  products/cos.md
  products/couchbase-server.md
  products/debian.md
  products/eks.md
  products/firefox.md
  products/gke.md
  products/graalvm.md
  products/haproxy.md
  products/ibm-aix.md
  products/ios.md
  products/ipados.md
  products/jira.md
  products/looker.md
  products/macos.md
  products/nutanix-aos.md
  products/nutanix-files.md
  products/nutanix-prism.md
  products/oracle-jdk.md
  products/php.md
  products/plesk.md
  products/red-hat-openshift.md
  products/redhat-satellite.md
  products/rockylinux.md
  products/splunk.md
  products/typo3.md
  products/unity.md
  products/unrealircd.md
  products/veeam-backup-and-replication.md
  products/visualstudio.md
  products/watchos.md
Labels: enhancement

#4580 [rust] Add changelogTemplate, add 1.76, update 1.75 eol
  products/rust.md
Labels: release-updates

#4579 [composer] Add 2.7, update 2.6 eol
  products/composer.md
Labels: release-updates

#4588 [firefox][unity] Mark auto-update as cumulative
  CONTRIBUTING.md
  products/firefox.md
  products/unity.md
Labels: product-updates

#4591 [akeneo-pim] Automate releaseDate and eol retrieval
  products/akeneo-pim.md
Labels: product-updates

#4576 [wagtail] Add 6.0
  products/wagtail.md
Labels: release-updates

#4575 [rocket-chat] Add 6.6
  products/rocket-chat.md
Labels: release-updates

#4590 [aws-lambda] Update description
  products/aws-lambda.md
Labels: product-updates

#4595 [pan-gp] Update eol/support for 6.1, 6.0, 5.1
  products/pan-gp.md
Labels: release-updates

#4601 [pan-cortex-xdr] Automate releaseDate and eol retrieval
  products/pan-cortex-xdr.md
Labels: product-updates

#4600 [pan-gp] Automate releaseDate, support and eol retrieval
  products/pan-gp.md
Labels: product-updates

#4599 [pan-os] Automate releaseDate and eol retrieval
  products/pan-os.md
Labels: product-updates

#4607 [visualstudio] Add 17.9, Update eol for lts versions 17.8, 17.6, 17.4, 17.2
  products/visualstudio.md
Labels: release-updates

#4611 [alpinelinux] Automate eol retrieval
  products/alpinelinux.md
Labels: product-updates

#4608 [pan-os] Add 7.0-1.3
  products/pan-os.md
Labels: release-updates

#4621 [alibaba-dragonwell] Automate eol retrieval
  products/alibaba-dragonwell.md
Labels: product-updates

#4625 [artifactory] Restore auto configuration
  products/artifactory.md
Labels: product-updates

#4626 [amazon-corretto] Automate eol retrieval
  products/amazon-corretto.md
Labels: product-updates

#4614 [gitlab] Add 16.9
  products/gitlab.md
Labels: release-updates

#4615 [looker] Add 24.2 and update 24.0 dates
  products/looker.md
Labels: release-updates

#4587 [kong-gateway] Add 3.6
  products/kong-gateway.md
Labels: release-updates

#4563 [mattermost] 9.5 release
  products/mattermost.md
Labels: release-updates

#4629 [amazon-corretto] Automate deprecated release eol retrieval
  products/amazon-corretto.md
Labels: product-updates

#4630 [amazon-neptune] Automate EOL and upgradeVersion retrieval
  products/amazon-neptune.md
Labels: product-updates

#4624 [zabbix] Update 6.4 support/eol, 6.0 releaseDate
  products/zabbix.md
Labels: release-updates

#4627 [mssharepoint] Update subscription, 2019
  products/mssharepoint.md
Labels: release-updates

#4628 [msexchange] 2019 CU14
  products/msexchange.md
Labels: release-updates

#4622 [apache-kafka] Update 3.6 exetendedSupport
  products/apache-kafka.md
Labels: release-updates

#4632 [amazon-rds-postgresql] Automate EOL retrieval
  products/alibaba-dragonwell.md
  products/amazon-corretto.md
  products/amazon-rds-postgresql.md
Labels: product-updates

#4633 [pan-cortex-xdr] Fix releaseCycle's regex in release_table auto configuration
  products/pan-cortex-xdr.md
Labels: product-fixes

#4635 [apache-kafka] Automate extendedSupport retrieval
  products/apache-kafka.md
Labels: product-updates

#4613 Improve date validation in product-data-validator.rb and fix a few dates
  _plugins/product-data-validator.rb
  products/lua.md
  products/mssqlserver.md
  products/neo4j.md
  products/rust.md
  products/ubuntu.md
  products/unity.md
  products/windows.md
Labels: enhancement, release-updates

#4332 [new-product] Google Nexus
  products/google-nexus.md
Labels: new-product

#4382 [new-product] bun
  products/bun.md
Labels: new-product

#4641 [bazel] Automate EOL retrieval
  products/bazel.md
Labels: product-updates

#4644 [bun] Fix auto configuration
  products/bun.md
Labels: bug

#4639 [contao] Add 5.3
  products/contao.md
Labels: release-updates

#4637 [artifactory] Add 7.77
  products/artifactory.md
Labels: release-updates

#4640 [jira] Add 9.14 and set 9.13 EOL
  products/jira.md
Labels: release-updates

#4646 [apache-camel] Add 4.4, Update 4.3 eol
  products/apache-camel.md
Labels: release-updates

#4585 [bellsoft-liberica] Update 17 and 21 links
  products/bellsoft-liberica.md
Labels: release-updates

#4651 [bun] Fix auto configuration
  products/bun.md
Labels: product-fixes

#4652 [debian] Automate EOL retrieval
  products/debian.md
Labels: product-updates

#4654 [dotnet] Automate EOL retrieval
  products/dotnet.md
Labels: product-updates

#4655 [dotnetfx] Automate EOL retrieval
  products/dotnetfx.md
Labels: product-updates

#4634 [apache-airflow] Improve page
  products/apache-airflow.md
Labels: product-updates

#4659 [apple] Update Apple products auto configuration
  products/ios.md
  products/ipados.md
  products/macos.md
  products/watchos.md
Labels: chore

#4665 [plesk] Add 18.0.59
  products/plesk.md
Labels: release-updates

#4670 [confluence][jira] Automate EOL retrieval
  products/confluence.md
  products/jira.md
Labels: product-updates

#4669 [jenkins] Add 2.440 LTS
  products/jenkins.md
Labels: release-updates

#4668 [rocket-chat] Automate EOL retrieval and fix some EOL dates
  products/rocket-chat.md
Labels: product-fixes, product-updates

#4680 [bazel] Update auto configuration
  products/bazel.md
Labels: product-updates

#4398 Handle Ctrl + K key-press to focus on a search input element
  _config.yml
Labels: enhancement

#4685 [couchbase-server] Automate EOL retrieval
  products/couchbase-server.md
Labels: product-updates

#4686 [craft-csm] Automate EOL retrieval
  products/craft-cms.md
Labels: product-updates

#4687 [eclipse-temurin] Automate EOL retrieval
  products/eclipse-temurin.md
Labels: product-updates

#4688 [eks] Automate EOL retrieval
  products/eks.md
Labels: product-updates

#4689 [electron] Automate EOL retrieval
  products/electron.md
Labels: product-updates

#4691 [envoy] Automate EOL retrieval
  products/electron.md
  products/envoy.md
Labels: product-updates

#4684 [prometheus] Add 2.50
  products/prometheus.md
Labels: release-updates

#4683 [pan-cortex-xdr] Add 8.3 and update latest releases
  products/pan-cortex-xdr.md
Labels: release-updates

#4682 [neo4j] Add 5.17
  products/neo4j.md
Labels: release-updates

#4681 [dotnet] Drop .0 suffix for versions 5 and greater
  products/dotnet.md
Labels: release-updates, breaking-change

#4679 [aws-lambda] Add .NET 8
  products/aws-lambda.md
Labels: release-updates

#4699 [azure-devops] Update 2022.1patch2, 2020.1.2patch12, 2019.1.2patch7
  products/azure-devops.md
Labels: release-updates

#4714 [consul] Add 1.18, update 1.15 eol
  products/consul.md
Labels: release-updates

#4716 [tails] Add 6, update 5 eol
  products/tails.md
Labels: release-updates

#4715 [kdeplasma] Add 6.0, update 5.24 eol
  products/kdeplasma.md
Labels: release-updates

#4581 Remove dead link about iOS 12 security updates
  products/ios.md
Labels: release-updates

#4704 Update ios.md
  products/ios.md
Labels: release-updates

#4718 [ipad] Mark iPad air 1, mini 2 and mini 3 as EOL
  products/ipad.md
Labels: release-updates

#4719 [kirby] Reduce releaseCycle 4, update 4.1.1
  products/kirby.md
Labels: release-updates
