Repository endoflife-date/endoflife.date, pull requests merged in 2024-10, with the labels that each got.

#5927 [mssqlserver] Update 2022 CU15
  products/mssqlserver.md
Labels: release-updates

#5925 [pan-os]Update PAN-OS version(s)
  products/pan-os.md
Labels: release-updates

#5928 [flux] add 2.4
  products/flux.md
Labels: release-updates

#5930 [coder] Add 2.16
  products/coder.md
Labels: release-updates

#5936 [dependencytrack] add 4.12
  products/dependencytrack.md
Labels: release-updates

#5923 [ffmpeg] Adds 7.1
  products/ffmpeg.md
Labels: release-updates

#5894 [python] Add 3.13 release
  products/python.md
Labels: release-updates

#5937 [firefox] add 131
  products/firefox.md
Labels: release-updates

#5945 [python] Drops 3.13
  products/python.md
Labels: bug

#5942 [composer] Add 2.8, Update 2.7 eol, Remove note for Composer 1.x on packagist
  products/composer.md
Labels: release-updates

#5943 [confluence] Add 9.1
  products/confluence.md
Labels: release-updates

#5949 [linux] update releaseImage
  products/linuxkernel.md
Labels: product-updates

#5955 [amazon-neptune] add 1.3.4.0
  products/amazon-neptune.md
Labels: release-updates

#5944 [red-hat-openshift] Add 4.17, Update 4.16 eoas
  products/red-hat-openshift.md
Labels: release-updates

#5832 [mongodb] add 8.0
  products/mongodb.md
Labels: release-updates

#5962 [cos] Adds m117
  products/cos.md
Labels: release-updates

#5966 [nutanix-aos] Adds 6.10 release
  products/nutanix-aos.md
Labels: release-updates

#5964 [keycloak] Adds 26
  products/keycloak.md
Labels: release-updates

#5961 [composer] Mark 1.x service EOL as well
  products/composer.md
Labels: product-fixes

#5967 [unity] Update unity releases
  products/unity.md
Labels: release-updates

#5963 [filemaker] Update EOL of 19 to 19.6 EOL
  products/filemaker.md
Labels: product-fixes

#5954 [amazon-corretto] add 23
  products/amazon-corretto.md
Labels: release-updates

#5929 [emberjs] add 5.12
  products/emberjs.md
Labels: release-updates

#5980 [qt] Add 6.8 LTS
  products/qt.md
Labels: release-updates

#5985 [tomcat] add 11.0 release
  products/tomcat.md
Labels: release-updates

#5986 [apache-hop] add 2.10
  products/apache-hop.md
Labels: release-updates

#5989 [mastodon] add 4.3
  products/mastodon.md
Labels: release-updates

#5988 [kdeplasma] add 6.2
  products/kdeplasma.md
Labels: release-updates

#5996 [rust] Fix latestReleaseDate for 1.80
  products/rust.md
Labels: release-updates

#5990 [mastodon] Add Identifiers and ActivityPub link in description
  products/mastodon.md
Labels: release-updates

#5991 [xcp-ng] add 8.3
  products/xcp-ng.md
Labels: release-updates

#5987 [hashicorp-vault] add 1.18
  products/hashicorp-vault.md
Labels: release-updates

#6000 [corretto] EOL Extension for 8 and 11
  products/amazon-corretto.md
Labels: product-fixes

#6001 [ubuntu] Adds 24.10
  products/ubuntu.md
Labels: release-updates

#5997 [VMware vCenter Server] update to latest release
  products/vmware-vcenter.md
Labels: release-updates

#6005 [looker] add 24.18
  products/looker.md
Labels: release-updates

#6004 [jira] add 10.1
  products/jira.md
Labels: release-updates

#6007 [pan-cortex-xdr] add 8.6
  products/pan-cortex-xdr.md
Labels: release-updates

#6006 [nomad] add 1.9
  products/nomad.md
Labels: release-updates

#6008 [centreon] add releaseImage
  products/centreon.md
Labels: product-fixes

#6014 [pan-os]Update PAN-OS version(s)
  products/pan-os.md
Labels: release-updates

#6010 [ubuntu] Correct 24.10 extended support
  products/ubuntu.md
Labels: bug

#6017 [graalvm] Mark only the latest version as supported
  products/graalvm.md
Labels: product-fixes

#6023 [mysql]Update mysql 8.0 latest info
  products/mysql.md
Labels: release-updates

#6020 [electron] add 33
  products/electron.md
Labels: release-updates

#6022 [envoy] add 1.32 release
  products/envoy.md
Labels: release-updates

#6021 [nexus] add 3.73
  products/nexus.md
Labels: release-updates

#6028 [pan-gp]Updated GlobalProtect App from 6.3.1 to 6.3.1-c383
  products/pan-gp.md
Labels: release-updates

#6018 [consul] add 1.20
  products/consul.md
Labels: release-updates

#6036 [rust] add release 1.82
  products/rust.md
Labels: release-updates

#6034 [apache-apisix] add 3.11
  products/apache-apisix.md
Labels: release-updates

#6032 [gitlab] add 17.5
  products/gitlab.md
Labels: release-updates

#6033 [amazon-rds-mariadb] add 11.4
  products/amazon-rds-mariadb.md
Labels: release-updates

#5992 [macos] add Mac OS X 10.0 through OS X 10.8
  products/macos.md
Labels: release-updates

#6041 [yocto] add 5.1
  products/yocto.md
Labels: release-updates

#6050 [linuxkernel] Update 6.10 eol
  products/linuxkernel.md
Labels: release-updates

#6052 [mssqlserver] Update 2022 CU15+GDR, 2019 CU28+GDR, 2017 CU31+GDR, 2016 SP3+GDR
  products/mssqlserver.md
Labels: release-updates

#6051 [mssharepoint] Update latest subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#6046 [pixel] add Android 15
  products/pixel.md
Labels: release-updates

#6058 [graalvm] update jdk-23 (23.0.1)
  products/graalvm.md
Labels: release-updates

#5948 [samsungmobile] Mark various devices as EOL
  products/samsungmobile.md
Labels: product-updates

#5993 [new product] Hashicorp Packer
  products/hashicorp-packer.md
Labels: new-product

#6066 [prometheus] add 2.55 release
  products/prometheus.md
Labels: release-updates

#6057 [mattermost] add 10.1
  products/mattermost.md
Labels: release-updates

#6067 [grafana] add 11.3
  products/grafana.md
Labels: release-updates

#6089 Fixing declarations of Eclipse Jetty
  products/eclipse-jetty.md
Labels: product-updates

#6060 [iphone] Mark 15 Pro, 15 Pro Max as discontinued
  products/iphone.md
Labels: release-updates

#6093 [samsungmobile] Fix Galaxy A35 and A55 EOL dates
  products/samsungmobile.md
Labels: release-updates

#6094 [spring boot] add purl identifiers
  products/spring-boot.md
Labels: product-updates

#6096 [graylog] Add 6.1
  products/graylog.md
Labels: release-updates

#6097 [kuma] Add 2.9
  products/kuma.md
Labels: release-updates

#6098 [openssl] Add 3.4
  products/openssl.md
Labels: release-updates

#6063 [nextjs] Add 15, Update eol 13
  products/nextjs.md
Labels: release-updates

#6126 [quarkus] add 3.16
  products/quarkus.md
Labels: release-updates

#6123 [aks] Update azure-kubernetes-service.md for K8s 1.30, 1.31, 1.32
  products/azure-kubernetes-service.md
Labels: release-updates

#6124 [vmware-vcenter] updates for 6.5/6.7/7.0/8.0
  products/vmware-vcenter.md
Labels: release-updates
