Repository endoflife-date/endoflife.date, pull requests merged in 2025-02, with the labels that each got.

#6685 [redis] fix broken link
  products/redis.md
Labels: release-updates

#6687 [eks] Add 1.32 and update prior version info
  products/eks.md
Labels: release-updates

#6688 [drush] Document Drush's Drupal 6 version support
  products/drush.md
Labels: product-fixes

#6689 [unity3d] add 2022.3.57f1
  products/unity.md
Labels: release-updates

#6693 [pnpm] 10.2.0 released
  products/pnpm.md
Labels: release-updates

#6691 [rocket-chat] Add 7.3
  products/rocket-chat.md
Labels: release-updates

#6694 [eks] add missing eol and eoes
  products/eks.md
Labels: release-updates

#6699 [cert-manager] Add 1.17, update 1.15 eol
  products/cert-manager.md
Labels: release-updates

#6698 [argocd] Add 2.14
  products/argocd.md
Labels: release-updates

#6695 [wagtail] Add 6.4
  products/wagtail.md
Labels: release-updates

#6696 [nexusRepo] Add 3.76, update release table
  products/nexus.md
Labels: release-updates, product-updates

#6705 [django] 5.1.6 released
  products/django.md
Labels: release-updates

#6715 [unity] Add 6000.0.37f1
  products/unity.md
Labels: release-updates

#6528 [ipados] Update EOL ipadOS 16
  products/ipados.md
Labels: release-updates

#6719 [coder] Add 2.19
  products/coder.md
Labels: release-updates

#6718 [confluence] Add 9.3, use changelogTemplate instead of links
  products/confluence.md
Labels: release-updates, product-updates

#6723 [spring-boot] 3.3.x series also support java 23
  products/spring-boot.md
Labels: release-updates

#6726 [opensearch] Fix auto configuration
  products/opensearch.md
Labels: auto

#6727 [powershell] Update auto configuration
  products/powershell.md
Labels: auto

#6722 [openwrt] add 24.10
  products/openwrt.md
Labels: release-updates

#6730 [redis] Automate EOL retrieval
  products/redis.md
Labels: auto

#5876 [new product] VirtualBox
  products/virtualbox.md
Labels: new-product

#6735 [react-native] 0.75.5
  products/react-native.md
Labels: release-updates

#6736 [react-native] 0.76.7
  products/react-native.md
Labels: release-updates

#6743 [kde-plasma] 6.3.0 released
  products/kdeplasma.md
Labels: release-updates

#6746 [go] add go 1.24 release
  products/go.md
Labels: release-updates

#6745 [openssl] Add the latest openssl releases
  products/openssl.md
Labels: release-updates

#6742 [msexchange] Update 2019 CU15
  products/msexchange.md
Labels: release-updates

#6747 [kde-plasma] add 6.2's eol dates
  products/kdeplasma.md
Labels: release-updates

#6752 [mssharepoint] Update latest Subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#6112 [jquery] Add support column and paragraph for HeroDevs.
  products/jquery.md
Labels: product-updates

#5933 [new product] rtpengine
  products/rtpengine.md
Labels: new-product

#6756 [nexus] add 3.77
  products/nexus.md
Labels: release-updates

#6755 [gke] add 1.32 and update eol for 1.29/1.27
  products/gke.md
Labels: release-updates

#6753 [podman] add 5.4 and eol 5.3
  products/podman.md
Labels: release-updates

#6754 [apache-camel] add 4.10 and eol 4.9
  products/apache-camel.md
Labels: release-updates

#6763 [unity] add 2022.3.58f1
  products/unity.md
Labels: release-updates

#6758 [pan-os]Update PAN-OS version(s)
  products/pan-os.md
Labels: release-updates

#6764 [mariadb] add 11.7 and eol 11.6
  products/mariadb.md
Labels: release-updates

#6768 [mssqlserver] Update 2019 CU31
  products/mssqlserver.md
Labels: release-updates

#6770 [unity] add 6000.0.38f1
  products/unity.md
Labels: release-updates

#6771 [react-native] Add 0.77.1
  products/react-native.md
Labels: release-updates

#6772 [pan-os]Update PAN-OS version(s)
  products/pan-os.md
Labels: release-updates

#6769 [vmware-esxi] Add 5.1, 5.0
  products/vmware-esxi.md
Labels: release-updates

#6773 [virtualbox] 7.1.6 and 7.0.24
  products/virtualbox.md
Labels: release-updates

#6774 [virtualbox] fix 7.1.6's date
  products/virtualbox.md
Labels: release-updates

#6775 [electron] 33.4.1 release
  products/electron.md
Labels: release-updates

#6449 [new product] Deno
  products/deno.md
Labels: new-product

#6785 [yocto] Fix ChangelogTemplate
  products/yocto.md
Labels: product-fixes

#6794 [firefox] Fixes 404 for .0 minor version
  products/firefox.md
Labels: product-fixes

#6797 [tails] Update last release 6.12
  products/tails.md
Labels: release-updates

#6796 [watchos] EOL watchOS 10
  products/watchos.md
Labels: product-fixes

#6778 [azure-devops] Update 2022.2patch3
  products/azure-devops.md
Labels: release-updates

#6798 [ipad] Make release cycle names unique again
  products/ipad.md
Labels: product-fixes

#6800 [firefox] remove .0 workaround link from 135
  products/firefox.md
Labels: release-updates

#6162 [new product] add apache-ant
  products/apache-ant.md
Labels: new-product

#6054 [new-product] Add Guzzle
  products/guzzle.md
Labels: new-product

#6808 [react-native] 0.78 released
  products/react-native.md
Labels: release-updates

#6787 [Gitlab] Add 17.9
  products/gitlab.md
Labels: release-updates

#6807 [guzzle] Automate latest release updates
  products/guzzle.md
Labels: auto

#6819 [unity] Add 6000.0.39f1
  products/unity.md
Labels: release-updates

#6822 [flux] Adds 2.5.0
  products/flux.md
Labels: release-updates

#6823 [meilisearch] Adds 1.13
  products/meilisearch.md
Labels: release-updates

#6820 [prometheus] Adds 3.20
  products/prometheus.md
Labels: release-updates

#6817 [rust] Adds 1.85, and 2024 Edition
  products/rust.md
Labels: release-updates

#6814 api-platform: fix maintenance policy and fix eol state of releases
  products/api-platform.md
Labels: product-fixes

#6813 [redhat-jboss-eap] Update to the latest for JBoss 7.4 and 8.0
  products/red-hat-jboss-eap.md
Labels: release-updates

#6829 [rtpengine] Add 13.2
  products/rtpengine.md
Labels: release-updates

#6824 [apache-hop] Add 2.12
  products/apache-hop.md
Labels: release-updates

#6827 [deno] Add 2.2 and align releases with description
  products/deno.md
Labels: release-updates, product-updates

#6828 [docker-engine] Add 28.0
  products/docker-engine.md
Labels: release-updates

#6831 [rtpengine] Fix eol date for 13.0
  products/rtpengine.md
Labels: product-fixes

#6832 [akeneo-pim] Remove broken link
  products/akeneo-pim.md
Labels: product-fixes

#6833 [firefox] Fix eol date for 115 ESR
  products/firefox.md
Labels: product-updates

#6016 [new-product]: vitess
  products/vitess.md
Labels: new-product

#6122 [new-product] Add express
  products/express.md
Labels: new-product

#6838 [bun] Fix purl link of github
  products/bun.md
Labels: product-fixes

#6834 [alibaba-dragonwell] remove 404 links
  products/alibaba-dragonwell.md
Labels: product-fixes

#6845 [unity] Add 6000.0.40f1
  products/unity.md
Labels: release-updates

#6846 [gradle] 8.13 released
  products/gradle.md
Labels: release-updates

#6851 [citrix-apps-desktops] Update 2402 CU2
  products/citrix-apps-desktops.md
Labels: release-updates

#6857 [ruby] remove temporary link from 3.4.x
  products/ruby.md
Labels: release-updates, product-fixes

#6856 Upgrade Ruby to 3.4.2
  .ruby-version
Labels: enhancement

#6861 [quarkus] add 3.19 release and eol adjust
  products/quarkus.md
Labels: release-updates

#6860 [terraform] add 1.11 release
  products/terraform.md
Labels: release-updates

#6859 Added icons to some products
  products/arangodb.md
  products/bazel.md
  products/fairphone.md
  products/jhipster.md
  products/kong-gateway.md
  products/kuma.md
  products/moodle.md
  products/nomad.md
  products/nuxt.md
  products/phpbb.md
  products/sourcegraph.md
Labels: product-updates

#6853 [keycloak] Adds note about JS adapter
  products/keycloak.md
Labels: product-fixes

#6843 [mautic] Document commercial long term support
  products/mautic.md
Labels: product-updates
