Repository endoflife-date/endoflife.date, pull requests merged in 2025-01, with the labels that each got.

#6496 [Godot] 4.x releases support status updated
  products/godot.md
Labels: release-updates

#5761 [new product] eslint
  products/eslint.md
Labels: new-product

#6498 [linux] version and releaseimage update
  products/linuxkernel.md
Labels: release-updates

#5981 [new-product] Add Backdrop
  products/backdrop.md
Labels: new-product

#6286 Fix stale schema
  product-schema.json
Labels: product-updates

#6501 Update freebsd.md
  products/freebsd.md
Labels: release-updates

#6503 Update ruby dependencies
  Gemfile.lock
Labels: dependencies, ruby

#6048 [node.js] Add new commercial support column.
  products/nodejs.md
Labels: product-fixes

#6505 [samsungmobile] Add Galaxy A16
  products/samsungmobile.md
Labels: release-updates

#6509 [prometheus] add 3.1
  products/prometheus.md
Labels: release-updates

#6510 [emberjs] add 6.0 and 6.1
  products/emberjs.md
Labels: release-updates

#6471 [new product] Mondoo cnspec
  products/cnspec.md
Labels: new-product

#6516 [forgejo] Fix product
  products/forgejo.md
Labels: product-fixes

#6517 [debian] Fix broken links
  products/debian.md
Labels: product-fixes

#6515 [mongodb] Fix broken links
  products/mongodb.md
Labels: product-fixes

#6514 [nvm] Fix changelogTemplate
  products/nvm.md
Labels: product-fixes

#6513 [vmware-esxi] Fix broken link
  products/vmware-esxi.md
Labels: product-fixes

#6511 [kotlin] Fix release date for 2.1 series
  products/kotlin.md
Labels: release-updates, product-fixes

#6523 Make sass silent for deprecation warnings
  _config.yml
Labels: enhancement, product-fixes

#6530 jetty: update latest 9.4
  products/eclipse-jetty.md
Labels: release-updates

#6533 [kotlin] Fix release date Kotlin 2.1.0
  products/kotlin.md
Labels: release-updates

#6535 [cakephp] Add latest release for 4.5 cycle
  products/cakephp.md
Labels: release-updates

#6532 [rust] Add rust 1.84
  products/rust.md
Labels: release-updates

#6526 [CFEngine] Version 3.25.0 (non-LTS) released
  products/cfengine.md
Labels: release-updates

#6537 [Android] Add Api Level information
  products/android.md
Labels: enhancement, release-updates

#6543 [Debian] 12.9 released
  products/debian.md
Labels: release-updates

#6196 [new product] Add Apple tvOS
  products/apple-tvos.md
Labels: new-product

#6544 [linux] 6.12.9 released
  products/linuxkernel.md
Labels: release-updates

#6166 [azure-kubernetes] Add eoas date to Azure Kubernetes 1.30
  products/azure-kubernetes-service.md
Labels: release-updates

#5952 [new product] big-ip
  products/big-ip.md
Labels: new-product

#6512 [salt] Fix broken links
  products/salt.md
Labels: product-fixes

#6548 [godot] Fix changelogTemplate
  products/godot.md
Labels: product-fixes

#6546 [apache-couchdb] Update links
  products/apache-couchdb.md
Labels: product-updates

#6547 [ghc] Fix old releases link
  products/ghc.md
Labels: product-fixes

#6550 [apache-kafka] Update 3.5 and 3.6 release link
  products/apache-kafka.md
Labels: product-updates

#6549 [weechat] Switch to GitHub for changelog
  products/weechat.md
Labels: product-fixes

#6551 [unity] Drop releaseImage
  products/unity.md
Labels: product-updates

#6554 Ignore a few links during validation
  _plugins/product-data-validator.rb
Labels: chore

#6552 [qt] Fix 4.8 link
  products/qt.md
Labels: product-updates

#6553 [red-hat-jboss-eap] Fix 4.2 link
  products/red-hat-jboss-eap.md
Labels: product-updates

#6557 [Qt] Add 6.5.8 Lts version
  products/qt.md
Labels: release-updates

#6525 [new product] add valkey
  products/valkey.md
Labels: new-product

#6568 [docker-engine] add 27.5
  products/docker-engine.md
Labels: release-updates

#6574 [traefik] add 3.3
  products/traefik.md
Labels: release-updates

#6573 [rocket-chat] add 7.2
  products/rocket-chat.md
Labels: release-updates

#6569 [firefox] add 134
  products/firefox.md
Labels: release-updates

#6567 [citrix-apps-desktops] Update 2203 CU6
  products/citrix-apps-desktops.md
Labels: release-updates

#6571 [opentofu] add 1.9
  products/opentofu.md
Labels: release-updates

#6556 [electron] Fix needed node version info
  products/electron.md
Labels: release-updates

#6581 [mssharepoint] Update latest Subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#6570 [looker] add 25.0
  products/looker.md
Labels: release-updates

#6572 [openzfs] add 2.3 and update 2.2
  products/openzfs.md
Labels: release-updates

#6583 [envoy] add 1.33
  products/envoy.md
Labels: release-updates

#6592 [GoLang] 1.23.5 released
  products/go.md
Labels: release-updates

#6597 [mssqlserver] Update 2022 CU17
  products/mssqlserver.md
Labels: release-updates

#6600 [samsungmobile] Add A24
  products/samsungmobile.md
Labels: release-updates

#6589 [nokia] fix broken link
  products/nokia.md
Labels: product-fixes

#6590 [pop_os] Fixed broken link for 21.10
  products/pop_os.md
Labels: product-fixes

#6601 [keycloak] add 26.1 and eol 26.0
  products/keycloak.md
Labels: release-updates

#6603 [oracle-apex] add 24.2
  products/oracle-apex.md
Labels: release-updates

#6602 [mattermost] add 10.4
  products/mattermost.md
Labels: release-updates

#6609 [FairPhone] Add Android 14 to supported Android List for FP5
  products/fairphone.md
Labels: release-updates

#6610 [linux] 6.13 series released
  products/linuxkernel.md
Labels: release-updates

#6612 [jira] Mark 10.3 as LTS
  products/jira.md
Labels: release-updates

#6593 [apache-spark] Update 3.5 as LTS release, 3.4 as EoL
  products/apache-spark.md
Labels: release-updates

#6615 [nvidia-driver] Update latest R550
  products/nvidia-driver.md
Labels: release-updates

#6527 [ios] Update EOL for iphones using iOS 16
  products/iphone.md
Labels: release-updates

#6595 [samsungmobile] Update A42 & A51 EOL
  products/samsungmobile.md
Labels: release-updates

#6621 [electron] Add electron 34
  products/electron.md
Labels: release-updates

#6622 [linux] fix release date
  products/linuxkernel.md
Labels: release-updates

#6629 [forgejo] Add 10.0
  products/forgejo.md
Labels: release-updates

#6624 [linuxmint] Add 22.1
  products/linuxmint.md
Labels: release-updates

#6630 [reactNative] 0.77 releasesd
  products/react-native.md
Labels: release-updates

#6607 Bump python version to 3.11
  runtime.txt
Labels: enhancement

#6634 [springboot] 3.4.2 released
  products/spring-boot.md
Labels: release-updates

#6635 [clamav] Update 1.4 LTS and eol
  products/clamav.md
Labels: release-updates

#6638 [jira] add 10.4
  products/jira.md
Labels: release-updates

#6639 [plesk] add 18.0.67
  products/plesk.md
Labels: release-updates

#6637 [hashicorp-packer] add 1.12, eol 1.9
  products/hashicorp-packer.md
Labels: release-updates

#6636 [nix] add 2.26 and eol 2.25
  products/nix.md
Labels: release-updates

#6640 [nix] Fix EOL dates and update EOL definition
  products/nix.md
Labels: release-updates, product-fixes

#6605 [ruby] move changelog to github
  products/ruby.md
Labels: release-updates

#6642 [graalvm] update 17,21,23 and update lts status for jdk17 and jdk21
  products/graalvm.md
Labels: release-updates, product-fixes

#6644 [Neo4j] 5.26 became LTS
  products/neo4j.md
Labels: release-updates

#6650 [unity3d] update to 6000.0.35f1
  products/unity.md
Labels: release-updates

#6651 [react-native] 0.74.7 released and in the same time it 0.74.x became eol
  products/react-native.md
Labels: release-updates

#6656 [kotlin] add 2.1.10
  products/kotlin.md
Labels: release-updates

#6658 [Quarkus] Add Explaination of New Release Cadence
  products/quarkus.md
Labels: release-updates

#6657 [nvidia-driver] Add R570, sync with releases.json
  products/nvidia-driver.md
Labels: release-updates

#6667 [unity3d] 6000.0.36f1
  products/unity.md
Labels: release-updates

#6668 [Quarkus] New release cycle 3.18 added
  products/quarkus.md
Labels: release-updates

#6665 [opnsense] add 25.1
  products/opnsense.md
Labels: release-updates

#6666 [grafana] add 11.5
  products/grafana.md
Labels: release-updates

#6671 [pan-gp] Updated GlobalProtect App to version 6.2.7
  products/pan-gp.md
Labels: release-updates

#6645 [new product] julia
  products/julia.md
Labels: new-product

#6675 [react] merge 18.x
  products/react.md
Labels: release-updates, product-fixes

#6674 [powershell] add 7.5
  products/powershell.md
Labels: release-updates

#6677 [Powershell] update 4.7.4
  products/powershell.md
Labels: release-updates

#6683 [vmware-esxi] Update latest releases and links
  products/vmware-esxi.md
Labels: release-updates
