Repository endoflife-date/endoflife.date, pull requests merged in 2025-09, with the labels that each got.

#8316 [wordpress] Remove rapidfort purl for dockerhub
  products/wordpress.md
Labels: product-fixes

#8315 [nix] Fixes broken link for 2.31 cycle
  products/nix.md
Labels: product-fixes

#8318 Drop Spotlight mention from README
  README.md
Labels: documentation

#8321 [kibana] Fix links for 9.0 cycle
  products/kibana.md
Labels: product-fixes

#8334 [electron] Add 38.0 cycle
  products/electron.md
Labels: release-updates

#8337 [unity] Add 6000.0.57f1
  products/unity.md
Labels: release-updates

#8332 [SUSE Manager] Update 4.3, 5.0 and 5.1 patch releases and rename product title
  products/suse-manager.md
Labels: release-updates, product-updates

#8348 [emberjs] Add 6.6
  products/emberjs.md
Labels: release-updates

#8351 [rocket-chat] Add 7.10
  products/rocket-chat.md
Labels: release-updates

#8352 [samsung-mobile] Add galaxy-a07
  products/samsung-mobile.md
Labels: release-updates

#8347 [docker-engine] Add 28.4
  products/docker-engine.md
Labels: release-updates

#8349 [linuxmint] Add 22.2
  products/linuxmint.md
Labels: release-updates

#8350 [neo4j] Add 2025.08
  products/neo4j.md
Labels: release-updates

#8342 [amazon-neptune] Display upgradeVersion directly in the main table
  products/amazon-neptune.md
Labels: product-updates

#8343 [amazon-neptune] Add 1.4.6.0
  products/amazon-neptune.md
Labels: release-updates

#8345 [cnspec] Add 12
  products/cnspec.md
Labels: release-updates

#8341 [sles] Fix 15.6 eol and eoes dates
  products/sles.md
Labels: release-updates

#8361 [bitbucket] Add 10.0 cycle
  products/bitbucket.md
Labels: release-updates

#8363 [kuma] Switch auto-update to github_releases instead of git
  products/kuma.md
Labels: release-updates, auto

#8364 [meilisearch] Add 1.20
  products/meilisearch.md
Labels: release-updates

#8362 [apache-pulsar] Add 4.1
  products/apache-pulsar.md
Labels: release-updates

#8368 Update apache-activemq.md
  products/apache-activemq.md
Labels: release-updates

#8370 Auto-adjust warning threshold
  CONTRIBUTING.md
  _config.yml
  _layouts/product.html
  _plugins/product-data-enricher.rb
  _plugins/product-data-validator.rb
  products/akeneo-pim.md
  products/angular.md
  products/arangodb.md
  products/coder.md
  products/gitlab.md
  products/ldap-account-manager.md
  products/mattermost.md
  products/plesk.md
  products/postmarketos.md
  products/prometheus.md
  products/rancher.md
  products/red-hat-satellite.md
  products/silverstripe.md
  products/vmware-cloud-foundation.md
Labels: enhancement

#8379 [telegraph] Add 1.36
  products/telegraf.md
Labels: release-updates

#8377 [contour] Add 1.33
  products/contour.md
Labels: release-updates

#8378 [kuma] Add 2.12
  products/kuma.md
Labels: release-updates

#8371 [New Product] : Gleam
  products/gleam.md
Labels: new-product

#8419 Fix addedAt dates
  products/gleam.md
  products/openbao.md
Labels: product-updates, chore

#8420 [motorola-mobility] Add motorola-edge-60-neo, moto-g06-power and moto-g06
  products/motorola-mobility.md
Labels: release-updates

#8423 [libreoffice] Ignore prereleases
  products/libreoffice.md
Labels: auto

#8433 [ios] Set up product icon
  products/ios.md
Labels: product-updates

#8446 [amazon-eks] Update auto configuration
  products/amazon-eks.md
Labels: auto

#8437 [fluentbit] Set up product icon
  products/fluent-bit.md
Labels: product-updates

#8450 Disable auto update for discontinued products
  products/angularjs.md
  products/eurolinux.md
Labels: auto

#8448 [apache-pulsar] Add changelogTemplate
  products/apache-pulsar.md
Labels: product-updates

#8452 [nexus] Add 3.84
  products/nexus.md
Labels: release-updates

#8449 [chef-infra-client] Revert latest for 14 to 14.15.6
  products/chef-infra-client.md
Labels: release-updates

#8394 [tvos] Add 26
  products/apple-tvos.md
Labels: release-updates

#8392 [macos] Add 26
  products/macos.md
Labels: release-updates

#8219 [iPadOS] Add iPadOS 26
  products/ipados.md
Labels: release-updates

#8393 [visionos] Add 26
  products/visionos.md
Labels: release-updates

#8395 [watchos] Add 26
  products/watchos.md
Labels: release-updates

#8467 [macos] Add changelogTemplate
  products/macos.md
Labels: product-updates

#8465 [watchos] Drop eoas column
  products/watchos.md
Labels: release-updates, breaking-change, product-updates

#8487 [eclipse-jetty]: rename release cycle 12 to 12.0 to fix conflicts
  products/eclipse-jetty.md
Labels: release-updates, breaking-change

#8483 [oracle-graalvm] Add 25
  products/oracle-graalvm.md
Labels: release-updates

#8473 [oracle-jdk] Add 25
  products/oracle-jdk.md
Labels: release-updates

#8475 [godot] Add 4.5
  products/godot.md
Labels: release-updates

#8474 [firefox] Add 143
  products/firefox.md
Labels: release-updates

#8482 [azul-zulu] Add 25 and update latest LTS releases
  products/azul-zulu.md
Labels: release-updates

#8478 [meilisearch] Add 1.21
  products/meilisearch.md
Labels: release-updates

#8477 [mattermost] Add 10.12
  products/mattermost.md
Labels: release-updates

#8492 [varnish] Add 8.0
  products/varnish.md
Labels: release-updates

#8499 [grails] Mark 5 as EOL
  products/grails.md
Labels: release-updates

#8511 [tails] Add 7
  products/tails.md
Labels: release-updates

#8503 [api-platform] Add 4.2
  products/api-platform.md
Labels: release-updates

#8508 [harbor] Add 2.14 and switch to github_releases
  products/harbor.md
Labels: release-updates

#8509 [kubernetes-csi-node-driver-registrar] Add 2.15
  products/kubernetes-csi-node-driver-registrar.md
Labels: release-updates

#8510 [rust] Add 1.90
  products/rust.md
Labels: release-updates

#8526 [tomcat] Update auto configuration
  products/tomcat.md
Labels: auto

#8527 [alibaba-ack] Update auto configuration
  products/alibaba-ack.md
Labels: auto

#8528 [apache-camel] Update auto-configuration
  products/apache-camel.md
Labels: auto

#8523 [ipad] Update releases
  products/ipad.md
Labels: release-updates

#8532 [office] Drop Office 365
  products/office.md
Labels: release-updates

#8516 [hbase] Mark 2.4 as EOL
  products/hbase.md
Labels: release-updates

#8517 [intel-processor] Mark apollo-lake as discontinued
  products/intel-processors.md
Labels: release-updates

#8518 [intel-processors] Mark rocket-lake as discontinued
  products/intel-processors.md
Labels: release-updates

#8522 [intel-processors] Mark comet-lake as discontinued
  products/intel-processors.md
Labels: release-updates

#8524 [jquery] Add link to the security policy
  products/jquery.md
Labels: release-updates

#8541 [apple-watch] Update stale release threshold to 6 years
  products/apple-watch.md
Labels: chore

#8544 [iphone] Update stale release threshold to 8 years
  products/iphone.md
Labels: chore

#8543 [iphone] Update supportedIosVersions for IPhone 16 models
  products/iphone.md
Labels: release-updates

#8545 [kindle] Update latest firmware releases
  products/kindle.md
Labels: release-updates

#8537 [eclipse-temurin] Add new LTS (25)
  products/eclipse-temurin.md
Labels: release-updates

#8561 [grafana] Add 12.2
  products/grafana.md
Labels: release-updates

#8568 [postgresql] add 18
  products/postgresql.md
Labels: release-updates

#8566 [pan-gp] Update 6.3 release data with 6.3.3-c711
  products/pan-gp.md
Labels: release-updates

#8571 [quarkus-framework] Add 3.28 and 3.27 LTS
  products/quarkus-framework.md
Labels: release-updates

#8570 [jira-software] add 11.1
  products/jira-software.md
Labels: release-updates

#8567 [meilisearch] add 1.22 and eol 1.21
  products/meilisearch.md
Labels: release-updates

#8569 [fluent-bit] add 4.1 and eol 4.0
  products/fluent-bit.md
Labels: release-updates

#8575 [boundary] Switch to github_releases for automation
  products/boundary.md
Labels: release-updates, auto

#8576 [boundary] Add 0.20
  products/boundary.md
Labels: release-updates

#8578 [kubernetes-csi-node-driver-registrar] Update product
  products/kubernetes-csi-node-driver-registrar.md
Labels: release-updates, product-updates
