Repository endoflife-date/endoflife.date, pull requests merged in 2025-07, with the labels that each got.

#7808 [msexchange] Add subscription edition
  products/msexchange.md
Labels: release-updates

#7732 [ipad] Align custom column with iPhone
  products/ipad.md
Labels: breaking-change, product-updates

#7820 [oracle-jdk] Stop using javascript for fetching https://www.java.com/releases/
  products/oracle-jdk.md
Labels: auto

#7816 add SLE 15 SP7, fix EOL/EOES dates for SLE 15 SP6
  products/sles.md
Labels: release-updates

#7814 [unity] Add 6000.1.10 and 6000.0.52
  products/unity.md
Labels: release-updates

#7801 [pan-os]Update PAN-OS version(s)
  products/pan-os.md
Labels: release-updates

#7825 [mediawiki] Add 1.44
  products/mediawiki.md
Labels: release-updates

#7824 [keycloak] Add 26.3
  products/keycloak.md
Labels: release-updates

#7822 [azure-kubernetes-service] Add 1.33
  products/azure-kubernetes-service.md
Labels: release-updates

#7815 [Shopware] Add supported PHP versions info for 6.7 cycle
  products/shopware.md
Labels: release-updates

#7830 [oracle-jdk] Use javascript for fetching https://www.java.com/releases/
  products/oracle-jdk.md
Labels: auto

#7788 [emberjs] Add 6.5 Series
  products/emberjs.md
Labels: release-updates

#7794 [elastic] Update products description
  products/beats.md
  products/elasticsearch.md
  products/kibana.md
  products/logstash.md
Labels: product-updates

#7827 [rtpengine] Add 13.4
  products/rtpengine.md
Labels: release-updates

#7835 [emberjs] Fix dupliated lts tag by mistake though autoscript
  products/emberjs.md
Labels: product-fixes

#7831 [deno] Add 2.4, fix 2.1 and 2.2
  products/deno.md
Labels: release-updates

#7841 [firefox] Fix eol date for ESR 115
  products/firefox.md
Labels: release-updates

#7846 [mastodon] Adds 4.4
  products/mastodon.md
Labels: release-updates

#7848 [sharepoint] Update latest Subscription, 2019, 2016
  products/sharepoint.md
Labels: release-updates

#7851 [artifactory] Fix auto configuration
  products/artifactory.md
Labels: bug, auto

#7855 [unity] Add 6000.0.53 and 6000.1.11
  products/unity.md
Labels: release-updates

#7862 Rename latest.py to update-product-data.py
  .github/workflows/auto-merge-release-updates.yml
  _auto/deploy.sh
  _plugins/product-data-validator.rb
  products/pan-os.md
Labels: chore

#7837 [fairphone] Remove Android versions that aren't yet released on the FP6
  products/fairphone.md
Labels: release-updates

#7859 [pan-os]Update PAN-OS version(s)
  products/pan-os.md
Labels: release-updates

#7867 [apache-camel] Add 4.13
  products/apache-camel.md
Labels: release-updates

#7869 [nexus] Add 3.82
  products/nexus.md
Labels: release-updates

#7870 [plesk] Add 18.0.71
  products/plesk.md
Labels: release-updates

#7873 [thumbor] Set addedAt
  products/thumbor.md
Labels: chore

#7662 New Product - Chef Supermarket
  products/chef-supermarket.md
Labels: new-product

#7880 [vmware-esxi] Update latest 8.0 Update 3f, 7.0 Update 3w
  products/vmware-esxi.md
Labels: release-updates

#7890 [forgejo] Add 12.0 cycle
  products/forgejo.md
Labels: release-updates

#7895 [mattermost] Add 10.10
  products/mattermost.md
Labels: release-updates

#7894 [gitlab] Add 18.2
  products/gitlab.md
Labels: release-updates

#7900 [chrome] Rename to Google Chrome
  products/chrome.md
Labels: release-updates

#7903 [weechat] Add 4.7.x cycle
  products/weechat.md
Labels: release-updates

#7898 [new-product] Adds new product - ClearLinux
  products/clearlinux.md
Labels: new-product

#7901 Add Date of addedAt into guide
  CONTRIBUTING.md
Labels: release-updates

#7912 [grafana] Fix 10.4 eoas
  products/grafana.md
Labels: release-updates

#7911 [firefox] Add 141
  products/firefox.md
Labels: release-updates

#7907 [looker] Remove support images
  products/looker.md
Labels: product-updates

#7927 [envoy] Automate releaseDate retrieval
  products/envoy.md
Labels: auto

#7920 [unity] Add 6000.1.13 and 6000.0.54
  products/unity.md
Labels: release-updates

#7914 Add bot page
  bot.md
Labels: documentation

#7929 [mysql] Add 9.4
  products/mysql.md
Labels: release-updates

#7930 [opnsense] Add 25.7
  products/opnsense.md
Labels: release-updates

#7928 [grafana] Add 12.1
  products/grafana.md
Labels: release-updates

#7926 [envoy] Add 1.35
  products/envoy.md
Labels: release-updates

#7925 [apache-nifi] Add 2.5
  products/apache-nifi.md
Labels: release-updates

#7938 [motorola-mobility] Configure automation
  products/motorola-mobility.md
Labels: auto

#7941 [gatekeeper] Add 3.20.x cycle
  products/gatekeeper.md
Labels: release-updates

#7935 [wordpress] Remove 404 link for ancient 4.6 cycle release
  products/wordpress.md
Labels: product-fixes

#7817 [new-product] AWS MSK
  products/amazon-msk.md
Labels: new-product

#7957 [nuxt] Update auto-configuration
  products/nuxt.md
Labels: auto

#7958 [unity] Add 6000.1.14
  products/unity.md
Labels: release-updates

#7965 [quarkus-framework] Add 3.25
  products/quarkus-framework.md
Labels: release-updates

#7972 [mattermost] Update auto configuration
  products/mattermost.md
Labels: auto

#7178 [new-product] Add tarteaucitron
  products/tarteaucitron.md
Labels: new-product

#7970 [gradle] Add 9
  products/gradle.md
Labels: release-updates

#7971 [neo4j] Add 2025.07
  products/neo4j.md
Labels: release-updates
