Repository endoflife-date/endoflife.date, pull requests merged in 2025-05, with the labels that each got.

#7299 [SAMSUNG Mobile] EOL device Update A32, M12, F12
  products/samsungmobile.md
Labels: release-updates

#7306 [sourcegraph] Remove broken links
  products/sourcegraph.md
Labels: product-fixes

#7313 [vitess] Add 22
  products/vitess.md
Labels: release-updates

#7312 [pan-cortex-xdr] Add 8.8
  products/pan-cortex-xdr.md
Labels: release-updates

#7311 [opensearch] Add 3
  products/opensearch.md
Labels: release-updates

#7309 [firefox] Add 138
  products/firefox.md
Labels: release-updates

#7290 [kyverno] Add 1.14
  products/kyverno.md
Labels: release-updates

#7310 [graylog] Add 6.2
  products/graylog.md
Labels: release-updates

#7321 [electron] Fix 36 EOL
  products/electron.md
Labels: bug

#7319 [quarkus] Set EOES for 2.13
  products/quarkus.md
Labels: release-updates

#7318 [quarkus] Add 3.22
  products/quarkus.md
Labels: release-updates

#7316 [deno] Add 2.3
  products/deno.md
Labels: release-updates

#7315 [bamboo] Add 11.0
  products/bamboo.md
Labels: release-updates

#7317 [nutanix-aos] Add 7.1
  products/nutanix-aos.md
Labels: release-updates

#7323 [dotnetfx] Normalize 3.5 SP1 release cycle name
  products/dotnetfx.md
Labels: release-updates, breaking-change

#7326 [intel-processors] Normalize release cycles name
  products/intel-processors.md
Labels: release-updates, breaking-change

#7327 [oneplus] Normalize release cycles name
  products/oneplus.md
Labels: release-updates, breaking-change

#7328 [pan-os] Normalize 9.0-XFR release name
  products/pan-os.md
Labels: release-updates, breaking-change

#7331 [windows-nano-server] Normalize 20H2 release cycle name
  products/windows-nano-server.md
Labels: release-updates, breaking-change

#7330 [windows-embedded] Normalize release cycles' name
  products/windows-embedded.md
Labels: release-updates, breaking-change

#7334 [surface] Normalize release cycles' name
  products/surface.md
Labels: release-updates, breaking-change

#7333 [windows-server] Normalize release cycles' name
  products/windows-server.md
Labels: release-updates, breaking-change

#7336 [nokia] Normalize release cycles' name
  products/nokia.md
Labels: release-updates, breaking-change

#7335 [motorola-mobility] Normalize release cycles' name
  products/motorola-mobility.md
Labels: release-updates, breaking-change

#7339 [samsungmobile] Normalize release cycles' name
  products/samsungmobile.md
Labels: release-updates, breaking-change

#7329 [raspberrypi] Normalize CM* release cycle names
  products/raspberrypi.md
Labels: release-updates, breaking-change

#7322 [android] Improve releases
  products/android.md
Labels: release-updates, breaking-change

#7337 [nvidia-driver] Normalize release cycles' name
  products/nvidia-driver.md
Labels: release-updates, breaking-change

#7338 [nvidia-products] Normalize release cycles' name
  products/nvidia-products.md
Labels: release-updates, breaking-change

#7272 [unity] Add 6000.1.0f1
  products/unity.md
Labels: release-updates

#7340 Force releaseCycle to be unique and adhere to a naming convention
  CONTRIBUTING.md
  _plugins/product-data-validator.rb
  product-schema.json
Labels: enhancement

#7347 Drop explicit Ruby version in check-links.yml
  .github/workflows/check-links.yml
Labels: ruby, github_actions

#7348 Bump project's ruby version from 3.4.2 to 3.4.3
  .ruby-version
Labels: ruby

#6946 Bump python to match with our CI's ubuntu-image's version
  .github/workflows/auto-merge-release-updates.yml
  runtime.txt
Labels: python

#7345 [pan-gp] Updated GlobalProtect 6.3 series to 6.3.3
  products/pan-gp.md
Labels: release-updates

#7073 [rh-openjdk] Update latest releases
  products/red-hat-build-of-openjdk.md
Labels: release-updates

#7351 [surface] Update auto configuration
  products/surface.md
Labels: breaking-change, auto

#7353 [dotnetfx] Update auto configuration
  products/dotnetfx.md
Labels: auto

#7222 [nvidia-products] Added the blackwell cards
  products/nvidia-products.md
Labels: release-updates

#7358 [kyverno] Remove chainguard dockerhub purl
  products/kyverno.md
Labels: product-fixes

#7357 [Samsung Smartphone] bunch of EOL update
  products/samsungmobile.md
Labels: release-updates

#2080 Endoflife api/v1
  .github/workflows/lint.yml
  .gitignore
  CHANGELOG_API.md
  CONTRIBUTING.md
  HACKING.md
  README.md
  _config.yml
  _headers
  _layouts/json.json
  _layouts/product.html
  _layouts/swagger-ui.html
  _plugins/generate-api-v0.rb
  _plugins/generate-api-v1.rb
  _plugins/product-data-enricher.rb
  _redirects
  api_v1/openapi.yml
  api_v1/swagger-ui.md
  assets/404.json
  humans.txt
  index.md
Labels: enhancement

#7013 [new product] ProFTPD
  products/proftpd.md
Labels: new-product

#7365 [magento] Remove repology
  products/magento.md
Labels: product-fixes

#7363 [intel] Update EOL for Kaby Lake and Coffee Lake CPU (#7363)
  products/intel-processors.md
Labels: release-updates

#7369 Align markdown filenames with their respective permalinks
  products/alpine-linux.md
  products/amazon-eks.md
  products/antix-linux.md
  products/argo-cd.md
  products/azure-devops-server.md
  products/citrix-vad.md
  products/dependency-track.md
  products/google-kubernetes-engine.md
  products/jira-software.md
  products/kde-plasma.md
  products/kubernetes-node-feature-discovery.md
  products/linux-kernel.md
  products/nvidia-gpu.md
  products/pop-os.md
  products/quarkus-framework.md
  products/raspberry-pi.md
  products/red-hat-satellite.md
  products/rocky-linux.md
  products/samsung-mobile.md
  products/sharepoint.md
  products/visual-studio.md
  products/vmware-cloud-foundation.md
Labels: chore

#7376 [unity] Add 6000.1.1f1 and 6000.0.48f1
  products/unity.md
Labels: release-updates

#7373 [alpine-linux] Align the permalink with the product name
  products/alpine-linux.md
Labels: product-updates

#7371 [apache-http-server] Align permalink with the title
  products/apache-http-server.md
Labels: product-updates

#7372 [apache-maven] Align permalink with the title
  products/apache-maven.md
Labels: product-updates

#7370 [apache-subversion] Align permalink with the title
  products/apache-subversion.md
Labels: product-updates

#7368 [intel-processors] Set EOL for Gemini Lake
  products/intel-processors.md
Labels: release-updates

#7388 [jenkins] Add 2.504 LTS
  products/jenkins.md
Labels: release-updates

#7387 add Nodejs 24 to releases
  products/nodejs.md
Labels: release-updates

#7374 [samsung-mobile] Fix EOL for a few models
  products/samsung-mobile.md
Labels: release-updates

#7385 [Samsung Smartphone] A14 EOL
  products/samsung-mobile.md
Labels: release-updates

#7383 [cert-manager] Remove duplicate link url
  products/cert-manager.md
Labels: product-fixes

#7389 [samsung-mobile] Revert transformation from '+' to 'plus' in identifiers
  products/samsung-mobile.md
Labels: release-updates, breaking-change

#7390 [samsung-mobile] Align names/labels with samsung EOL page
  products/samsung-mobile.md
Labels: release-updates, breaking-change

#7391 [kuma] Remove duplicate url
  products/kuma.md
Labels: product-fixes

#7394 Update grafana.md
  products/grafana.md
Labels: release-updates

#7396 [grafana] Automate EOL retrieval
  products/grafana.md
Labels: release-updates, auto

#7375 [nutanix] Update release cadence information for Nutanix products
  products/nutanix-aos.md
  products/nutanix-files.md
  products/nutanix-prism.md
Labels: product-updates

#7406 [samsung-mobile] Automate EOL retrieval
  products/samsung-mobile.md
Labels: breaking-change, auto

#7407 [prometheus] remove chainguard's purl for dockerhub
  products/prometheus.md
Labels: product-fixes

#7415 update SUSE Manager 4.3 and 5.0 patch releases
  products/suse-manager.md
Labels: release-updates

#7414 [electron] Fixes Nodejs version info for 3.6 cycle
  products/electron.md
Labels: release-updates

#7404 [wagtail] Add 7.0
  products/wagtail.md
Labels: release-updates

#7403 [traefik] Add 3.4
  products/traefik.md
Labels: release-updates

#7402 [red-hat-satellite] Add 6.17
  products/red-hat-satellite.md
Labels: release-updates

#7401 [contour] Add 1.31
  products/contour.md
Labels: release-updates

#7400 [consul] Add 1.21
  products/consul.md
Labels: release-updates

#7398 [argo-cd] Add 3.0
  products/argo-cd.md
Labels: release-updates

#7359 [New Product] Add samsung-galaxy-watch
  products/samsung-galaxy-watch.md
  products/samsung-mobile.md
Labels: new-product

#7427 [samsung-mobile] Fix Galaxy Xcover5 name and identifier
  products/samsung-mobile.md
Labels: release-updates

#7324 [redis] Redis 8 with new license released
  products/redis.md
Labels: release-updates

#6956 [New product] Plone
  products/plone.md
Labels: new-product

#7055 [new product] LDAP Account Manager
  products/lam.md
Labels: new-product

#7430 [ldap-account-manager] Align the file name with its permalink
  products/ldap-account-manager.md
Labels: chore

#7413 [windows-nano-server] Added info for releaseCycle 2025
  products/windows-nano-server.md
Labels: release-updates

#7419 [nexus] Add 3.80
  products/nexus.md
Labels: release-updates

#7420 [scala] Add 3.7
  products/scala.md
Labels: release-updates

#7421 [yocto] Add 5.2
  products/yocto.md
Labels: release-updates

#7422 [samsung-mobile] Add W25 and W25 Flip
  products/samsung-mobile.md
Labels: release-updates

#7423 [samsung-mobile] Add W24 and W24 Flip
  products/samsung-mobile.md
Labels: release-updates

#7424 [samsung-mobile] Add W23 and W23 Flip
  products/samsung-mobile.md
Labels: release-updates

#7425 [samsung-mobile] Add Galaxy A05 and A05s
  products/samsung-mobile.md
Labels: release-updates

#7426 [samsung-mobile] Add Galaxy A06 and A06 5G
  products/samsung-mobile.md
Labels: release-updates

#7428 [samsung-mobile] Add Galaxy Z Fold6 and Galaxy Z Flip6
  products/samsung-mobile.md
Labels: release-updates

#7432 [samsung-mobile] Revert automated EOL changes
  products/samsung-mobile.md
Labels: release-updates

#7436 [opnsense] Remove repology from purls
  products/opnsense.md
Labels: product-fixes

#7433 [samsung-mobile] Add W22 5G
  products/samsung-mobile.md
Labels: release-updates

#7434 [samsung-mobile] Add Galaxy Z Fold5 and Galaxy Z Flip5
  products/samsung-mobile.md
Labels: release-updates

#7441 [samsung-mobile] Add Galaxy M56 5G
  products/samsung-mobile.md
Labels: release-updates

#7442 [samsung-mobile] Add Galaxy M55 5G and Galaxy M55s 5G
  products/samsung-mobile.md
Labels: release-updates

#7443 [samsung-mobile] Add Galaxy M54 5G and Galaxy M14 5G
  products/samsung-mobile.md
Labels: release-updates

#7444 [samsung-mobile] Update a few models
  products/samsung-mobile.md
Labels: release-updates

#7445 [samsung-mobile] Add Galaxy M44 5G
  products/samsung-mobile.md
Labels: release-updates

#7447 [samsung-mobile] Add Galaxy M34 5G and Galaxy M35 5G
  products/samsung-mobile.md
Labels: release-updates

#7448 [samsung-mobile] Add new Galaxy M devices
  products/samsung-mobile.md
Labels: release-updates

#7449 [samsung-mobile] Add Galaxy C55 5G
  products/samsung-mobile.md
Labels: release-updates

#7450 [samsung-mobile] Add new Galaxy F devices
  products/samsung-mobile.md
Labels: release-updates

#7451 [samsung-mobile] Add new Galaxy A devices
  products/samsung-mobile.md
Labels: release-updates

#7453 [unity] Add 2022.3.62
  products/unity.md
Labels: release-updates

#7464 [rust] Add 10th years of Rust ( 1.87 )
  products/rust.md
Labels: release-updates

#7470 [zerto] Automate release information retrieval
  products/zerto.md
Labels: auto

#7471 [virtualbox] Automate EOL retrieval
  products/virtualbox.md
Labels: auto

#7472 [zerto] Fix auto configuration
  products/zerto.md
Labels: bug, auto

#7469 [neo4j] Add 2025.04
  products/neo4j.md
Labels: release-updates

#7477 [unity] add 6000.1.3f1 and 6000.0.49f1
  products/unity.md
Labels: release-updates

#7482 [terraform] Add 1.12
  products/terraform.md
Labels: release-updates

#7480 [podman] Add 5.5
  products/podman.md
Labels: release-updates

#7483 [visual-studio] Add 17.14
  products/visual-studio.md
Labels: release-updates

#7479 [mattermost] Add 10.8
  products/mattermost.md
Labels: release-updates

#7481 [rocket-chat] Add 7.6
  products/rocket-chat.md
Labels: release-updates

#7476 [eclipse-temurin] Update auto configuration
  products/eclipse-temurin.md
Labels: auto

#7478 [etcd] Add 3.6 and update description
  products/etcd.md
Labels: release-updates

#7473 [cockroachdb] Add 25.2
  products/cockroachdb.md
Labels: release-updates

#7474 [coder] Add 2.22
  products/coder.md
Labels: release-updates

#7475 [contour] Add 1.32
  products/contour.md
Labels: release-updates

#7484 [lineageos] Fix androidVersion values
  products/lineageos.md
Labels: bug

#7485 [vmware-photon] Fix kernelVersion values
  products/vmware-photon.md
Labels: release-updates

#7486 [pixel] Fix supportedAndroidVersions values
  products/pixel.md
Labels: bug

#7487 [pixel-watch] Fix supportedAndroidVersions values
  products/pixel-watch.md
Labels: bug

#7488 [oneplus] Fix supportedOxygenOSVersions values
  products/oneplus.md
Labels: bug

#7490 [apache-camel] Fix supportedJavaVersions values
  products/apache-camel.md
Labels: bug

#7491 [nvidia-gpu] Fix releases' label
  products/nvidia-gpu.md
Labels: product-fixes

#7495 Make custom fields declaration mandatory
  CONTRIBUTING.md
  _config.yml
  _includes/custom-column-td.html
  _layouts/product.html
  _plugins/product-data-validator.rb
  product-schema.json
  products/amazon-glue.md
  products/amazon-neptune.md
  products/android.md
  products/angularjs.md
  products/ansible-core.md
  products/ansible.md
  products/apache-camel.md
  products/apple-watch.md
  products/azul-zulu.md
  products/cakephp.md
  products/django.md
  products/drush.md
  products/eclipse-jetty.md
  products/electron.md
  products/eslint.md
  products/fairphone.md
  products/google-nexus.md
  products/gradle.md
  products/guzzle.md
  products/ionic.md
  products/ipad.md
  products/iphone.md
  products/istio.md
  products/jekyll.md
  products/keda.md
  products/kirby.md
  products/kyverno.md
  products/laravel.md
  products/lineageos.md
  products/magento.md
  products/moodle.md
  products/mssqlserver.md
  products/omnissa-horizon.md
  products/oneplus.md
  products/openzfs.md
  products/pixel-watch.md
  products/pixel.md
  products/plone.md
  products/robo.md
  products/shopware.md
  products/spring-boot.md
  products/spring-framework.md
  products/tomcat.md
  products/vmware-esxi.md
  products/vmware-photon.md
  products/vmware-srm.md
  products/vmware-vcenter.md
  products/wordpress.md
  products/zentyal.md
Labels: enhancement, api

#7492 [apache-airflow] Remove deprecared/removed bitnami purls
  products/apache-airflow.md
Labels: release-updates

#7501 [ansible] Fix custom field values
  products/ansible.md
Labels: release-updates

#7503 [eclipse-jetty] Fix custom field values
  products/eclipse-jetty.md
Labels: release-updates

#7504 [gradle] Fix custom field values
  products/gradle.md
Labels: release-updates

#7505 [ipad] Fix custom field values
  products/ipad.md
Labels: release-updates

#7507 [tomcat] Fix custom field values
  products/tomcat.md
Labels: release-updates

#7509 Update google-kubernetes-engine.md
  products/google-kubernetes-engine.md
Labels: release-updates

#7513 [samsung-galaxy-tab] Move Galaxy Tabs to a dedicated page
  products/samsung-galaxy-tab.md
  products/samsung-galaxy-watch.md
  products/samsung-mobile.md
Labels: new-product, product-updates

#7514 [samsung-mobile][samsung-galaxy-tab] Update auto configuration
  products/samsung-galaxy-tab.md
  products/samsung-mobile.md
Labels: auto

#7516 [zerto] Add 10.0_u7
  products/zerto.md
Labels: release-updates

#7515 [prometheus] Add 3.4
  products/prometheus.md
Labels: release-updates

#7457 [rhel] Add 10.0
  products/rhel.md
Labels: release-updates

#7493 [elasticsearch] Fix broken link for 9.x
  products/elasticsearch.md
Labels: product-fixes

#7494 [beats] Fix broken link for 9.x
  products/beats.md
Labels: product-fixes

#7525 [AlmaLinux] Fix link for cycle 9 for 9.6
  products/almalinux.md
Labels: release-updates

#7499 [pixel] Fix 9a eoas / eol
  products/pixel.md
Labels: release-updates

#7530 [express] Fix link template for 5.x series
  products/express.md
Labels: product-fixes

#7528 [CFEngine] Add 3.26 cycle
  products/cfengine.md
Labels: release-updates

#7462 [android] Add Version Codes
  products/android.md
Labels: release-updates

#7529 [arangodb] Remove 404 link for 2.8
  products/arangodb.md
Labels: product-fixes

#7520 [envoy] Remove chainguard purl for dockerhub purl
  products/envoy.md
Labels: product-fixes

#7546 [unity] Add 6000.1.4
  products/unity.md
Labels: release-updates
