Repository endoflife-date/endoflife.date, pull requests merged in 2025-04, with the labels that each got.

#7088 [vmware-srm] Remove 404 and login required links
  products/vmware-srm.md
Labels: product-fixes

#7094 [firefox] Add 137.0
  products/firefox.md
Labels: release-updates

#7100 [valkey] Add 8.1
  products/valkey.md
Labels: release-updates

#7097 [fluent-bit] Add 4.0
  products/fluent-bit.md
Labels: release-updates

#7096 [cakephp] Add 5.2
  products/cakephp.md
Labels: release-updates

#7106 [mattermost] fix wrong esr release months
  products/mattermost.md
Labels: product-updates

#7104 [Qt] 6.9 Released
  products/qt.md
Labels: release-updates

#7103 [silverstripe] Fix purl for github
  products/silverstripe.md
Labels: product-fixes

#7101 [unity] Add 6000.0.44f1
  products/unity.md
Labels: release-updates

#7109 [coder] Add 2.21
  products/coder.md
Labels: release-updates

#7110 [confluence] Add 9.4
  products/confluence.md
Labels: release-updates

#7108 [apache-apisix] Add 3.12
  products/apache-apisix.md
Labels: release-updates

#7117 [openssl] Add older releases for openssl
  products/openssl.md
Labels: release-updates

#7116 [rust] add 1.86
  products/rust.md
Labels: release-updates

#7114 [redis] Fix broken purls for ubuntu and debian
  products/redis.md
Labels: product-fixes

#7113 [red-hat-jboss-eap] Fix 5.2's link
  products/red-hat-jboss-eap.md
Labels: product-fixes

#7124 [mautic] Add 6.0
  products/mautic.md
Labels: release-updates

#7122 [nexus] Add 3.79
  products/nexus.md
Labels: release-updates

#7121 [apache-camel] Add 4.11
  products/apache-camel.md
Labels: release-updates

#7126 [amazon-corretto] Disable automation for release and EOL dates
  products/amazon-corretto.md
Labels: auto

#7127 [linuxkernel] Switch automation from git.kernel.org to gregkh/linux
  products/linuxkernel.md
Labels: auto

#7128 [red-hat-jboss-eap] Automate release level information retrieval
  products/red-hat-jboss-eap.md
Labels: auto

#7129 [ansible-core] Automate releaseDate and EOL retrieval
  products/ansible-core.md
Labels: auto

#7130 [rhel] Automate release level information retrieval
  products/rhel.md
Labels: auto

#7131 [red-hat-build-of-openjdk] Automate release level information retrieval
  products/red-hat-build-of-openjdk.md
Labels: auto

#7134 Remove erroneous releasedate fields
  products/red-hat-build-of-openjdk.md
  products/red-hat-jboss-eap.md
  products/rhel.md
Labels: product-fixes, chore

#7142 [linux] Update new releaseImage
  products/linuxkernel.md
Labels: release-updates

#7149 [rocket-chat] Add 7.5
  products/rocket-chat.md
Labels: release-updates

#7146 [keda] Add 2.17, update 2.15 eol
  products/keda.md
Labels: release-updates

#7145 [dependencytrack] Add 4.13, update 4.12 eol
  products/dependencytrack.md
Labels: release-updates

#7150 [pan-gp]Updated GlobalProtect App from 6.2.7 to v6.2.8
  products/pan-gp.md
Labels: release-updates

#7137 [apache-airflow] Remove rapidfort purls
  products/apache-airflow.md
Labels: product-fixes

#7136 [apache-couchdb] Fix purl for rapidfort
  products/apache-couchdb.md
Labels: product-fixes

#7135 [unity] Add 6000.0.45f1
  products/unity.md
Labels: release-updates

#7086 [vmware-cloudfoundation] Remove 404 links
  products/vmware-cloudfoundation.md
Labels: product-fixes

#7154 [openssl] Add 3.5.x (new LTS) cycle
  products/openssl.md
Labels: release-updates

#7153 [pnpm] Add eol date for 9.x
  products/pnpm.md
Labels: release-updates

#7162 [react-native] Add 0.79, update eoas, eol
  products/react-native.md
Labels: release-updates

#7161 [magento] Add 2.4.8, update 2.4.7, 2.4.6 eos
  products/magento.md
Labels: release-updates

#7159 [ipad] Update eol for supportedIosVersions 16 and 15
  products/ipad.md
Labels: release-updates

#7158 [iphone] Update eol for supportedIosVersions 16 and 15
  products/iphone.md
Labels: release-updates

#7157 [ipados] Update 16 and 15 eol
  products/ipados.md
Labels: release-updates

#7156 [ios] Update 16 and 15 eol
  products/ios.md
Labels: release-updates

#7165 [tails] Add 6.14.1 version
  products/tails.md
Labels: release-updates

#7170 [silverstripe] add 5.4
  products/silverstripe.md
Labels: release-updates

#7171 [gatekeeper] add 3.19
  products/gatekeeper.md
Labels: release-updates

#7164 [mule-runetime] Update to 4.9
  products/mule-runtime.md
Labels: release-updates

#7175 [mssharepoint] Update latest subscription, 2019, 2016
  products/mssharepoint.md
Labels: release-updates

#7152 [bellsoft-liberica] Remove not working purls
  products/bellsoft-liberica.md
Labels: product-fixes

#7176 [android] 12 and 12.1 series is EOLed
  products/android.md
Labels: release-updates

#7183 [unity] Add 6000.0.46f1
  products/unity.md
Labels: release-updates

#7184 [openssl] Automate EOL retrieval
  products/openssl.md
Labels: auto

#7185 Simplify validation exclusions
  _plugins/product-data-validator.rb
Labels: chore

#6613 [new product] Veeam One
  products/veeam-one.md
Labels: new-product

#7190 [centos] Add missing latestReleaseDate
  products/centos.md
Labels: release-updates

#7189 [ffmpeg] Add missing latestReleaseDate
  products/ffmpeg.md
Labels: release-updates

#7188 [qt] Add missing latestReleaseDate for 4.8
  products/qt.md
Labels: release-updates

#7187 [android] Clarify support policy
  products/android.md
Labels: product-updates

#7186 [veeam-backup-and-replication] Update 12 EOL
  products/veeam-backup-and-replication.md
Labels: release-updates

#7191 [unity] Add 2022.3.61
  products/unity.md
Labels: release-updates

#7196 [harbor] Add 2.13, update 2.10 eol
  products/harbor.md
Labels: release-updates

#7197 [keycloak] Add 26.2, update 26.1 eol
  products/keycloak.md
Labels: release-updates

#7198 [moodle] Add 5.0
  products/moodle.md
Labels: release-updates

#7192 [vmware-esxi] Update 8.0 Update 3e
  products/vmware-esxi.md
Labels: release-updates

#6737 [Netapp ONTAP] new product
  products/netapp-ontap.md
Labels: new-product

#7092 [apache-activemq] fix link for 6.16 release
  products/apache-activemq.md
Labels: product-fixes

#7205 [mysql] add 9.3, eol 9.2
  products/mysql.md
Labels: release-updates

#7206 [meilisearch] add 1.14, eol 1.13
  products/meilisearch.md
Labels: release-updates

#7201 [prometheus] Fix rapidfort purl
  products/prometheus.md
Labels: product-fixes

#7119 [oneplus] Add Oneplus 13 and 13R
  products/oneplus.md
Labels: release-updates

#7219 [wordpress] add 6.8, eol 6.7
  products/wordpress.md
Labels: release-updates

#7217 [rabbitmq] add 4.1, eol 4.0
  products/rabbitmq.md
Labels: release-updates

#7214 [beats, elasticsearch, kibana, logstash] add 9, eol update for 7,8
  products/beats.md
  products/elasticsearch.md
  products/kibana.md
  products/logstash.md
Labels: release-updates

#7216 [gitlab] add 17.11
  products/gitlab.md
Labels: release-updates

#7218 [prometheus] add 3.3
  products/prometheus.md
Labels: release-updates

#7230 [unity] Add 6000.0.47f1
  products/unity.md
Labels: release-updates

#7234 [spring-boot] Add java 24 support for 3.4 series
  products/spring-boot.md
Labels: release-updates

#7233 [spring-framework] Fix java support list
  products/spring-framework.md
Labels: release-updates

#7237 [mattermost] add 10.7
  products/mattermost.md
Labels: release-updates

#7236 [forgejo] add 11.0
  products/forgejo.md
Labels: release-updates

#7235 [envoy] add 1.34
  products/envoy.md
Labels: release-updates

#7241 Remove unnecessary config
  products/eslint.md
  products/suse-manager.md
  products/veeam-backup-and-replication.md
  products/wordpress.md
Labels: chore

#7242 [ckeditor] Update page
  products/ckeditor.md
Labels: release-updates, product-updates

#7238 [zabbix] Set latestReleaseDate for 5.4
  products/zabbix.md
Labels: release-updates

#7240 [tomcat] Set latestReleaseDate for 5.5 and 6.0
  products/tomcat.md
Labels: release-updates

#7250 [ubuntu] Add 25.04
  products/ubuntu.md
Labels: release-updates

#7249 [tarantool] Add 3.4
  products/tarantool.md
Labels: release-updates

#7247 [ibm-i] Add 7.6
  products/ibm-i.md
Labels: release-updates

#7244 [linux] Add eol date for 6.13.x and update versioninfos
  products/linuxkernel.md
Labels: release-updates

#7258 [nvidia-driver] Update latest 570, 550, 535
  products/nvidia-driver.md
Labels: release-updates

#7254 [apache-airflow] Remove chainguard's dockerhub purl
  products/apache-airflow.md
Labels: release-updates

#7251 Make releaseDate and eol mandatory
  CONTRIBUTING.md
  _plugins/product-data-validator.rb
  products/alibaba-ack.md
  products/bitbucket.md
  products/raspberrypi.md
Labels: enhancement, breaking-change

#7089 [nutanix] Update end of active support & end of life definitions and dates
  products/nutanix-aos.md
  products/nutanix-files.md
  products/nutanix-prism.md
Labels: product-fixes

#7260 [linuxkernel] Annotate EOL dates for latest releases
  products/linuxkernel.md
Labels: chore

#7246 [docker-engine] Add 28.1
  products/docker-engine.md
Labels: release-updates

#7248 [plesk] Add 18.0.69
  products/plesk.md
Labels: release-updates

#7263 [calico] Remove chainguard's dockerhub purl
  products/calico.md
Labels: product-fixes

#7265 [coldfusion] Update coldfusion.md
  products/coldfusion.md
Labels: release-updates

#7271 [pan-os]Updated PAN-OS versions
  products/pan-os.md
Labels: release-updates

#7270 [grafana-loki] Add 3.5 cycle
  products/grafana-loki.md
Labels: release-updates

#7275 Schedule dependabot using a cron expression
  .github/dependabot.yml
Labels: enhancement

#7278 Schedule dependabot using a real cron expression
  .github/dependabot.yml
Labels: bug

#7277 [kubernetes] add 1.33.x version
  products/kubernetes.md
Labels: release-updates

#7281 Revert dependabot to daily config (#7275)
  .github/dependabot.yml
Labels: auto

#7283 [openssl] Fix 404 for 3.5 version
  products/openssl.md
Labels: product-fixes

#7269 [redis] update eol for 6.2
  products/redis.md
Labels: release-updates

#7292 Switch to weekly for bundler / github-actions dependabot updates
  .github/dependabot.yml
Labels: ruby, github_actions

#7282 [bazel] Remove chainguard's purl for dockerhub
  products/bazel.md
Labels: product-fixes

#7276 [harbor] Remove chainguard purls for dockerhub
  products/harbor.md
Labels: product-fixes

#7294 Add a few validation exclusions
  _plugins/product-data-validator.rb
Labels: chore

#7295 Update apache-airflow] Update auto configuration
  products/apache-airflow.md
Labels: auto

#6614 [New product] Veeam Backup for Microsoft 365
  products/veeam-backup-for-microsoft-365.md
Labels: new-product

#7286 [apache-airflow] Add 3
  products/apache-airflow.md
Labels: release-updates

#7289 [jira] Add 10.6
  products/jira.md
Labels: release-updates

#7287 [apache-hop] Add 2.13
  products/apache-hop.md
Labels: release-updates

#7288 [cos] Add cos-121
  products/cos.md
Labels: release-updates

#7291 [rtpengine] Add 13.3
  products/rtpengine.md
Labels: release-updates

#7305 Add empty Lint workflow
  .github/workflows/lint.yml
Labels: enhancement, github_actions
