Repository endoflife-date/endoflife.date, pull requests merged in 2025-03, with the labels that each got.

#6842 [vitess] Add 21 and use only major in releaseCycles
  products/vitess.md
Labels: release-updates, product-updates

#6870 [pan-os]Update PAN-OS version(s)
  products/pan-os.md
Labels: release-updates

#6869 [openssl] Add 3.4 eol date
  products/openssl.md
Labels: release-updates

#6866 docs: add herodevs tags to relevant products.
  products/angular.md
  products/angularjs.md
  products/bootstrap.md
  products/eslint.md
  products/nodejs.md
  products/nuxt.md
  products/protractor.md
  products/vue.md
Labels: product-updates

#6082 [new product] Add Apache NiFi
  products/apache-nifi.md
Labels: new-product

#6092 [new-product] Add greenlight
  products/greenlight.md
Labels: new-product

#6426 [nexus] Add changelogTemplate
  products/nexus.md
Labels: product-updates

#6875 [surface] Set up auto configuration
  products/surface.md
Labels: auto

#6529 [surface] Added some missing devices
  products/surface.md
Labels: release-updates

#6591 [sourcegraph] migrated to private repo
  products/sourcegraph.md
Labels: product-fixes

#6871 Silence Saas deprecation warnings
  Gemfile.lock
  _config.yml
Labels: dependencies, ruby, chore

#6716 [grunt] Add new product.
  products/grunt.md
Labels: new-product

#6873 [aws-lambda] Add .NET 9
  products/aws-lambda.md
Labels: release-updates

#6874 [api-platform] Add 4.1
  products/api-platform.md
Labels: release-updates

#6740 [neo4j] Update 2025
  products/neo4j.md
Labels: release-updates

#6877 [react] Clarify support policy
  products/react.md
Labels: product-updates

#6878 [unity] Add 2022.3.59f1
  products/unity.md
Labels: release-updates

#6884 Ignore validation error for a few links
  _plugins/product-data-validator.rb
Labels: chore

#6883 [nvidia-driver] Drop release image
  products/nvidia-driver.md
Labels: product-updates

#6882 [amazon-corretto] Update changelogTemplate
  products/amazon-corretto.md
Labels: product-updates

#6880 [grunt] Fix changelogTemplate
  products/grunt.md
Labels: product-fixes

#6881 [nexus] Fix a few releases links
  products/nexus.md
Labels: release-updates

#6879 [oracle-database] Fix broken link for 23
  products/oracle-database.md
Labels: release-updates

#6889 [powershell] Exclude preview in regex
  products/powershell.md
Labels: product-updates

#6887 [mssqlserver] Update 2019 CU32
  products/mssqlserver.md
Labels: release-updates

#6890 [api-platform] Make 3.3.x eol instead of 3.4.x
  products/api-platform.md
Labels: release-updates

#6885 Bump wdm to 0.2.0
  Gemfile
Labels: enhancement

#6891 [godot] 4.4 released
  products/godot.md
Labels: release-updates

#6893 [ffmpeg] Update 7.1 LTS
  products/ffmpeg.md
Labels: release-updates

#6903 [nvidia-driver] Update 570.124.06, 572.61
  products/nvidia-driver.md
Labels: release-updates

#6910 [unity] Add missing 2021.3.49
  products/unity.md
Labels: release-updates

#6905 [red-hat-openshift] Add 4.18, Update 4.17 eoas
  products/red-hat-openshift.md
Labels: release-updates

#6906 [red-hat-openshift] Update changelogTemplate
  products/red-hat-openshift.md
Labels: product-updates

#6899 chore: add commercial support to struts.
  products/apache-struts.md
Labels: product-updates

#6920 [plesk] Add 18.0.68
  products/plesk.md
Labels: release-updates

#6918 [hashicorp-vault] Add 1.19
  products/hashicorp-vault.md
Labels: release-updates

#6917 [electron] Add 35
  products/electron.md
Labels: release-updates

#6916 [coder] Add 2.20
  products/coder.md
Labels: release-updates

#6925 [unity] 6000.0.41f1
  products/unity.md
Labels: release-updates

#6919 [nexus] Add 3.78
  products/nexus.md
Labels: release-updates

#6921 [rocket-chat] Add 7.4
  products/rocket-chat.md
Labels: release-updates

#6909 [powershell] Update 5.1 eol
  products/powershell.md
Labels: release-updates

#6734 [New product] Apache Pulsar
  products/apache-pulsar.md
Labels: new-product

#6927 [rocket-chat] Update 7.4 EOL
  products/rocket-chat.md
Labels: release-updates

#6928 [electron] Remove useless whitespaces
  products/electron.md
Labels: product-fixes

#6929 [mariadb] Update support policy
  products/mariadb.md
Labels: product-updates

#6932 [tomcat] Remove whitespaces
  products/tomcat.md
Labels: product-fixes

#6934 [electron] fix node version info
  products/electron.md
Labels: product-fixes

#6936 [freebsd] 13.5 Released
  products/freebsd.md
Labels: release-updates

#6940 [kdeplasma] 6.3.3 released
  products/kdeplasma.md
Labels: release-updates

#6947 [unity] 2022.3.60f1 added
  products/unity.md
Labels: release-updates

#6951 [mssharepoint] Update latest subscription
  products/mssharepoint.md
Labels: release-updates

#6952 [unity] 6000.0.42f1
  products/unity.md
Labels: release-updates

#6953 [mssqlserver] Update 2022 CU18
  products/mssqlserver.md
Labels: release-updates

#6960 [SteamOS] (Re)Add proper EOL date for SteamOS 1.0
  products/steamos.md
Labels: release-updates

#6962 [unrealircd] 6.1.10 release
  products/unrealircd.md
Labels: release-updates

#6963 Update samsungmobile.md
  products/samsungmobile.md
Labels: release-updates

#6961 Clarify meaning of the discontinued column
  CONTRIBUTING.md
  assets/openapi.yml
  product-schema.json
  products/apache-cassandra.md
  products/steamos.md
  products/wordpress.md
Labels: documentation

#6965 [cert-manager] Update release and support policy
  products/cert-manager.md
Labels: product-updates

#6964 Fix product-schema.json link on CONTRIBUTING.md
  CONTRIBUTING.md
  _config.yml
Labels: documentation

#6968 [openjdk-oracle] Add java 23
  products/openjdk-builds-from-oracle.md
Labels: release-updates

#6958 [blender] Simplify and clarify support policy
  products/blender.md
Labels: release-updates, product-updates

#6976 [fairphone] Update EOL for 3, 3+
  products/fairphone.md
Labels: product-fixes

#6972 [gstreamer] Add 1.26
  products/gstreamer.md
Labels: release-updates

#6971 [apache-nifi] Add 2.
  products/apache-nifi.md
Labels: release-updates

#6973 [pan-cortex-xdr] Add 8.7, 7.9.103-ce and 8.3-ce
  products/pan-cortex-xdr.md
Labels: release-updates

#6977 [eks] Use EKS-docs link for 1.24-1.26
  products/eks.md
Labels: product-fixes

#6970 [apache-activemq] Add 5.19
  products/apache-activemq.md
Labels: release-updates

#6979 [apache-http-server] Add missing releaseNotes
  products/apache-http-server.md
Labels: release-updates

#6983 [ckeditor] Fixes eoes date for 4.x cycle
  products/ckeditor.md
Labels: release-updates

#6980 [azure-devops] Update 2022 Update 2 Patch 4, 2020 Update 1 Patch 15, 2019 Update 1 Patch 10
  products/azure-devops.md
Labels: release-updates

#6625 [New product] Alibaba ACK
  products/alibaba-ack.md
Labels: new-product

#6998 [openjdk-builds-from-oracle] Java 24 Released
  products/openjdk-builds-from-oracle.md
Labels: release-updates

#6997 [graalvm] GraalVM 24 Released
  products/graalvm.md
Labels: release-updates

#6996 [oracle-jdk] Java 24 Released
  products/oracle-jdk.md
Labels: release-updates

#6994 [blender] Blender 4.4 released
  products/blender.md
Labels: release-updates

#6987 [linuxkernel] Add 5.11 to 5.14
  products/linuxkernel.md
Labels: release-updates

#6990 [electron] Remove useless whitespaces and fix nodeversion for v2
  products/electron.md
Labels: product-fixes

#6986 [pixel] Split entries containing mutiple models
  products/pixel.md
Labels: release-updates

#6985 [mattermost] Add 10.6
  products/mattermost.md
Labels: release-updates

#6989 [fedora] Fix whitespaces between cycles
  products/fedora.md
Labels: chore

#6969 [neo4j] Update changelogTemplate
  products/neo4j.md
Labels: product-updates

#6984 [new product] weakforced
  products/weakforced.md
Labels: new-product

#7006 [bellsoft-liberica] Add 24
  products/bellsoft-liberica.md
Labels: release-updates

#7004 [amazon-corretto] Add 24
  products/amazon-corretto.md
Labels: release-updates

#7003 [varnish] Add 7.7
  products/varnish.md
Labels: release-updates

#7014 [kotlin] Update last release for 2.1
  products/kotlin.md
Labels: release-updates

#7015 [unity] Update unity.md
  products/unity.md
Labels: release-updates

#7005 [azul-zulu] Add 23/24 and update latest releases
  products/azul-zulu.md
Labels: release-updates

#7016 [kotlin] Update auto config
  products/kotlin.md
Labels: auto

#7011 [mssqlserver] Update 2017 Azure Connect pack
  products/mssqlserver.md
Labels: release-updates

#7024 Update jekyll dependencies
  Gemfile.lock
Labels: dependencies, ruby

#7022 [unity] 6000.0.43 released
  products/unity.md
Labels: release-updates

#7025 [electron] Remove usekess whitespaces
  products/electron.md
Labels: chore

#7030 Add a few validation exclusions
  _plugins/product-data-validator.rb
Labels: chore

#7032 [craft-cms] Update auto configuration
  products/craft-cms.md
Labels: auto

#6604 [new product] Bitbucket
  products/bitbucket.md
Labels: new-product

#7034 [jira][confluence] Update description
  products/confluence.md
  products/jira.md
Labels: product-updates

#7031 [fedora] Fix links for 1 to 19
  products/fedora.md
Labels: release-updates

#7029 [mandrel] Fix 20.3 link
  products/mandrel.md
Labels: release-updates

#7028 [gradle] Fix 8.13 latest release
  products/gradle.md
Labels: release-updates

#7044 [express] Update auto configuration and latest versions
  products/express.md
Labels: release-updates, auto

#7043 [weechat] Add 4.6
  products/weechat.md
Labels: release-updates

#7040 [eclipse-temurin] Add 24
  products/eclipse-temurin.md
Labels: release-updates

#7042 [kuma] Add 2.10
  products/kuma.md
Labels: release-updates

#7038 [apache-flink] Add 2.0 and clarify support policy
  products/apache-flink.md
Labels: release-updates, product-updates

#7039 [cakephp] Add 4.6
  products/cakephp.md
Labels: release-updates

#7045 [linux] 6.14 released
  products/linuxkernel.md
Labels: release-updates

#7035 [bamboo] Add product
  products/bamboo.md
Labels: new-product

#7050 [amazon-cdk] Fix purl link for golang
  products/amazon-cdk.md
Labels: product-fixes

#7049 [mysql] Add 9.2.0 and fix latestReleaseDate value of 8.0.41
  products/mysql.md
Labels: release-updates

#7059 [nix] Add 2.27
  products/nix.md
Labels: release-updates

#7058 [grafana] Add 11.6
  products/grafana.md
Labels: release-updates

#7072 [quarkus] Add 3.21
  products/quarkus.md
Labels: release-updates

#7069 [zabbix] Update last release
  products/zabbix.md
Labels: release-updates

#7067 [cert-manager] Remove purl link which gives 404
  products/cert-manager.md
Labels: product-fixes

#7060 [ghc] Improve automation
  products/ghc.md
Labels: release-updates, auto

#7062 [eks] fix link for 1.27.41
  products/eks.md
Labels: product-fixes

#7063 [bellsoft-liberica] Remove all purl links which were giving 404
  products/bellsoft-liberica.md
Labels: product-fixes

#7075 [react-native] Fix automation
  products/react-native.md
Labels: release-updates, auto

#7074 [traefik] Simplify description
  products/traefik.md
Labels: product-updates, auto

#7068 [envoy] Fix rapidfort purl link
  products/envoy.md
Labels: product-fixes

#7076 [traefik] Improve auto configuration
  products/traefik.md
Labels: auto

#6825 [cockroachdb] Add 25.1
  products/cockroachdb.md
Labels: release-updates

#5014 [new product] opa gatekeeper
  products/gatekeeper.md
Labels: new-product, stale

#7081 [forgejo] Remove git tag
  products/forgejo.md
Labels: product-updates

#7082 Fix a few product's tags
  products/apache-lucene.md
  products/express.md
  products/grunt.md
  products/nvm.md
Labels: product-updates

#7080 [emberjs] Add 6.3
  products/emberjs.md
Labels: release-updates

#7078 [sourcegraph] Add 6 and update auto configuration
  products/sourcegraph.md
Labels: release-updates, auto

#7079 [aws-lambda] Add Ruby 3.4
  products/aws-lambda.md
Labels: release-updates

#7084 [wordpress] Remove pkg:docker/bitnami/wordpress-intel purl
  products/wordpress.md
Labels: product-fixes

#7083 [yarn] Remove nonexisting yarnpkg/cli purl
  products/yarn.md
Labels: product-fixes

#7085 [veeam-backup-and-replication] Update auto configuration
  products/veeam-backup-and-replication.md
Labels: auto
