Repository endoflife-date/endoflife.date, pull requests merged in 2025-08, with the labels that each got.

#7975 [pan-gp] Updated GlobalProtect 6.3.3-c650 latest to 6.3.3-c676
  products/pan-gp.md
Labels: release-updates

#7977 [rancher] update eol for 2.11
  products/rancher.md
Labels: release-updates

#7976 [kyverno] add 1.15
  products/kyverno.md
Labels: release-updates

#7979 [motorola-mobility] Add Motorola Razr 60 models
  products/motorola-mobility.md
Labels: release-updates

#7980 [motorola-mobility] Add Motorola Razr 50 models
  products/motorola-mobility.md
Labels: release-updates

#7981 [motorola-mobility] Add Motorola Edge 60 models
  products/motorola-mobility.md
Labels: release-updates

#7983 [motorola-mobility] Add Motorola Razr 2024/2025 models
  products/motorola-mobility.md
Labels: release-updates

#7984 [motorola-mobility] Add Motorola Edge 50 models
  products/motorola-mobility.md
Labels: release-updates

#7985 [motorola-mobility] Add Motorola edge 2025/2024
  products/motorola-mobility.md
Labels: release-updates

#7986 [motorola-mobility] Add Moto G models
  products/motorola-mobility.md
Labels: release-updates

#7987 [motorola-mobility] Add various Moto models
  products/motorola-mobility.md
Labels: release-updates

#7990 Update disabled auto configuration
  products/coldfusion.md
  products/pop-os.md
  products/unity.md
  products/unrealircd.md
  products/visual-cobol.md
Labels: chore

#7989 [filemaker] Add 2025
  products/filemaker.md
Labels: release-updates

#7988 [oneplus] Fix broken links
  products/oneplus.md
Labels: product-fixes

#7991 [ros] Update product description
  products/ros-2.md
  products/ros.md
Labels: product-updates

#7993 [visual-cobol] Update 10.0
  products/visual-cobol.md
Labels: release-updates

#7303 [new-product] InfluxDB
  products/influxdb.md
Labels: new-product

#8015 Update a few addedAt dates
  products/amazon-msk.md
  products/clearlinux.md
  products/tarteaucitron.md
Labels: chore

#7828 [New Product] : Tailwind
  products/tailwind-css.md
Labels: new-product

#8014 [vuetify] Switch to major for 1
  products/vuetify.md
Labels: release-updates, breaking-change

#8013 [wagtail] Add versions from 0.8 to 2.6
  products/wagtail.md
Labels: release-updates

#8004 [emberjs] Add LTS from 2.4 to 3.20
  products/emberjs.md
Labels: release-updates

#8011 [salt] Add 2014.7 to 3003
  products/salt.md
Labels: release-updates

#8005 [lua] Add 1.1 to 3.1
  products/lua.md
Labels: release-updates

#8006 [mariadb] Add 5.1 to 5.3
  products/mariadb.md
Labels: release-updates

#8010 [postgresql] Add 6.3 to 7.4
  products/postgresql.md
Labels: release-updates

#8009 [nextcloud] Add 9 to 15
  products/nextcloud.md
Labels: release-updates

#8008 [netbsd] Add 1 to 4
  products/netbsd.md
Labels: release-updates

#8001 [django] Add 1.3 to 1.10
  products/django.md
Labels: release-updates

#7994 [nutanix-*] Update descriptions
  products/nutanix-aos.md
  products/nutanix-files.md
  products/nutanix-prism.md
Labels: release-updates, product-updates

#7998 [chrome] Add 7 to 124
  products/chrome.md
Labels: release-updates

#8000 [couchbase-server] Add 1.8 to 5.5
  products/couchbase-server.md
Labels: release-updates

#7997 [alpine-linux] Add 2.1 to 3.6
  products/alpine-linux.md
Labels: release-updates

#7996 [alibaba-ack] Add 1.12 and 1.14
  products/alibaba-ack.md
Labels: release-updates

#8021 [containerd] Update auto configuration
  products/containerd.md
Labels: auto

#8020 [amazon-neptune] Explode 1.0 version
  products/amazon-neptune.md
Labels: release-updates

#8026 [big-ip] Add 17.5 release cycle
  products/big-ip.md
Labels: release-updates

#8039 [samsung] Add Z Fold7, Z Flip7, Z Flip7 FE, M36 5G and F36 5G
  products/samsung-mobile.md
Labels: release-updates

#8033 [cockroachdb] Add 25.3
  products/cockroachdb.md
Labels: release-updates

#8032 [chrome] Add 139
  products/chrome.md
Labels: release-updates

#8045 [mariadb] Add 12.0
  products/mariadb.md
Labels: release-updates

#8030 [keda] update 2.16 and 2.17 eol dates
  products/keda.md
Labels: release-updates, product-updates

#8058 [statamic] Update product
  products/statamic.md
Labels: release-updates, product-updates

#8055 [pan-cortex-xdr] Add 8.9
  products/pan-cortex-xdr.md
Labels: release-updates

#8064 [debian] Add 13.x ( trixie )
  products/debian.md
Labels: release-updates

#8067 Fix a few markdown linting errors
  .github/ISSUE_TEMPLATE/new_product_suggestion.md
  .github/ISSUE_TEMPLATE/report_incorrect_details.md
  CHANGELOG_API.md
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  HACKING.md
  README.md
  pages/help/identifiers-needed.md
  products/amazon-linux.md
  products/amazon-msk.md
  products/centreon.md
  products/citrix-vad.md
  products/firefox.md
  products/freebsd.md
  products/ghc.md
  products/gradle.md
  products/hashicorp-packer.md
  products/intel-processors.md
  products/jhipster.md
  products/ldap-account-manager.md
  products/nvidia-gpu.md
  products/openzfs.md
  products/oracle-linux.md
  products/oracle-solaris.md
  products/pci-dss.md
  products/phoenix-framework.md
  products/redis.md
  recommendations.md
Labels: chore

#8069 Force consistent style across the project
  .markdownlint.yaml
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  HACKING.md
  products/fedora.md
  products/ghc.md
  products/kde-plasma.md
  products/mssqlserver.md
  products/netbsd.md
  products/unity.md
  products/wagtail.md
  products/windows-server.md
  recommendations.md
Labels: chore

#8070 Normalize formatting of non-product files
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_product_suggestion.md
  .github/ISSUE_TEMPLATE/report_incorrect_details.md
  .github/workflows/auto-merge-release-updates.yml
  .github/workflows/check-links.yml
  .github/workflows/lint.yml
  .prettierignore
  .prettierrc
  CONTRIBUTING.md
  HACKING.md
  _config.yml
  api_v1/openapi.yml
  assets/openapi.yml
  assets/register-show-hidden-releases-handler.js
  index.md
  pages/help/identifiers-needed.md
  product-schema.json
  recommendations.md
Labels: chore

#8068 [debian] Update News links for 12.11 and 13.0
  products/debian.md
Labels: release-updates

#8081 [almalinux] Reformat description
  products/almalinux.md
Labels: chore

#8084 [azure-kubernetes-service] Reformat description
  products/azure-kubernetes-service.md
Labels: chore

#8085 [bootstrap] Reformat description
  products/bootstrap.md
Labels: chore

#8090 Exclude Ruby's vendor directory from markdown linting
  .github/workflows/lint.yml
Labels: chore

#8091 [telegraf] Reformat recommandation page
  products/telegraf.md
Labels: chore

#8092 [suse-manager] Reformat recommandation page
  products/suse-manager.md
Labels: chore

#8093 [rust] Reformat recommandation page
  products/rust.md
Labels: chore

#8094 [ruby-on-rails] Reformat recommandation page
  products/ruby-on-rails.md
Labels: chore

#8095 [rhel] Reformat recommandation page
  products/rhel.md
Labels: chore

#8096 [quarkus-framework] Reformat recommandation page
  products/quarkus-framework.md
Labels: chore

#8098 [oracle-linux] Reformat recommandation page
  products/oracle-linux.md
Labels: chore

#8105 [nutanix-aos] Reformat recommandation page
  products/nutanix-aos.md
Labels: chore

#8106 [nodejs] Reformat recommandation page
  products/nodejs.md
Labels: chore

#8104 [nutanix-prism] Reformat recommandation page
  products/nutanix-prism.md
Labels: chore

#8103 [nuxt] Reformat recommandation page
  products/nuxt.md
Labels: chore

#8101 [omnissa-horizon] Reformat recommandation page
  products/omnissa-horizon.md
Labels: chore

#8100 [oneplus] Reformat recommandation page
  products/oneplus.md
Labels: chore

#8108 [nix] Reformat recommandation page
  products/nix.md
Labels: chore

#8109 [nexus] Reformat recommandation page
  products/nexus.md
Labels: chore

#8111 [nextcloud] Reformat recommandation page
  products/nextcloud.md
Labels: chore

#8120 [fortios] Reformat recommandation page
  products/fortios.md
Labels: chore

#8123 [controlm] Reformat recommandation page
  products/controlm.md
Labels: chore

#8125 [cnspec] Reformat recommandation page
  products/cnspec.md
Labels: chore

#8126 [citrix-vad] Reformat recommandation page
  products/citrix-vad.md
Labels: chore

#8127 [boundary] Reformat recommandation page
  products/boundary.md
Labels: chore

#8132 [debian] Update auto configuration
  products/debian.md
Labels: auto

#8133 [azure-kubernetes-service] Update auto configuration
  products/azure-kubernetes-service.md
Labels: release-updates, auto

#8134 [mautic] Declare future releases in auto configuration
  products/mautic.md
Labels: auto

#8136 [silverstripe] Update auto-configuration
  products/silverstripe.md
Labels: auto

#8137 [statamic] Declare 6 in auto-configuration
  products/oracle-graalvm.md
Labels: auto

#8139 [linux] Update releaseImage
  products/linux-kernel.md
Labels: release-updates

#8146 [istio] Move supported Kubernetes version in the main table
  products/istio.md
Labels: product-updates

#8145 Update a few auto configuration
  products/couchbase-server.md
  products/debian.md
  products/mautic.md
  products/oracle-graalvm.md
  products/silverstripe.md
  products/statamic.md
Labels: auto

#8153 [oracle-jdk]: additional CPE identifiers
  products/oracle-jdk.md
Labels: product-updates

#8157 [jira-software] Add 11.0
  products/jira-software.md
Labels: release-updates

#8156 [react-native] Add 0.81
  products/react-native.md
Labels: release-updates

#8155 [nexus] Add 3.83
  products/nexus.md
Labels: release-updates

#8154 [meilisearch] Add 1.17
  products/meilisearch.md
Labels: release-updates

#8060 [sles] Fix automation for .0 releases
  products/sles.md
Labels: release-updates, breaking-change

#8163 [unity] Add 6000.1.16
  products/unity.md
Labels: release-updates

#8171 Add lint-product.sh
  CONTRIBUTING.md
  bin/lint-product.sh
Labels: chore

#8061 [ibm-mq] Add product
  products/ibm-mq.md
Labels: new-product

#8062 [ibm-db2] Add product
  products/ibm-db2.md
Labels: new-product

#8175 [freebsd] Automate new releases detection
  products/freebsd.md
Labels: auto

#8182 [freebsd] Add older releases
  products/freebsd.md
Labels: release-updates, auto

#8169 Use categories for navigation
  _plugins/end-of-life.rb
  _plugins/generate-tag-pages.rb
  _plugins/product-data-enricher.rb
  _plugins/product-data-validator.rb
  api_v1/swagger-ui.md
Labels: enhancement

#8075 Customize 404 page
  404.html
Labels: enhancement

#8183 Move 'All tags' page to the main navigation
  _config.yml
  _plugins/end-of-life.rb
  _plugins/generate-tag-pages.rb
  _plugins/product-data-enricher.rb
Labels: enhancement

#8184 Add a small description to category pages
  CONTRIBUTING.md
  _layouts/product-list.html
  _layouts/product-tags.html
  _plugins/end-of-life.rb
  _plugins/generate-tag-pages.rb
Labels: enhancement

#8185 [splunk] Add cisco tag and disable auto update
  products/splunk.md
Labels: product-updates, auto

#8186 [clearlinux] Add missing discontinued tag
  products/clearlinux.md
Labels: product-updates

#8173 [dce] Update latest for 5.0
  products/dce.md
Labels: release-updates

#8167 [virtualbox] Add 7.2
  products/virtualbox.md
Labels: release-updates

#8165 [argo-cd] Add 3.1
  products/argo-cd.md
Labels: release-updates

#8189 [eurolinux] Add missing discontinued tag
  products/eurolinux.md
Labels: product-updates

#8144 [new product] Apache ActiveMQ Artemis
  products/apache-activemq-artemis.md
  products/apache-activemq.md
Labels: new-product

#8221 [contao] add 5.6
  products/contao.md
Labels: release-updates

#8211 [unity] Revert mixed Enterprise and Industry only versions
  products/unity.md
Labels: release-updates

#8201 [samsung-galaxy-tab] Add Galaxy Tab A9+(2025)
  products/samsung-galaxy-tab.md
Labels: release-updates

#8213 [LibreOffice] Add 25.8
  products/libreoffice.md
Labels: release-updates

#8225 [plesk] Add 18.0.72
  products/plesk.md
Labels: release-updates

#8227 [terraform] Add 1.13
  products/terraform.md
Labels: release-updates

#8242 [surface] Fix release date for laptop-7th-edition-intel-processor
  products/surface.md
Labels: release-updates

#8233 [openwrt] 23.05 is EOL
  products/openwrt.md
Labels: release-updates

#8238 [unity] Add 6000.0.56
  products/unity.md
Labels: release-updates

#8239 [linux-kernel] 6.15 eol
  products/linux-kernel.md
Labels: release-updates

#8256 Implement a retry mechanism for 429 when checking URLs
  _plugins/product-data-validator.rb
  products/freebsd.md
Labels: enhancement

#8250 [rancher] Add 2.12
  products/rancher.md
Labels: release-updates

#8253 [zerto] Update product following HPE acquisition
  products/zerto.md
Labels: product-updates

#8267 [apache-groovy] Add 5.0 cycle
  products/apache-groovy.md
Labels: release-updates

#8278 [citrix-vad] Add release 2507, update changelogTemplate
  products/citrix-vad.md
Labels: release-updates

#8279 [apache-groovy] Fix 4 EOAS
  products/apache-groovy.md
Labels: release-updates

#8281 [vmware-esxi] Add 9.0
  products/vmware-esxi.md
Labels: release-updates

#8283 [apache-groovy] Groovy 5 requires JVM 11+
  products/apache-groovy.md
Labels: release-updates

#8284 Update latest release information for Splunk 9.4
  products/splunk.md
Labels: release-updates

#8286 [unity] Update latest release version and date for 6.2
  products/unity.md
Labels: release-updates

#8296 [tarantool] Add 3.5
  products/tarantool.md
Labels: release-updates

#8292 [influxdb] Add 3.4
  products/influxdb.md
Labels: release-updates

#8301 [api] Ignore no-ambiguous-paths rule during validation
  .github/workflows/lint.yml
  .vacuumignore.yml
Labels: api

#8299 [intel] Adds link and info about PCNs
  products/intel-processors.md
Labels: product-fixes

#8305 [mysql] Fix PURLs
  products/mysql.md
Labels: product-fixes

#8304 [mongodb] Fix PURLs
  products/mongodb.md
Labels: product-fixes

#8303 [mariadb] Fix PURLs
  products/mariadb.md
Labels: product-fixes

#8306 Add validation exclusions for search.maven.org
  _plugins/product-data-validator.rb
Labels: chore

#8308 [ghc] Disable auto update
  products/ghc.md
Labels: auto

#8309 [amazon-linux] Fix regex
  products/amazon-linux.md
Labels: auto

#8310 Fix addedAt fields for SonarQube and Stormshield
  products/sns-firmware.md
  products/sns-hardware.md
  products/sonarqube-community.md
  products/sonarqube-server.md
Labels: chore
