Repository endoflife-date/endoflife.date, pull requests merged in 2025-06, with the labels that each got.

#7603 Fix a few typos on product pages - XYZ
  products/xcp-ng.md
  products/yarn.md
  products/yocto.md
  products/zabbix.md
  products/zentyal.md
  products/zerto.md
  products/zookeeper.md
Labels: chore

#7601 Fix a few typos on product pages - V
  products/veeam-backup-and-replication.md
  products/veeam-one.md
  products/visual-studio.md
  products/vmware-cloud-foundation.md
  products/vmware-esxi.md
  products/vmware-srm.md
  products/vmware-vcenter.md
  products/vue.md
Labels: chore

#7599 Fix a few typos on product pages - T
  products/tails.md
  products/tarantool.md
  products/tomcat.md
  products/typo3.md
Labels: chore

#7595 Fix a few typos on product pages - P
  products/pan-cortex-xdr.md
  products/pan-os.md
  products/perl.md
  products/plone.md
  products/pnpm.md
  products/podman.md
  products/pop-os.md
  products/postfix.md
  products/postmarketos.md
  products/powershell.md
  products/proftpd.md
  products/prometheus.md
  products/proxmox-ve.md
  products/puppet.md
  products/python.md
Labels: chore

#7597 Fix a few typos on product pages - R
  products/rancher.md
  products/raspberry-pi.md
  products/react.md
  products/red-hat-build-of-openjdk.md
  products/red-hat-jboss-eap.md
  products/red-hat-openshift.md
  products/red-hat-satellite.md
  products/redmine.md
  products/rhel.md
  products/rocket-chat.md
  products/rocky-linux.md
  products/roundcube.md
  products/rtpengine.md
  products/ruby.md
Labels: chore

#7594 Fix a few typos on product pages - O
  products/office.md
  products/omnissa-horizon.md
  products/oneplus.md
  products/openbsd.md
  products/opensearch.md
  products/openvpn.md
  products/openzfs.md
  products/opnsense.md
  products/oracle-apex.md
  products/oracle-database.md
  products/oracle-jdk.md
  products/oracle-linux.md
  products/oracle-solaris.md
Labels: chore

#7593 Fix a few typos on product pages - N
  products/neo4j.md
  products/neos.md
  products/netapp-ontap.md
  products/netbsd.md
  products/nextcloud.md
  products/nginx.md
  products/nix.md
  products/nixos.md
  products/nokia.md
  products/numpy.md
  products/nutanix-aos.md
  products/nutanix-files.md
  products/nutanix-prism.md
  products/nvidia-driver.md
  products/nvidia-gpu.md
Labels: chore

#7592 Fix a few typos on product pages - M
  products/macos.md
  products/mageia.md
  products/magento.md
  products/mandrel.md
  products/mariadb.md
  products/mastodon.md
  products/matomo.md
  products/mattermost.md
  products/mautic.md
  products/memcached.md
  products/microsoft-build-of-openjdk.md
  products/moodle.md
  products/motorola-mobility.md
  products/mssqlserver.md
  products/mule-runtime.md
  products/mxlinux.md
  products/mysql.md
Labels: chore

#7591 Fix a few typos on product pages - L
  products/laravel.md
  products/ldap-account-manager.md
  products/libreoffice.md
  products/lineageos.md
  products/linux-kernel.md
  products/linuxmint.md
  products/logstash.md
  products/looker.md
  products/lua.md
Labels: chore

#7590 Fix a few typos on product pages - K
  products/kde-plasma.md
  products/keycloak.md
  products/kibana.md
  products/kong-gateway.md
  products/kubernetes-node-feature-discovery.md
  products/kuma.md
  products/kyverno.md
Labels: chore

#7587 Fix a few typos on product pages - H
  products/haproxy.md
  products/hashicorp-packer.md
  products/hashicorp-vault.md
  products/hbase.md
Labels: chore

#7584 Fix a few typos on product pages - E
  products/eclipse-jetty.md
  products/eclipse-temurin.md
  products/elasticsearch.md
  products/electron.md
  products/emberjs.md
  products/envoy.md
  products/erlang.md
  products/exim.md
Labels: chore

#7585 Fix a few typos on product pages - F
  products/fedora.md
  products/ffmpeg.md
  products/filemaker.md
  products/firefox.md
  products/fluent-bit.md
  products/flux.md
  products/forgejo.md
  products/fortios.md
  products/freebsd.md
Labels: chore

#7582 Fix a few typos on product pages - C
  products/cakephp.md
  products/calico.md
  products/centos-stream.md
  products/centos.md
  products/centreon.md
  products/cert-manager.md
  products/chef-infra-server.md
  products/citrix-vad.md
  products/clamav.md
  products/cnspec.md
  products/cockroachdb.md
  products/coder.md
  products/coldfusion.md
  products/composer.md
  products/confluence.md
  products/containerd.md
  products/contao.md
  products/controlm.md
  products/cos.md
  products/couchbase-server.md
Labels: chore

#7581 Fix a few typos on product pages - B
  products/bamboo.md
  products/beats.md
  products/bellsoft-liberica.md
  products/big-ip.md
  products/bitbucket.md
  products/blender.md
  products/bootstrap.md
  products/bun.md
Labels: chore

#7579 Fix a few typos on product pages - A
  products/akeneo-pim.md
  products/alibaba-dragonwell.md
  products/almalinux.md
  products/alpine-linux.md
  products/android.md
  products/angular.md
  products/angularjs.md
  products/apple-tvos.md
  products/arangodb.md
  products/aws-lambda.md
  products/azul-zulu.md
  products/azure-kubernetes-service.md
Labels: chore

#7577 Fix a few typos on Apache product pages
  products/apache-activemq.md
  products/apache-airflow.md
  products/apache-apisix.md
  products/apache-camel.md
  products/apache-cassandra.md
  products/apache-flink.md
  products/apache-groovy.md
  products/apache-hop.md
  products/apache-kafka.md
  products/apache-spark.md
  products/apache-struts.md
  products/apache-subversion.md
Labels: chore

#7578 Fix a few typos on Amazon product pages
  products/amazon-cdk.md
  products/amazon-corretto.md
  products/amazon-eks.md
  products/amazon-glue.md
  products/amazon-linux.md
  products/amazon-rds-mariadb.md
  products/amazon-rds-mysql.md
  products/amazon-rds-postgresql.md
Labels: chore

#7616 [graalvm] Split to two new product: GraalVM CE and Oracle GraalVM
  products/graalvm-ce.md
  products/graalvm.md
  products/oracle-graalvm.md
Labels: new-product, breaking-change, product-updates

#7572 [firefox] Add 139
  products/firefox.md
Labels: release-updates

#7568 [apache-hop] Add 2.14
  products/apache-hop.md
Labels: release-updates

#7569 [apache-spark] Add 4.0
  products/apache-spark.md
Labels: release-updates

#7574 [plesk] Add 18.0.70
  products/plesk.md
Labels: release-updates

#7571 [erlang] Add 28
  products/erlang.md
Labels: release-updates

#7566 [amazon-eks] Add 1.33
  products/amazon-eks.md
Labels: release-updates

#7620 [Qt] Add 5.15.17
  products/qt.md
Labels: release-updates

#7576 [surface] Add pro-12-inch and laptop-13-inch
  products/surface.md
Labels: release-updates

#7628 [eurolinux] remove links because of project itself became eoled
  products/eurolinux.md
Labels: product-fixes

#7627 [omnissa-horizon] Remove 404 link
  products/omnissa-horizon.md
Labels: product-fixes

#7064 [new product] Liquibase
  products/liquibase.md
Labels: new-product

#7648 [visual-studio] Update 17.13 eol
  products/visual-studio.md
Labels: release-updates

#7644 [mssqlserver] Update 2022 CU19
  products/mssqlserver.md
Labels: release-updates

#7642 [unity] Add 6000.1.6
  products/unity.md
Labels: release-updates

#7634 [coder] Add 2.23
  products/coder.md
Labels: release-updates

#7635 [confluence] Add 9.5
  products/confluence.md
Labels: release-updates

#7638 [neo4j] Add 2025.05
  products/neo4j.md
Labels: release-updates

#7637 [kubernetes-csi-node-driver-registrar] Add 2.14
  products/kubernetes-csi-node-driver-registrar.md
Labels: release-updates

#7653 [alibaba-ack] Add 1.33
  products/alibaba-ack.md
Labels: release-updates

#7655 Update samsung-mobile] Add galaxy-s25-edge and galaxy-f56-5g
  products/samsung-mobile.md
Labels: release-updates

#7656 Align custom and generic auto scripts configuration
  products/amazon-eks.md
  products/amazon-neptune.md
  products/amazon-rds-mariadb.md
  products/amazon-rds-mysql.md
  products/amazon-rds-postgresql.md
  products/apache-http-server.md
  products/apache-subversion.md
  products/artifactory.md
  products/aws-lambda.md
  products/bamboo.md
  products/bitbucket.md
  products/chef-infra-client.md
  products/chef-infra-server.md
  products/chef-inspec.md
  products/coldfusion.md
  products/confluence.md
  products/cos.md
  products/couchbase-server.md
  products/debian.md
  products/firefox.md
  products/ghc.md
  products/google-kubernetes-engine.md
  products/haproxy.md
  products/ibm-aix.md
  products/jira-software.md
  products/kuma.md
  products/libreoffice.md
  products/looker.md
  products/lua.md
  products/netbsd.md
  products/oracle-jdk.md
  products/pan-os.md
  products/php.md
  products/plesk.md
  products/red-hat-jboss-eap.md
  products/red-hat-openshift.md
  products/red-hat-satellite.md
  products/rhel.md
  products/rocky-linux.md
  products/ros.md
  products/sles.md
  products/splunk.md
  products/typo3.md
  products/unity.md
  products/unrealircd.md
  products/virtualbox.md
  products/visual-studio.md
Labels: enhancement

#7654 [ldap-account-manager] Add 9.2
  products/ldap-account-manager.md
Labels: release-updates

#7666 [oracle-graalvm] Fix changelogTemplate
  products/oracle-graalvm.md
Labels: product-fixes

#7667 [liquibase] Update changelogTemplate
  products/liquibase.md
Labels: product-updates

#7680 [android] Add 16 ( Baklava )
  products/android.md
Labels: release-updates

#7683 Update coldfusion.md
  products/coldfusion.md
Labels: release-updates

#7677 [msexchange] Update 2019 CU15 HU2, 2016 CU23 HU16
  products/msexchange.md
Labels: release-updates

#7678 [sharepoint] Update latest Subscription, 2019, 2016
  products/sharepoint.md
Labels: release-updates

#7687 [unity] Add 6000.0.51 and 6000.1.7
  products/unity.md
Labels: release-updates

#7686 [rocky-linux] Add 10.x cycle
  products/rocky-linux.md
Labels: release-updates

#7663 [graalvm-ce] Mark 17 as EOL
  products/graalvm-ce.md
Labels: release-updates

#7697 [vmware-esxi] Update 7.0 Update 3v
  products/vmware-esxi.md
Labels: release-updates

#7691 [istio] Fix 404 purl
  products/istio.md
Labels: product-updates

#7690 [mattermost] Remove maillist link
  products/mattermost.md
Labels: product-updates

#7700 [mariadb] Fix auto configuration
  products/mariadb.md
Labels: auto

#7706 [jira-software] Add 10.7
  products/jira-software.md
Labels: release-updates

#7709 [nexus] Add 3.81
  products/nexus.md
Labels: release-updates

#7712 [umbraco] Add 16
  products/umbraco.md
Labels: release-updates

#7707 [kuma] Add 2.11
  products/kuma.md
Labels: release-updates

#7720 [bamboo] Add changelogTemplate
  products/bamboo.md
Labels: product-updates

#7723 [vmware-vcenter] Remove broken link
  products/vmware-vcenter.md
Labels: product-updates

#7670 [electron] Update nodeVersion to only document the major releases
  products/electron.md
Labels: release-updates, breaking-change, auto

#7730 [shopware] Add 6.7
  products/shopware.md
Labels: release-updates

#7728 [mattermost] Add 10.9
  products/mattermost.md
Labels: release-updates

#7729 [red-hat-openshift] Add 4.19
  products/red-hat-openshift.md
Labels: release-updates

#7727 [kde-plasma] Add 6.4
  products/kde-plasma.md
Labels: release-updates

#7726 [icinga] Add 2.15
  products/icinga.md
Labels: release-updates

#7737 [gitlab] Add 18.1
  products/gitlab.md
Labels: release-updates

#7739 [nvidia-driver] Update 570.158.01, 573.39
  products/nvidia-driver.md
Labels: release-updates

#7741 [apache-kafka] Update for Confluent Community
  products/apache-kafka.md
Labels: release-updates, product-updates

#7643 [windows-server] Update AC and SAC releaseCycles
  products/windows-server.md
Labels: breaking-change, product-updates

#7747 Add a few validation exclusions
  _plugins/product-data-validator.rb
Labels: chore

#7748 [apache-kafka] Update auto configuration
  products/apache-kafka.md
Labels: auto

#7746 [mariadb] Update 5.5, 10.0, 10.1 and 10.2 links
  products/mariadb.md
Labels: release-updates

#7756 [Apache Flink] supported java versions
  products/apache-flink.md
Labels: release-updates

#7770 [kotlin] Add 2.2 cycle
  products/kotlin.md
Labels: release-updates

#7769 [electron] Add v37 cycle
  products/electron.md
Labels: release-updates

#7768 [docker-engine] Add 28.3.x cycle
  products/docker-engine.md
Labels: release-updates

#7775 [postmarketos] Add 25.06
  products/postmarketos.md
Labels: release-updates

#7774 [quarkus-framework] Add 3.24
  products/quarkus-framework.md
Labels: release-updates

#7781 [ghc] Disable ghc-wiki auto configuration
  products/ghc.md
Labels: auto

#7780 [hashicorp-vault] Add 1.20
  products/hashicorp-vault.md
Labels: release-updates

#7773 [clamav] Update maintainer documentation
  products/clamav.md
Labels: documentation

#7785 Fix auto-merge-release-updates.yml workflow
  .github/workflows/auto-merge-release-updates.yml
Labels: chore

#7787 [unity] Add 6000.1.9 release
  products/unity.md
Labels: release-updates

#7790 [mongodb] Automate release date retrieval
  products/mongodb.md
Labels: release-updates, auto

#7141 [new-product] Add GrumPHP
  products/grumphp.md
Labels: new-product

#7179 [new-product] Add Behat
  products/behat.md
  products/grumphp.md
Labels: new-product

#7791 Replace reference links by real links on the homepage
  index.md
Labels: chore

#7797 [grumphp] Update 1 EOL
  products/grumphp.md
Labels: release-updates

#7796 [azure-kubernetes-service] Fix description
  products/azure-kubernetes-service.md
Labels: product-fixes

#7361 feat(api/v1): add known Identifiers
  CHANGELOG_API.md
  CONTRIBUTING.md
  _plugins/generate-api-v1.rb
  api_v1/openapi.yml
Labels: new-product
